// GENERATED by scripts/generate-vendor-directory.mjs. Do not edit by hand.
//
// The vendor roster and its published scores, taken from the live AI Enterprise
// source (fixtures/aie-live/vendors.json, captured 2026-05-07T00:00:00.000Z).
//
// This exists so a client component can look up a vendor's name or score
// without pulling node:fs into the browser bundle. It replaces the name and
// roster lookups that used to come from lib/aie/intelligence/entities.ts, a
// copy of the same source frozen on 8 July 2026 which had drifted far enough
// that every one of 37 overlapping vendors scored higher in it than upstream,
// by 18 points on average.
//
// Regenerate after every sync. If this file is stale the whole product is.

export interface DirectoryVendor {
  id: string;
  name: string;
  category: string | null;
  ownershipType: string | null;
  overallScore: number | null;
  confidenceScore: number | null;
  marketPosition: string | null;
}

/** The capture these figures came from. */
export const VENDOR_DIRECTORY_AS_OF = "2026-05-07T00:00:00.000Z";

export const VENDOR_DIRECTORY: DirectoryVendor[] = [
  {
    "id": "a16z",
    "name": "Andreessen Horowitz",
    "category": "AI investor",
    "ownershipType": "private",
    "overallScore": 54.9,
    "confidenceScore": 97.9,
    "marketPosition": "Specialist contender"
  },
  {
    "id": "ai21",
    "name": "AI21 Labs",
    "category": "Frontier model/API",
    "ownershipType": "private",
    "overallScore": 48.6,
    "confidenceScore": 90.6,
    "marketPosition": "Specialist contender"
  },
  {
    "id": "alibaba",
    "name": "Alibaba",
    "category": "Frontier model/API",
    "ownershipType": "public",
    "overallScore": 62.7,
    "confidenceScore": 95.9,
    "marketPosition": "Major challenger"
  },
  {
    "id": "amd",
    "name": "AMD",
    "category": "AI infrastructure",
    "ownershipType": "public",
    "overallScore": 56.9,
    "confidenceScore": 93.8,
    "marketPosition": "Category leader"
  },
  {
    "id": "anthropic",
    "name": "Anthropic",
    "category": "Frontier model/API",
    "ownershipType": "private",
    "overallScore": 68.3,
    "confidenceScore": 97.8,
    "marketPosition": "Leader"
  },
  {
    "id": "aws",
    "name": "AWS",
    "category": "Cloud AI platform",
    "ownershipType": "public",
    "overallScore": 53,
    "confidenceScore": 97.7,
    "marketPosition": "Major challenger"
  },
  {
    "id": "broadcom",
    "name": "Broadcom",
    "category": "AI infrastructure",
    "ownershipType": "public",
    "overallScore": 58.8,
    "confidenceScore": 98.3,
    "marketPosition": "Major challenger"
  },
  {
    "id": "cerebras",
    "name": "Cerebras",
    "category": "AI infrastructure",
    "ownershipType": "public",
    "overallScore": 55,
    "confidenceScore": 97.1,
    "marketPosition": "Category leader"
  },
  {
    "id": "cohere",
    "name": "Cohere (incl. Aleph Alpha)",
    "category": "Frontier model/API",
    "ownershipType": "private",
    "overallScore": 50.9,
    "confidenceScore": 97.8,
    "marketPosition": "Specialist contender"
  },
  {
    "id": "coreweave",
    "name": "CoreWeave",
    "category": "AI infrastructure",
    "ownershipType": "public",
    "overallScore": 61.9,
    "confidenceScore": 93.6,
    "marketPosition": "Category leader"
  },
  {
    "id": "databricks",
    "name": "Databricks",
    "category": "Cloud AI platform",
    "ownershipType": "private",
    "overallScore": 44,
    "confidenceScore": 97.4,
    "marketPosition": "Category leader"
  },
  {
    "id": "deepseek",
    "name": "DeepSeek",
    "category": "Frontier model/API",
    "ownershipType": "private",
    "overallScore": 62.7,
    "confidenceScore": 97,
    "marketPosition": "Category leader"
  },
  {
    "id": "fireworks",
    "name": "Fireworks AI",
    "category": "AI infrastructure",
    "ownershipType": "private",
    "overallScore": 54.9,
    "confidenceScore": 98.5,
    "marketPosition": "Specialist contender"
  },
  {
    "id": "g42",
    "name": "G42 / Falcon (TII)",
    "category": "Sovereign/regional AI",
    "ownershipType": "private",
    "overallScore": 42.7,
    "confidenceScore": 94.6,
    "marketPosition": "Emerging specialist"
  },
  {
    "id": "glean",
    "name": "Glean",
    "category": "RAG/enterprise search",
    "ownershipType": "private",
    "overallScore": 59.2,
    "confidenceScore": 98.9,
    "marketPosition": "Category leader"
  },
  {
    "id": "google",
    "name": "Google",
    "category": "Cloud AI platform",
    "ownershipType": "public",
    "overallScore": 62.3,
    "confidenceScore": 97.8,
    "marketPosition": "Major challenger"
  },
  {
    "id": "groq",
    "name": "Groq",
    "category": "AI infrastructure",
    "ownershipType": "private",
    "overallScore": 63.7,
    "confidenceScore": 97.7,
    "marketPosition": "Emerging specialist"
  },
  {
    "id": "harvey",
    "name": "Harvey",
    "category": "Regulated-industry AI",
    "ownershipType": "private",
    "overallScore": 56.6,
    "confidenceScore": 98.9,
    "marketPosition": "Category leader"
  },
  {
    "id": "hebbia",
    "name": "Hebbia",
    "category": "RAG/enterprise search",
    "ownershipType": "private",
    "overallScore": 54.1,
    "confidenceScore": 98.4,
    "marketPosition": "Emerging specialist"
  },
  {
    "id": "humain",
    "name": "HUMAIN",
    "category": "Sovereign/regional AI",
    "ownershipType": "private",
    "overallScore": 48.6,
    "confidenceScore": 92.6,
    "marketPosition": "Emerging specialist"
  },
  {
    "id": "ibm",
    "name": "IBM",
    "category": "Regulated-industry AI",
    "ownershipType": "public",
    "overallScore": 45.2,
    "confidenceScore": 97.5,
    "marketPosition": "Specialist contender"
  },
  {
    "id": "lambda",
    "name": "Lambda",
    "category": "AI infrastructure",
    "ownershipType": "private",
    "overallScore": 56.9,
    "confidenceScore": 99,
    "marketPosition": "Emerging specialist"
  },
  {
    "id": "meta",
    "name": "Meta",
    "category": "Frontier model/API",
    "ownershipType": "public",
    "overallScore": 62.1,
    "confidenceScore": 97.8,
    "marketPosition": "Major challenger"
  },
  {
    "id": "mgx",
    "name": "MGX",
    "category": "AI investor",
    "ownershipType": "public",
    "overallScore": 48.5,
    "confidenceScore": 93.1,
    "marketPosition": "Emerging specialist"
  },
  {
    "id": "microsoft",
    "name": "Microsoft",
    "category": "Cloud AI platform",
    "ownershipType": "public",
    "overallScore": 45,
    "confidenceScore": 97.6,
    "marketPosition": "Leader"
  },
  {
    "id": "minimax",
    "name": "MiniMax",
    "category": "Frontier model/API",
    "ownershipType": "private",
    "overallScore": 56.4,
    "confidenceScore": 93.3,
    "marketPosition": "Emerging specialist"
  },
  {
    "id": "mistral",
    "name": "Mistral",
    "category": "Frontier model/API",
    "ownershipType": "private",
    "overallScore": 51.1,
    "confidenceScore": 97.7,
    "marketPosition": "Specialist contender"
  },
  {
    "id": "moonshot",
    "name": "Moonshot AI",
    "category": "Frontier model/API",
    "ownershipType": "private",
    "overallScore": 58.8,
    "confidenceScore": 97.7,
    "marketPosition": "Specialist contender"
  },
  {
    "id": "moveworks",
    "name": "Moveworks",
    "category": "ITSM/HR/service AI",
    "ownershipType": "private",
    "overallScore": 60.6,
    "confidenceScore": 98.5,
    "marketPosition": "Category leader"
  },
  {
    "id": "nscale",
    "name": "Nscale",
    "category": "AI infrastructure",
    "ownershipType": "private",
    "overallScore": 57.2,
    "confidenceScore": 92.8,
    "marketPosition": "Emerging specialist"
  },
  {
    "id": "nvidia",
    "name": "NVIDIA",
    "category": "AI infrastructure",
    "ownershipType": "public",
    "overallScore": 61.5,
    "confidenceScore": 93.5,
    "marketPosition": "Leader"
  },
  {
    "id": "openai",
    "name": "OpenAI",
    "category": "Frontier model/API",
    "ownershipType": "private",
    "overallScore": 68.5,
    "confidenceScore": 97.8,
    "marketPosition": "Leader"
  },
  {
    "id": "oracle",
    "name": "Oracle",
    "category": "Cloud AI platform",
    "ownershipType": "public",
    "overallScore": 53.8,
    "confidenceScore": 98.6,
    "marketPosition": "Category leader"
  },
  {
    "id": "perplexity",
    "name": "Perplexity",
    "category": "Enterprise assistant",
    "ownershipType": "private",
    "overallScore": 49.5,
    "confidenceScore": 95.1,
    "marketPosition": "Specialist contender"
  },
  {
    "id": "rogo",
    "name": "Rogo",
    "category": "Regulated-industry AI",
    "ownershipType": "private",
    "overallScore": 56.4,
    "confidenceScore": 98.7,
    "marketPosition": "Emerging specialist"
  },
  {
    "id": "sakana",
    "name": "Sakana AI",
    "category": "Sovereign/regional AI",
    "ownershipType": "private",
    "overallScore": 55.9,
    "confidenceScore": 97.1,
    "marketPosition": "Emerging specialist"
  },
  {
    "id": "salesforce",
    "name": "Salesforce",
    "category": "CRM/customer AI",
    "ownershipType": "public",
    "overallScore": 55.8,
    "confidenceScore": 98.7,
    "marketPosition": "Major challenger"
  },
  {
    "id": "sap",
    "name": "SAP",
    "category": "Enterprise applications",
    "ownershipType": "public",
    "overallScore": 56.9,
    "confidenceScore": 98.7,
    "marketPosition": "Specialist contender"
  },
  {
    "id": "sequoia",
    "name": "Sequoia Capital",
    "category": "AI investor",
    "ownershipType": "private",
    "overallScore": 53,
    "confidenceScore": 95.9,
    "marketPosition": "Specialist contender"
  },
  {
    "id": "servicenow",
    "name": "ServiceNow",
    "category": "ITSM/HR/service AI",
    "ownershipType": "public",
    "overallScore": 45.7,
    "confidenceScore": 90.6,
    "marketPosition": "Category leader"
  },
  {
    "id": "snowflake",
    "name": "Snowflake",
    "category": "Cloud AI platform",
    "ownershipType": "public",
    "overallScore": 46.7,
    "confidenceScore": 96.7,
    "marketPosition": "Category leader"
  },
  {
    "id": "softbank",
    "name": "SoftBank",
    "category": "AI investor",
    "ownershipType": "public",
    "overallScore": 59,
    "confidenceScore": 77.8,
    "marketPosition": "Specialist contender"
  },
  {
    "id": "together",
    "name": "Together AI",
    "category": "AI infrastructure",
    "ownershipType": "private",
    "overallScore": 56.1,
    "confidenceScore": 96.9,
    "marketPosition": "Specialist contender"
  },
  {
    "id": "tsmc",
    "name": "TSMC",
    "category": "AI infrastructure",
    "ownershipType": "public",
    "overallScore": 64.3,
    "confidenceScore": 87,
    "marketPosition": "Major challenger"
  },
  {
    "id": "writer",
    "name": "Writer",
    "category": "Enterprise assistant",
    "ownershipType": "private",
    "overallScore": 55.2,
    "confidenceScore": 96.9,
    "marketPosition": "Category leader"
  },
  {
    "id": "xai",
    "name": "xAI",
    "category": "Frontier model/API",
    "ownershipType": "private",
    "overallScore": 62.2,
    "confidenceScore": 97.5,
    "marketPosition": "Specialist contender"
  },
  {
    "id": "zai",
    "name": "Z.ai",
    "category": "Frontier model/API",
    "ownershipType": "private",
    "overallScore": 60.1,
    "confidenceScore": 96.1,
    "marketPosition": "Emerging specialist"
  }
];

const BY_ID = new Map(VENDOR_DIRECTORY.map((v) => [v.id, v]));

// The July port renamed five vendors, so any join on id silently dropped them.
// Kept here as well as in live-vendors.ts because this module has to work in
// the browser, where that one cannot go.
const ALIASES: Record<string, string> = {
  "alibaba-qwen": "alibaba",
  "fireworks-ai": "fireworks",
  "moonshot-kimi": "moonshot",
  "together-ai": "together",
  "zhipu-glm": "zai",
};

export function directoryVendor(id: string): DirectoryVendor | null {
  return BY_ID.get(ALIASES[id] ?? id) ?? null;
}

/** A vendor's published name, falling back to the id rather than to blank. */
export function vendorName(id: string): string {
  return directoryVendor(id)?.name ?? id;
}
