// Ported from ranking-engine repo: lib/model-inventory/seed.ts
// Origin snapshot: _archive/ranking-engine-stray-copy-2026-07-08, copied 30 July 2026.

/**
 * Commercial LLM Models seed inventory.
 *
 * Every record cites real official-source URLs (per prompt v2 source list).
 * Per the prompt rules:
 *   - dataStatus = "seed" until live API/docs verification flips it to "documented" (E2)
 *     or "verified" (E3+ with reachable model endpoint)
 *   - confidenceScore in [50,80] for seed records
 *   - lastVerifiedAt = null for seed records
 *   - hosted third-party records keep ownerVendorId pointing at the actual owner
 *     (Anthropic stays Anthropic on Bedrock; OpenAI stays OpenAI on Azure)
 *   - vendors with no confirmed first-party model are explicitly marked
 *     refresh-required or infrastructure-only, never invented
 *
 * NEVER add a model name, model id, or source URL that isn't in the prompt's
 * source list or directly linkable from it.
 */

import type { CommercialModel, CommercialModelSource } from "./types";

const NOW_ISO = "2026-05-10T00:00:00.000Z";

// ──────────────── Source registry (per prompt v2) ────────────────

export const SEED_MODEL_SOURCES: CommercialModelSource[] = [
  // OpenAI
  {
    id: "src_openai_models_docs",
    vendorId: "openai",
    sourceName: "OpenAI, Models documentation",
    sourceUrl: "https://platform.openai.com/docs/models",
    sourceType: "official_model_docs",
    capturedAt: NOW_ISO,
    sourceDate: "2026-05-10",
    evidenceGrade: "E2",
    confidenceScore: 70,
    freshnessStatus: "fresh",
    notes: "Canonical model list. Live API endpoint exists at /v1/models for E3 verification.",
  },
  {
    id: "src_openai_developers_api",
    vendorId: "openai",
    sourceName: "OpenAI, Developers API docs",
    sourceUrl: "https://developers.openai.com/api/docs/models",
    sourceType: "official_api_models_endpoint",
    capturedAt: NOW_ISO,
    sourceDate: "2026-05-10",
    evidenceGrade: "E2",
    confidenceScore: 72,
    freshnessStatus: "fresh",
    notes: "Developer-facing model documentation.",
  },
  // Anthropic
  {
    id: "src_anthropic_models_overview",
    vendorId: "anthropic",
    sourceName: "Anthropic, Claude Models overview",
    sourceUrl: "https://docs.anthropic.com/en/docs/about-claude/models/overview",
    sourceType: "official_model_docs",
    capturedAt: NOW_ISO,
    sourceDate: "2026-05-10",
    evidenceGrade: "E2",
    confidenceScore: 75,
    freshnessStatus: "fresh",
    notes: "Canonical Claude model family list.",
  },
  {
    id: "src_anthropic_models_list_api",
    vendorId: "anthropic",
    sourceName: "Anthropic, models-list API",
    sourceUrl: "https://docs.anthropic.com/en/api/models-list",
    sourceType: "official_api_models_endpoint",
    capturedAt: NOW_ISO,
    sourceDate: "2026-05-10",
    evidenceGrade: "E2",
    confidenceScore: 76,
    freshnessStatus: "fresh",
    notes: "Live model list endpoint enables E3 verification when reachable.",
  },
  // Google
  {
    id: "src_google_gemini_api_models",
    vendorId: "googl",
    sourceName: "Google AI, Gemini API model docs",
    sourceUrl: "https://ai.google.dev/gemini-api/docs/models",
    sourceType: "official_model_docs",
    capturedAt: NOW_ISO,
    sourceDate: "2026-05-10",
    evidenceGrade: "E2",
    confidenceScore: 74,
    freshnessStatus: "fresh",
    notes: "Gemini API model documentation.",
  },
  {
    id: "src_google_vertex_models",
    vendorId: "googl",
    sourceName: "Google Cloud, Vertex AI generative models",
    sourceUrl: "https://cloud.google.com/vertex-ai/generative-ai/docs/models",
    sourceType: "official_model_catalog",
    capturedAt: NOW_ISO,
    sourceDate: "2026-05-10",
    evidenceGrade: "E2",
    confidenceScore: 72,
    freshnessStatus: "fresh",
    notes: "Vertex catalog distinguishes first-party vs partner models.",
  },
  // Mistral
  {
    id: "src_mistral_models",
    vendorId: "mistral",
    sourceName: "Mistral AI, Models documentation",
    sourceUrl: "https://docs.mistral.ai/models",
    sourceType: "official_model_docs",
    capturedAt: NOW_ISO,
    sourceDate: "2026-05-10",
    evidenceGrade: "E2",
    confidenceScore: 70,
    freshnessStatus: "fresh",
    notes: "Mistral premier/open/labs/deprecated lifecycle.",
  },
  // Cohere
  {
    id: "src_cohere_models",
    vendorId: "cohere",
    sourceName: "Cohere, Models documentation",
    sourceUrl: "https://docs.cohere.com/docs/models",
    sourceType: "official_model_docs",
    capturedAt: NOW_ISO,
    sourceDate: "2026-05-10",
    evidenceGrade: "E2",
    confidenceScore: 70,
    freshnessStatus: "fresh",
    notes: "Command / Embed / Rerank / Aya families.",
  },
  // xAI
  {
    id: "src_xai_models",
    vendorId: "xai",
    sourceName: "xAI, Models documentation",
    sourceUrl: "https://docs.x.ai/docs/models",
    sourceType: "official_model_docs",
    capturedAt: NOW_ISO,
    sourceDate: "2026-05-10",
    evidenceGrade: "E2",
    confidenceScore: 65,
    freshnessStatus: "fresh",
    notes: "Grok model availability.",
  },
  // AWS Bedrock
  {
    id: "src_aws_bedrock_models",
    vendorId: "amzn",
    sourceName: "AWS, Bedrock supported foundation models",
    sourceUrl: "https://docs.aws.amazon.com/bedrock/latest/userguide/models-supported.html",
    sourceType: "official_marketplace_docs",
    capturedAt: NOW_ISO,
    sourceDate: "2026-05-10",
    evidenceGrade: "E2",
    confidenceScore: 78,
    freshnessStatus: "fresh",
    notes: "Bedrock catalog. Hosted third-party models keep their original owner.",
  },
  // Microsoft / Azure AI Foundry
  {
    id: "src_azure_ai_foundry_models",
    vendorId: "msft",
    sourceName: "Azure AI Foundry, Models",
    sourceUrl: "https://learn.microsoft.com/en-us/azure/ai-foundry/foundry-models/overview",
    sourceType: "official_marketplace_docs",
    capturedAt: NOW_ISO,
    sourceDate: "2026-05-10",
    evidenceGrade: "E2",
    confidenceScore: 76,
    freshnessStatus: "fresh",
    notes: "Foundry catalog includes Microsoft Phi/MAI plus partner models from OpenAI / Anthropic / Mistral / Cohere / Meta / xAI.",
  },
  {
    id: "src_azure_ai_foundry_partners",
    vendorId: "msft",
    sourceName: "Azure AI Foundry, Models from partners",
    sourceUrl: "https://learn.microsoft.com/en-us/azure/ai-foundry/foundry-models/concepts/models-from-partners",
    sourceType: "official_marketplace_docs",
    capturedAt: NOW_ISO,
    sourceDate: "2026-05-10",
    evidenceGrade: "E2",
    confidenceScore: 76,
    freshnessStatus: "fresh",
    notes: "Distinguishes Microsoft-owned models from hosted partner models.",
  },
  // IBM
  {
    id: "src_ibm_watsonx_foundation_models",
    vendorId: "ibm",
    sourceName: "IBM, watsonx.ai foundation models",
    sourceUrl: "https://www.ibm.com/products/watsonx-ai/foundation-models",
    sourceType: "official_model_docs",
    capturedAt: NOW_ISO,
    sourceDate: "2026-05-10",
    evidenceGrade: "E2",
    confidenceScore: 70,
    freshnessStatus: "fresh",
    notes: "Granite families plus hosted third-party models.",
  },
  // Oracle
  {
    id: "src_oracle_genai_models",
    vendorId: "orcl",
    sourceName: "Oracle, OCI Generative AI pretrained models",
    sourceUrl: "https://docs.oracle.com/en-us/iaas/Content/generative-ai/pretrained-models.htm",
    sourceType: "official_marketplace_docs",
    capturedAt: NOW_ISO,
    sourceDate: "2026-05-10",
    evidenceGrade: "E2",
    confidenceScore: 70,
    freshnessStatus: "fresh",
    notes: "OCI hosts Cohere / Meta / Mistral / xAI; Oracle is host, not owner.",
  },
  // Salesforce
  {
    id: "src_salesforce_agentforce_models",
    vendorId: "crm",
    sourceName: "Salesforce, Agentforce supported models",
    sourceUrl: "https://developer.salesforce.com/docs/ai/agentforce/guide/supported-models.html",
    sourceType: "official_product_docs",
    capturedAt: NOW_ISO,
    sourceDate: "2026-05-10",
    evidenceGrade: "E2",
    confidenceScore: 70,
    freshnessStatus: "fresh",
    notes: "Salesforce orchestrates external providers via Einstein Trust Layer.",
  },
  // ServiceNow
  {
    id: "src_now_llm_docs",
    vendorId: "now",
    sourceName: "ServiceNow, Now LLM exploration",
    sourceUrl: "https://www.servicenow.com/docs/r/intelligent-experiences/servicenow-large-language-model-now-llm/exploring-large-language-models.html",
    sourceType: "official_product_docs",
    capturedAt: NOW_ISO,
    sourceDate: "2026-05-10",
    evidenceGrade: "E2",
    confidenceScore: 65,
    freshnessStatus: "fresh",
    notes: "Now LLM is a domain LLM; third-party LLMs accessed via Now LLM Service are hosted/orchestrated.",
  },
  // Writer
  {
    id: "src_writer_palmyra_models",
    vendorId: "writer",
    sourceName: "Writer, Palmyra models",
    sourceUrl: "https://dev.writer.com/home/models",
    sourceType: "official_model_docs",
    capturedAt: NOW_ISO,
    sourceDate: "2026-05-10",
    evidenceGrade: "E2",
    confidenceScore: 68,
    freshnessStatus: "fresh",
    notes: "Palmyra family.",
  },
  // Glean
  {
    id: "src_glean_llms",
    vendorId: "glean",
    sourceName: "Glean, LLM administration",
    sourceUrl: "https://docs.glean.com/administration/llms",
    sourceType: "official_product_docs",
    capturedAt: NOW_ISO,
    sourceDate: "2026-05-10",
    evidenceGrade: "E2",
    confidenceScore: 65,
    freshnessStatus: "fresh",
    notes: "Glean hosts/orchestrates external LLMs; retains original owner.",
  },
  // Harvey
  {
    id: "src_harvey_models",
    vendorId: "harvey",
    sourceName: "Harvey, supported AI models",
    sourceUrl: "https://help.harvey.ai/articles/what-ai-models-does-harvey-use",
    sourceType: "official_product_docs",
    capturedAt: NOW_ISO,
    sourceDate: "2026-05-10",
    evidenceGrade: "E2",
    confidenceScore: 60,
    freshnessStatus: "fresh",
    notes: "Harvey uses third-party models; Harvey is application/orchestration vendor.",
  },
  // Moveworks (not in our vendor list, included via lookup)
  // Perplexity
  {
    id: "src_perplexity_pending",
    vendorId: "perplexity",
    sourceName: "Perplexity, Sonar / Enterprise Pro docs (pending verification)",
    sourceUrl: "https://docs.perplexity.ai/",
    sourceType: "seed_placeholder",
    capturedAt: NOW_ISO,
    sourceDate: "2026-05-10",
    evidenceGrade: "E1",
    confidenceScore: 45,
    freshnessStatus: "unknown",
    notes: "Source list incomplete; Sonar API docs require verification before enabling models.",
  },
  // NVIDIA, Nemotron is a first-party family per developer.nvidia.com.
  {
    id: "src_nvidia_nemotron",
    vendorId: "nvda",
    sourceName: "NVIDIA, Nemotron developer hub",
    sourceUrl: "https://developer.nvidia.com/nemotron",
    sourceType: "official_model_docs",
    capturedAt: NOW_ISO,
    sourceDate: "2026-05-13",
    evidenceGrade: "E2",
    confidenceScore: 72,
    freshnessStatus: "fresh",
    notes: "Nemotron 3 series, Nano / Super / multimodal / RAG / Speech / Safety variants.",
  },
  // Meta, Llama series owner.
  {
    id: "src_meta_llama",
    vendorId: "meta",
    sourceName: "Meta, Llama overview",
    sourceUrl: "https://www.llama.com/docs/overview/",
    sourceType: "official_model_docs",
    capturedAt: NOW_ISO,
    sourceDate: "2026-05-13",
    evidenceGrade: "E2",
    confidenceScore: 72,
    freshnessStatus: "fresh",
    notes: "Llama family overview, Meta is the original owner.",
  },
  // DeepSeek
  {
    id: "src_deepseek_models",
    vendorId: "deepseek",
    sourceName: "DeepSeek, pricing & model docs",
    sourceUrl: "https://api-docs.deepseek.com/quick_start/pricing",
    sourceType: "official_pricing_page",
    capturedAt: NOW_ISO,
    sourceDate: "2026-05-13",
    evidenceGrade: "E2",
    confidenceScore: 70,
    freshnessStatus: "fresh",
    notes: "DeepSeek v4 series. deepseek-chat / deepseek-reasoner are compatibility aliases.",
  },
  // Alibaba / Qwen, global frontier family.
  {
    id: "src_alibaba_qwen",
    vendorId: "alibaba",
    sourceName: "Alibaba Cloud, Model Studio (Qwen)",
    sourceUrl: "https://www.alibabacloud.com/help/en/model-studio/models",
    sourceType: "official_model_docs",
    capturedAt: NOW_ISO,
    sourceDate: "2026-05-13",
    evidenceGrade: "E2",
    confidenceScore: 70,
    freshnessStatus: "fresh",
    notes: "Qwen3 / Qwen3.5 series + QwQ reasoning family.",
  },
  // Moonshot AI / Kimi.
  {
    id: "src_moonshot_kimi",
    vendorId: "moonshot",
    sourceName: "Moonshot AI, Platform docs (Kimi)",
    sourceUrl: "https://platform.moonshot.ai",
    sourceType: "official_model_docs",
    capturedAt: NOW_ISO,
    sourceDate: "2026-05-13",
    evidenceGrade: "E2",
    confidenceScore: 70,
    freshnessStatus: "fresh",
    notes: "Kimi K2 series.",
  },
  // Z.ai / Zhipu, GLM family.
  {
    id: "src_zai_glm",
    vendorId: "zai",
    sourceName: "Z.ai, GLM model docs",
    sourceUrl: "https://docs.z.ai/guides/llm/glm-5.1",
    sourceType: "official_model_docs",
    capturedAt: NOW_ISO,
    sourceDate: "2026-05-13",
    evidenceGrade: "E2",
    confidenceScore: 68,
    freshnessStatus: "fresh",
    notes: "GLM-5.1 frontier model.",
  },
  // MiniMax.
  {
    id: "src_minimax_models",
    vendorId: "minimax",
    sourceName: "MiniMax, Platform model docs",
    sourceUrl: "https://platform.minimax.io/docs/guides/models-intro",
    sourceType: "official_model_docs",
    capturedAt: NOW_ISO,
    sourceDate: "2026-05-13",
    evidenceGrade: "E2",
    confidenceScore: 68,
    freshnessStatus: "fresh",
    notes: "MiniMax M2 series + her-variant.",
  },
  // AI21 Labs, Jamba.
  {
    id: "src_ai21_jamba",
    vendorId: "ai21",
    sourceName: "AI21, Jamba foundation models",
    sourceUrl: "https://docs.ai21.com/docs/jamba-foundation-models",
    sourceType: "official_model_docs",
    capturedAt: NOW_ISO,
    sourceDate: "2026-05-13",
    evidenceGrade: "E2",
    confidenceScore: 70,
    freshnessStatus: "fresh",
    notes: "Jamba Large / Mini hybrid Mamba+Transformer architecture.",
  },
  // Aleph Alpha, Pharia.
  {
    id: "src_aleph_alpha_pharia",
    vendorId: "aleph",
    sourceName: "Aleph Alpha, Pharia model variants",
    sourceUrl: "https://docs.aleph-alpha.com/phariaai-dev-guide/latest/pharia-llm/model-variants.html",
    sourceType: "official_model_docs",
    capturedAt: NOW_ISO,
    sourceDate: "2026-05-13",
    evidenceGrade: "E1",
    confidenceScore: 55,
    freshnessStatus: "fresh",
    notes: "Pharia model variants, weight-available release; commercial API availability unclear.",
  },
  // Snowflake Arctic, first-party open enterprise LLM family.
  {
    id: "src_snowflake_arctic",
    vendorId: "snow",
    sourceName: "Snowflake, Arctic model family",
    sourceUrl: "https://www.snowflake.com/en/product/features/arctic/",
    sourceType: "official_product_docs",
    capturedAt: NOW_ISO,
    sourceDate: "2026-05-13",
    evidenceGrade: "E2",
    confidenceScore: 70,
    freshnessStatus: "fresh",
    notes: "Snowflake Arctic, first-party / open-weight enterprise LLM. Cortex hosts third-party models separately.",
  },
];

// ──────────────── Models ────────────────
//
// Helper to keep records consistent. All seed records use these defaults; any
// field can be overridden per-record.
function model(partial: Partial<CommercialModel> & {
  id: string;
  vendorId: string;
  vendorName: string;
  modelName: string;
  modelFamily: string;
  ownerVendorId: string;
  ownerVendorName: string;
  ownershipType: CommercialModel["ownershipType"];
  availabilityStage: CommercialModel["availabilityStage"];
  commercialAvailability: CommercialModel["commercialAvailability"];
  modelCategory: CommercialModel["modelCategory"];
  sourceIds: string[];
  sourceUrls: string[];
  sourceNames: string[];
}): CommercialModel {
  return {
    hostingVendorId: partial.ownerVendorId === partial.vendorId ? null : partial.vendorId,
    hostingVendorName: partial.ownerVendorId === partial.vendorId ? null : partial.vendorName,
    modelId: null,
    modality: ["text"],
    accessChannel: "api",
    contextWindow: null,
    inputModalities: ["text"],
    outputModalities: ["text"],
    toolSupport: [],
    pricingSummary: null,
    sourceDate: "2026-05-10",
    capturedAt: NOW_ISO,
    evidenceGrade: "E2",
    confidenceScore: 70,
    dataStatus: "seed",
    uncertaintyNote: "Seed record from official documentation URL. Live verification (API model-list endpoint) required to flip to verified.",
    lifecycleStatus:
      partial.availabilityStage === "ga" ? "active"
        : partial.availabilityStage === "preview" ? "preview"
        : partial.availabilityStage === "beta" ? "beta"
        : partial.availabilityStage === "deprecated" ? "deprecated"
        : partial.availabilityStage === "retired" ? "retired"
        : "unknown",
    deprecationDate: null,
    lastVerifiedAt: null,
    ...partial,
  } as CommercialModel;
}

export const SEED_MODELS: CommercialModel[] = [
  // ───────────── OpenAI (first-party) ─────────────
  // Refreshed to current source-backed API catalog. Family includes size
  // variants (mini / nano) and the reasoning o-series alongside the
  // flagship multimodal line.
  model({
    id: "model_openai_gpt55",
    vendorId: "openai", vendorName: "OpenAI",
    ownerVendorId: "openai", ownerVendorName: "OpenAI",
    modelName: "GPT-5.5", modelFamily: "GPT", modelCategory: "multimodal",
    ownershipType: "first_party", availabilityStage: "ga",
    commercialAvailability: "api_available",
    inputModalities: ["text", "image"], outputModalities: ["text"], toolSupport: ["function_calling"],
    sourceIds: ["src_openai_models_docs", "src_openai_developers_api"],
    sourceUrls: ["https://platform.openai.com/docs/models", "https://developers.openai.com/api/docs/models"],
    sourceNames: ["OpenAI, Models documentation", "OpenAI, Developers API docs"],
  }),
  model({
    id: "model_openai_gpt54",
    vendorId: "openai", vendorName: "OpenAI",
    ownerVendorId: "openai", ownerVendorName: "OpenAI",
    modelName: "GPT-5.4", modelFamily: "GPT", modelCategory: "multimodal",
    ownershipType: "first_party", availabilityStage: "ga",
    commercialAvailability: "api_available",
    sourceIds: ["src_openai_models_docs", "src_openai_developers_api"],
    sourceUrls: ["https://platform.openai.com/docs/models", "https://developers.openai.com/api/docs/models"],
    sourceNames: ["OpenAI, Models documentation", "OpenAI, Developers API docs"],
  }),
  model({
    id: "model_openai_gpt54_mini",
    vendorId: "openai", vendorName: "OpenAI",
    ownerVendorId: "openai", ownerVendorName: "OpenAI",
    modelName: "GPT-5.4 mini", modelFamily: "GPT", modelCategory: "llm_text",
    ownershipType: "first_party", availabilityStage: "ga",
    commercialAvailability: "api_available",
    sourceIds: ["src_openai_models_docs"],
    sourceUrls: ["https://platform.openai.com/docs/models"],
    sourceNames: ["OpenAI, Models documentation"],
  }),
  model({
    id: "model_openai_gpt54_nano",
    vendorId: "openai", vendorName: "OpenAI",
    ownerVendorId: "openai", ownerVendorName: "OpenAI",
    modelName: "GPT-5.4 nano", modelFamily: "GPT", modelCategory: "llm_text",
    ownershipType: "first_party", availabilityStage: "ga",
    commercialAvailability: "api_available",
    sourceIds: ["src_openai_models_docs"],
    sourceUrls: ["https://platform.openai.com/docs/models"],
    sourceNames: ["OpenAI, Models documentation"],
  }),
  model({
    id: "model_openai_o4",
    vendorId: "openai", vendorName: "OpenAI",
    ownerVendorId: "openai", ownerVendorName: "OpenAI",
    modelName: "o4 reasoning series", modelFamily: "o-series", modelCategory: "reasoning",
    ownershipType: "first_party", availabilityStage: "ga",
    commercialAvailability: "api_available",
    sourceIds: ["src_openai_models_docs"],
    sourceUrls: ["https://platform.openai.com/docs/models"],
    sourceNames: ["OpenAI, Models documentation"],
    uncertaintyNote: "Reasoning-tier model family per official model docs. Variants and exact model IDs require live API verification.",
  }),

  // ───────────── Anthropic (first-party) ─────────────
  model({
    id: "model_anthropic_claude_opus_47",
    vendorId: "anthropic", vendorName: "Anthropic",
    ownerVendorId: "anthropic", ownerVendorName: "Anthropic",
    modelName: "Claude Opus 4.7", modelFamily: "Claude", modelCategory: "multimodal",
    ownershipType: "first_party", availabilityStage: "ga",
    commercialAvailability: "api_available",
    inputModalities: ["text", "image"], outputModalities: ["text"], toolSupport: ["function_calling", "computer_use"],
    contextWindow: 1_000_000,
    sourceIds: ["src_anthropic_models_overview", "src_anthropic_models_list_api"],
    sourceUrls: ["https://docs.anthropic.com/en/docs/about-claude/models/overview", "https://docs.anthropic.com/en/api/models-list"],
    sourceNames: ["Anthropic, Claude Models overview", "Anthropic, models-list API"],
  }),
  model({
    id: "model_anthropic_claude_sonnet_46",
    vendorId: "anthropic", vendorName: "Anthropic",
    ownerVendorId: "anthropic", ownerVendorName: "Anthropic",
    modelName: "Claude Sonnet 4.6", modelFamily: "Claude", modelCategory: "llm_text",
    ownershipType: "first_party", availabilityStage: "ga",
    commercialAvailability: "api_available",
    sourceIds: ["src_anthropic_models_overview"],
    sourceUrls: ["https://platform.claude.com/docs/en/about-claude/models/overview"],
    sourceNames: ["Anthropic, Claude Models overview"],
  }),
  model({
    id: "model_anthropic_claude_haiku_45",
    vendorId: "anthropic", vendorName: "Anthropic",
    ownerVendorId: "anthropic", ownerVendorName: "Anthropic",
    modelName: "Claude Haiku 4.5", modelFamily: "Claude", modelCategory: "llm_text",
    ownershipType: "first_party", availabilityStage: "ga",
    commercialAvailability: "api_available",
    sourceIds: ["src_anthropic_models_overview"],
    sourceUrls: ["https://platform.claude.com/docs/en/about-claude/models/overview"],
    sourceNames: ["Anthropic, Claude Models overview"],
  }),

  // ───────────── Google (first-party) ─────────────
  // Refreshed to current Gemini 3.x line alongside the 2.5 generation
  // which remains supported. Gemma stays open-weight.
  model({
    id: "model_google_gemini_31_pro",
    vendorId: "googl", vendorName: "Alphabet",
    ownerVendorId: "googl", ownerVendorName: "Alphabet",
    modelName: "Gemini 3.1 Pro", modelFamily: "Gemini", modelCategory: "multimodal",
    ownershipType: "first_party", availabilityStage: "ga",
    commercialAvailability: "api_available",
    inputModalities: ["text", "image", "audio", "video"], outputModalities: ["text"],
    sourceIds: ["src_google_gemini_api_models", "src_google_vertex_models"],
    sourceUrls: ["https://ai.google.dev/gemini-api/docs/models"],
    sourceNames: ["Google AI, Gemini API model docs"],
  }),
  model({
    id: "model_google_gemini_3_flash",
    vendorId: "googl", vendorName: "Alphabet",
    ownerVendorId: "googl", ownerVendorName: "Alphabet",
    modelName: "Gemini 3 Flash", modelFamily: "Gemini", modelCategory: "multimodal",
    ownershipType: "first_party", availabilityStage: "ga",
    commercialAvailability: "api_available",
    sourceIds: ["src_google_gemini_api_models"],
    sourceUrls: ["https://ai.google.dev/gemini-api/docs/models"],
    sourceNames: ["Google AI, Gemini API model docs"],
  }),
  model({
    id: "model_google_gemini_31_flash_lite",
    vendorId: "googl", vendorName: "Alphabet",
    ownerVendorId: "googl", ownerVendorName: "Alphabet",
    modelName: "Gemini 3.1 Flash-Lite", modelFamily: "Gemini", modelCategory: "llm_text",
    ownershipType: "first_party", availabilityStage: "ga",
    commercialAvailability: "api_available",
    sourceIds: ["src_google_gemini_api_models"],
    sourceUrls: ["https://ai.google.dev/gemini-api/docs/models"],
    sourceNames: ["Google AI, Gemini API model docs"],
  }),
  model({
    id: "model_google_gemini_25_pro",
    vendorId: "googl", vendorName: "Alphabet",
    ownerVendorId: "googl", ownerVendorName: "Alphabet",
    modelName: "Gemini 2.5 Pro", modelFamily: "Gemini", modelCategory: "multimodal",
    ownershipType: "first_party", availabilityStage: "ga",
    commercialAvailability: "api_available",
    inputModalities: ["text", "image", "audio", "video"], outputModalities: ["text"],
    sourceIds: ["src_google_gemini_api_models", "src_google_vertex_models"],
    sourceUrls: ["https://ai.google.dev/gemini-api/docs/models", "https://cloud.google.com/vertex-ai/generative-ai/docs/models"],
    sourceNames: ["Google AI, Gemini API model docs", "Google Cloud, Vertex AI generative models"],
  }),
  model({
    id: "model_google_gemini_25_flash",
    vendorId: "googl", vendorName: "Alphabet",
    ownerVendorId: "googl", ownerVendorName: "Alphabet",
    modelName: "Gemini 2.5 Flash", modelFamily: "Gemini", modelCategory: "multimodal",
    ownershipType: "first_party", availabilityStage: "ga",
    commercialAvailability: "api_available",
    sourceIds: ["src_google_gemini_api_models"],
    sourceUrls: ["https://ai.google.dev/gemini-api/docs/models"],
    sourceNames: ["Google AI, Gemini API model docs"],
  }),
  model({
    id: "model_google_gemma3",
    vendorId: "googl", vendorName: "Alphabet",
    ownerVendorId: "googl", ownerVendorName: "Alphabet",
    modelName: "Gemma 3", modelFamily: "Gemma", modelCategory: "llm_text",
    ownershipType: "open_weight", availabilityStage: "ga",
    commercialAvailability: "api_available",
    sourceIds: ["src_google_gemini_api_models"],
    sourceUrls: ["https://ai.google.dev/gemini-api/docs/models"],
    sourceNames: ["Google AI, Gemini API model docs"],
    uncertaintyNote: "Open-weight family. Commercial use governed by Gemma terms; not a hosted commercial API in the same sense as Gemini.",
  }),

  // ───────────── Mistral (first-party) ─────────────
  // Expanded to current source-backed family per docs.mistral.ai.
  model({
    id: "model_mistral_large_3",
    vendorId: "mistral", vendorName: "Mistral AI",
    ownerVendorId: "mistral", ownerVendorName: "Mistral AI",
    modelName: "Mistral Large 3", modelFamily: "Mistral premier", modelCategory: "multimodal",
    ownershipType: "first_party", availabilityStage: "ga",
    commercialAvailability: "api_available",
    sourceIds: ["src_mistral_models"],
    sourceUrls: ["https://docs.mistral.ai/models/overview"],
    sourceNames: ["Mistral AI, Models overview"],
  }),
  model({
    id: "model_mistral_medium_35",
    vendorId: "mistral", vendorName: "Mistral AI",
    ownerVendorId: "mistral", ownerVendorName: "Mistral AI",
    modelName: "Mistral Medium 3.5", modelFamily: "Mistral premier", modelCategory: "llm_text",
    ownershipType: "first_party", availabilityStage: "ga",
    commercialAvailability: "api_available",
    sourceIds: ["src_mistral_models"],
    sourceUrls: ["https://docs.mistral.ai/models/overview"],
    sourceNames: ["Mistral AI, Models overview"],
  }),
  model({
    id: "model_mistral_small_4",
    vendorId: "mistral", vendorName: "Mistral AI",
    ownerVendorId: "mistral", ownerVendorName: "Mistral AI",
    modelName: "Mistral Small 4", modelFamily: "Mistral premier", modelCategory: "llm_text",
    ownershipType: "first_party", availabilityStage: "ga",
    commercialAvailability: "api_available",
    sourceIds: ["src_mistral_models"],
    sourceUrls: ["https://docs.mistral.ai/models/overview"],
    sourceNames: ["Mistral AI, Models overview"],
  }),
  model({
    id: "model_mistral_ministral_3",
    vendorId: "mistral", vendorName: "Mistral AI",
    ownerVendorId: "mistral", ownerVendorName: "Mistral AI",
    modelName: "Ministral 3", modelFamily: "Ministral", modelCategory: "llm_text",
    ownershipType: "first_party", availabilityStage: "ga",
    commercialAvailability: "api_available",
    sourceIds: ["src_mistral_models"],
    sourceUrls: ["https://docs.mistral.ai/models/overview"],
    sourceNames: ["Mistral AI, Models overview"],
    uncertaintyNote: "Edge-optimised family. Variants (3B / 8B) require live API verification.",
  }),
  model({
    id: "model_mistral_magistral_medium_12",
    vendorId: "mistral", vendorName: "Mistral AI",
    ownerVendorId: "mistral", ownerVendorName: "Mistral AI",
    modelName: "Magistral Medium 1.2", modelFamily: "Magistral", modelCategory: "reasoning",
    ownershipType: "first_party", availabilityStage: "ga",
    commercialAvailability: "api_available",
    sourceIds: ["src_mistral_models"],
    sourceUrls: ["https://docs.mistral.ai/models/overview"],
    sourceNames: ["Mistral AI, Models overview"],
  }),
  model({
    id: "model_mistral_codestral",
    vendorId: "mistral", vendorName: "Mistral AI",
    ownerVendorId: "mistral", ownerVendorName: "Mistral AI",
    modelName: "Codestral", modelFamily: "Codestral", modelCategory: "coding",
    ownershipType: "first_party", availabilityStage: "ga",
    commercialAvailability: "api_available",
    sourceIds: ["src_mistral_models"],
    sourceUrls: ["https://docs.mistral.ai/models/overview"],
    sourceNames: ["Mistral AI, Models overview"],
  }),
  model({
    id: "model_mistral_voxtral",
    vendorId: "mistral", vendorName: "Mistral AI",
    ownerVendorId: "mistral", ownerVendorName: "Mistral AI",
    modelName: "Voxtral", modelFamily: "Voxtral", modelCategory: "speech_audio",
    ownershipType: "first_party", availabilityStage: "ga",
    commercialAvailability: "api_available",
    sourceIds: ["src_mistral_models"],
    sourceUrls: ["https://docs.mistral.ai/models/overview"],
    sourceNames: ["Mistral AI, Models overview"],
  }),
  model({
    id: "model_mistral_ocr",
    vendorId: "mistral", vendorName: "Mistral AI",
    ownerVendorId: "mistral", ownerVendorName: "Mistral AI",
    modelName: "Mistral OCR", modelFamily: "Mistral OCR", modelCategory: "ocr_document_ai",
    ownershipType: "first_party", availabilityStage: "ga",
    commercialAvailability: "api_available",
    sourceIds: ["src_mistral_models"],
    sourceUrls: ["https://docs.mistral.ai/models/overview"],
    sourceNames: ["Mistral AI, Models overview"],
  }),

  // ───────────── Cohere (first-party) ─────────────
  // Refreshed: Command R+ emphasis is stale. Current source-backed
  // catalog leads with Command A and the Command A specialist variants.
  model({
    id: "model_cohere_command_a",
    vendorId: "cohere", vendorName: "Cohere",
    ownerVendorId: "cohere", ownerVendorName: "Cohere",
    modelName: "Command A", modelFamily: "Command", modelCategory: "llm_text",
    ownershipType: "first_party", availabilityStage: "ga",
    commercialAvailability: "api_available",
    sourceIds: ["src_cohere_models"],
    sourceUrls: ["https://docs.cohere.com/docs/models"],
    sourceNames: ["Cohere, Models documentation"],
  }),
  model({
    id: "model_cohere_command_a_reasoning",
    vendorId: "cohere", vendorName: "Cohere",
    ownerVendorId: "cohere", ownerVendorName: "Cohere",
    modelName: "Command A Reasoning", modelFamily: "Command", modelCategory: "reasoning",
    ownershipType: "first_party", availabilityStage: "ga",
    commercialAvailability: "api_available",
    sourceIds: ["src_cohere_models"],
    sourceUrls: ["https://docs.cohere.com/docs/models"],
    sourceNames: ["Cohere, Models documentation"],
  }),
  model({
    id: "model_cohere_command_a_vision",
    vendorId: "cohere", vendorName: "Cohere",
    ownerVendorId: "cohere", ownerVendorName: "Cohere",
    modelName: "Command A Vision", modelFamily: "Command", modelCategory: "multimodal",
    ownershipType: "first_party", availabilityStage: "ga",
    commercialAvailability: "api_available",
    sourceIds: ["src_cohere_models"],
    sourceUrls: ["https://docs.cohere.com/docs/models"],
    sourceNames: ["Cohere, Models documentation"],
  }),
  model({
    id: "model_cohere_command_a_translate",
    vendorId: "cohere", vendorName: "Cohere",
    ownerVendorId: "cohere", ownerVendorName: "Cohere",
    modelName: "Command A Translate", modelFamily: "Command", modelCategory: "domain_specific",
    ownershipType: "first_party", availabilityStage: "ga",
    commercialAvailability: "api_available",
    sourceIds: ["src_cohere_models"],
    sourceUrls: ["https://docs.cohere.com/docs/models"],
    sourceNames: ["Cohere, Models documentation"],
  }),
  model({
    id: "model_cohere_command_r7b",
    vendorId: "cohere", vendorName: "Cohere",
    ownerVendorId: "cohere", ownerVendorName: "Cohere",
    modelName: "Command R7B", modelFamily: "Command", modelCategory: "llm_text",
    ownershipType: "first_party", availabilityStage: "ga",
    commercialAvailability: "api_available",
    sourceIds: ["src_cohere_models"],
    sourceUrls: ["https://docs.cohere.com/docs/models"],
    sourceNames: ["Cohere, Models documentation"],
  }),
  model({
    id: "model_cohere_embed",
    vendorId: "cohere", vendorName: "Cohere",
    ownerVendorId: "cohere", ownerVendorName: "Cohere",
    modelName: "Embed", modelFamily: "Embed", modelCategory: "embedding",
    ownershipType: "first_party", availabilityStage: "ga",
    commercialAvailability: "api_available",
    sourceIds: ["src_cohere_models"],
    sourceUrls: ["https://docs.cohere.com/docs/models"],
    sourceNames: ["Cohere, Models documentation"],
  }),
  model({
    id: "model_cohere_rerank",
    vendorId: "cohere", vendorName: "Cohere",
    ownerVendorId: "cohere", ownerVendorName: "Cohere",
    modelName: "Rerank", modelFamily: "Rerank", modelCategory: "reranking",
    ownershipType: "first_party", availabilityStage: "ga",
    commercialAvailability: "api_available",
    sourceIds: ["src_cohere_models"],
    sourceUrls: ["https://docs.cohere.com/docs/models"],
    sourceNames: ["Cohere, Models documentation"],
  }),
  model({
    id: "model_cohere_transcribe",
    vendorId: "cohere", vendorName: "Cohere",
    ownerVendorId: "cohere", ownerVendorName: "Cohere",
    modelName: "Transcribe", modelFamily: "Transcribe", modelCategory: "speech_audio",
    ownershipType: "first_party", availabilityStage: "ga",
    commercialAvailability: "api_available",
    sourceIds: ["src_cohere_models"],
    sourceUrls: ["https://docs.cohere.com/docs/models"],
    sourceNames: ["Cohere, Models documentation"],
  }),
  model({
    id: "model_cohere_aya",
    vendorId: "cohere", vendorName: "Cohere",
    ownerVendorId: "cohere", ownerVendorName: "Cohere",
    modelName: "Aya", modelFamily: "Aya", modelCategory: "llm_text",
    ownershipType: "open_weight", availabilityStage: "ga",
    commercialAvailability: "api_available",
    sourceIds: ["src_cohere_models"],
    sourceUrls: ["https://docs.cohere.com/docs/models"],
    sourceNames: ["Cohere, Models documentation"],
    uncertaintyNote: "Multilingual research/open-weight family.",
  }),

  // ───────────── xAI (first-party) ─────────────
  // Refreshed: vague "Grok" entry replaced with current source-backed
  // model name. Voice/Imagine APIs added with explicit category.
  model({
    id: "model_xai_grok_43",
    vendorId: "xai", vendorName: "xAI",
    ownerVendorId: "xai", ownerVendorName: "xAI",
    modelName: "Grok 4.3", modelFamily: "Grok", modelCategory: "multimodal",
    ownershipType: "first_party", availabilityStage: "ga",
    commercialAvailability: "api_available",
    sourceIds: ["src_xai_models"],
    sourceUrls: ["https://docs.x.ai/developers/models"],
    sourceNames: ["xAI, Models documentation"],
  }),
  model({
    id: "model_xai_voice",
    vendorId: "xai", vendorName: "xAI",
    ownerVendorId: "xai", ownerVendorName: "xAI",
    modelName: "Grok Voice API", modelFamily: "Grok Voice", modelCategory: "speech_audio",
    ownershipType: "first_party", availabilityStage: "ga",
    commercialAvailability: "api_available",
    sourceIds: ["src_xai_models"],
    sourceUrls: ["https://docs.x.ai/developers/models"],
    sourceNames: ["xAI, Models documentation"],
  }),
  model({
    id: "model_xai_imagine",
    vendorId: "xai", vendorName: "xAI",
    ownerVendorId: "xai", ownerVendorName: "xAI",
    modelName: "Imagine API", modelFamily: "Imagine", modelCategory: "image_generation",
    ownershipType: "first_party", availabilityStage: "ga",
    commercialAvailability: "api_available",
    sourceIds: ["src_xai_models"],
    sourceUrls: ["https://docs.x.ai/developers/models"],
    sourceNames: ["xAI, Models documentation"],
  }),

  // ───────────── AWS (first-party Nova/Titan + hosted third-party) ─────────────
  model({
    id: "model_amzn_nova",
    vendorId: "amzn", vendorName: "Amazon",
    ownerVendorId: "amzn", ownerVendorName: "Amazon",
    modelName: "Amazon Nova", modelFamily: "Nova", modelCategory: "multimodal",
    ownershipType: "first_party", availabilityStage: "ga",
    commercialAvailability: "api_available",
    sourceIds: ["src_aws_bedrock_models"],
    sourceUrls: ["https://docs.aws.amazon.com/bedrock/latest/userguide/models-supported.html"],
    sourceNames: ["AWS, Bedrock supported foundation models"],
  }),
  model({
    id: "model_amzn_titan_text_embeddings",
    vendorId: "amzn", vendorName: "Amazon",
    ownerVendorId: "amzn", ownerVendorName: "Amazon",
    modelName: "Titan Text Embeddings", modelFamily: "Titan", modelCategory: "embedding",
    ownershipType: "first_party", availabilityStage: "ga",
    commercialAvailability: "api_available",
    sourceIds: ["src_aws_bedrock_models"],
    sourceUrls: ["https://docs.aws.amazon.com/bedrock/latest/userguide/titan-models.html"],
    sourceNames: ["AWS, Titan model docs"],
  }),
  model({
    id: "model_amzn_titan_multimodal_embeddings",
    vendorId: "amzn", vendorName: "Amazon",
    ownerVendorId: "amzn", ownerVendorName: "Amazon",
    modelName: "Titan Multimodal Embeddings", modelFamily: "Titan", modelCategory: "embedding",
    ownershipType: "first_party", availabilityStage: "ga",
    commercialAvailability: "api_available",
    sourceIds: ["src_aws_bedrock_models"],
    sourceUrls: ["https://docs.aws.amazon.com/bedrock/latest/userguide/titan-models.html"],
    sourceNames: ["AWS, Titan model docs"],
  }),
  model({
    id: "model_amzn_titan_image_generator",
    vendorId: "amzn", vendorName: "Amazon",
    ownerVendorId: "amzn", ownerVendorName: "Amazon",
    modelName: "Titan Image Generator", modelFamily: "Titan", modelCategory: "image_generation",
    ownershipType: "first_party", availabilityStage: "ga",
    commercialAvailability: "api_available",
    sourceIds: ["src_aws_bedrock_models"],
    sourceUrls: ["https://docs.aws.amazon.com/bedrock/latest/userguide/titan-models.html"],
    sourceNames: ["AWS, Titan model docs"],
  }),
  // Hosted third-party on Bedrock, owner stays original
  model({
    id: "model_bedrock_anthropic_claude",
    vendorId: "amzn", vendorName: "Amazon",
    ownerVendorId: "anthropic", ownerVendorName: "Anthropic",
    modelName: "Claude (hosted on Bedrock)", modelFamily: "Claude", modelCategory: "multimodal",
    ownershipType: "hosted_third_party", availabilityStage: "ga",
    commercialAvailability: "hosted_on_marketplace",
    sourceIds: ["src_aws_bedrock_models"],
    sourceUrls: ["https://docs.aws.amazon.com/bedrock/latest/userguide/models-supported.html"],
    sourceNames: ["AWS, Bedrock supported foundation models"],
  }),
  model({
    id: "model_bedrock_meta_llama",
    vendorId: "amzn", vendorName: "Amazon",
    ownerVendorId: "meta", ownerVendorName: "Meta",
    modelName: "Llama (hosted on Bedrock)", modelFamily: "Llama", modelCategory: "llm_text",
    ownershipType: "hosted_third_party", availabilityStage: "ga",
    commercialAvailability: "hosted_on_marketplace",
    sourceIds: ["src_aws_bedrock_models"],
    sourceUrls: ["https://docs.aws.amazon.com/bedrock/latest/userguide/models-supported.html"],
    sourceNames: ["AWS, Bedrock supported foundation models"],
  }),
  model({
    id: "model_bedrock_mistral",
    vendorId: "amzn", vendorName: "Amazon",
    ownerVendorId: "mistral", ownerVendorName: "Mistral AI",
    modelName: "Mistral (hosted on Bedrock)", modelFamily: "Mistral", modelCategory: "llm_text",
    ownershipType: "hosted_third_party", availabilityStage: "ga",
    commercialAvailability: "hosted_on_marketplace",
    sourceIds: ["src_aws_bedrock_models"],
    sourceUrls: ["https://docs.aws.amazon.com/bedrock/latest/userguide/models-supported.html"],
    sourceNames: ["AWS, Bedrock supported foundation models"],
  }),
  model({
    id: "model_bedrock_cohere",
    vendorId: "amzn", vendorName: "Amazon",
    ownerVendorId: "cohere", ownerVendorName: "Cohere",
    modelName: "Cohere Command (hosted on Bedrock)", modelFamily: "Command", modelCategory: "llm_text",
    ownershipType: "hosted_third_party", availabilityStage: "ga",
    commercialAvailability: "hosted_on_marketplace",
    sourceIds: ["src_aws_bedrock_models"],
    sourceUrls: ["https://docs.aws.amazon.com/bedrock/latest/userguide/models-supported.html"],
    sourceNames: ["AWS, Bedrock supported foundation models"],
  }),

  // ───────────── Microsoft (first-party Phi/MAI/Copilot + hosted third-party) ─────────────
  model({
    id: "model_msft_phi",
    vendorId: "msft", vendorName: "Microsoft",
    ownerVendorId: "msft", ownerVendorName: "Microsoft",
    modelName: "Phi", modelFamily: "Phi", modelCategory: "llm_text",
    ownershipType: "first_party", availabilityStage: "ga",
    commercialAvailability: "api_available",
    sourceIds: ["src_azure_ai_foundry_models"],
    sourceUrls: ["https://learn.microsoft.com/en-us/azure/ai-foundry/foundry-models/overview"],
    sourceNames: ["Azure AI Foundry, Models"],
  }),
  // Microsoft AI Internal models (MAI series), Microsoft's first-party
  // frontier models developed internally, sitting alongside the OpenAI
  // partnership in Foundry.
  model({
    id: "model_msft_mai",
    vendorId: "msft", vendorName: "Microsoft",
    ownerVendorId: "msft", ownerVendorName: "Microsoft",
    modelName: "MAI (Microsoft AI)", modelFamily: "MAI", modelCategory: "multimodal",
    ownershipType: "first_party", availabilityStage: "ga",
    commercialAvailability: "api_available",
    sourceIds: ["src_azure_ai_foundry_models"],
    sourceUrls: ["https://learn.microsoft.com/en-us/azure/ai-foundry/foundry-models/overview"],
    sourceNames: ["Azure AI Foundry, Models"],
  }),
  // Copilot product family, Microsoft's first-party assistant brand,
  // packaged across M365, GitHub, Dynamics, Security, and Sales/Service.
  // Each variant is a first-party Microsoft product even though the
  // underlying LLM is OpenAI GPT served via Azure AI Foundry.
  model({
    id: "model_msft_copilot_m365",
    vendorId: "msft", vendorName: "Microsoft",
    ownerVendorId: "msft", ownerVendorName: "Microsoft",
    modelName: "Microsoft 365 Copilot", modelFamily: "Copilot", modelCategory: "llm_text",
    ownershipType: "underlying_product_model", availabilityStage: "ga",
    commercialAvailability: "underlying_product_model",
    sourceIds: ["src_azure_ai_foundry_models"],
    sourceUrls: ["https://www.microsoft.com/en-us/microsoft-365/copilot"],
    sourceNames: ["Microsoft 365 Copilot, official product page"],
  }),
  model({
    id: "model_msft_copilot_github",
    vendorId: "msft", vendorName: "Microsoft",
    ownerVendorId: "msft", ownerVendorName: "Microsoft",
    modelName: "GitHub Copilot", modelFamily: "Copilot", modelCategory: "coding",
    ownershipType: "underlying_product_model", availabilityStage: "ga",
    commercialAvailability: "underlying_product_model",
    sourceIds: ["src_azure_ai_foundry_models"],
    sourceUrls: ["https://github.com/features/copilot"],
    sourceNames: ["GitHub Copilot, official product page"],
  }),
  model({
    id: "model_msft_copilot_studio",
    vendorId: "msft", vendorName: "Microsoft",
    ownerVendorId: "msft", ownerVendorName: "Microsoft",
    modelName: "Copilot Studio", modelFamily: "Copilot", modelCategory: "llm_text",
    ownershipType: "underlying_product_model", availabilityStage: "ga",
    commercialAvailability: "underlying_product_model",
    sourceIds: ["src_azure_ai_foundry_models"],
    sourceUrls: ["https://www.microsoft.com/en-us/microsoft-copilot/microsoft-copilot-studio"],
    sourceNames: ["Microsoft Copilot Studio, official product page"],
  }),
  model({
    id: "model_msft_copilot_dynamics",
    vendorId: "msft", vendorName: "Microsoft",
    ownerVendorId: "msft", ownerVendorName: "Microsoft",
    modelName: "Dynamics 365 Copilot", modelFamily: "Copilot", modelCategory: "llm_text",
    ownershipType: "underlying_product_model", availabilityStage: "ga",
    commercialAvailability: "underlying_product_model",
    sourceIds: ["src_azure_ai_foundry_models"],
    sourceUrls: ["https://www.microsoft.com/en-us/dynamics-365/solutions/ai"],
    sourceNames: ["Dynamics 365 Copilot, official product page"],
  }),
  model({
    id: "model_msft_copilot_security",
    vendorId: "msft", vendorName: "Microsoft",
    ownerVendorId: "msft", ownerVendorName: "Microsoft",
    modelName: "Microsoft Security Copilot", modelFamily: "Copilot", modelCategory: "llm_text",
    ownershipType: "underlying_product_model", availabilityStage: "ga",
    commercialAvailability: "underlying_product_model",
    sourceIds: ["src_azure_ai_foundry_models"],
    sourceUrls: ["https://www.microsoft.com/en-us/security/business/ai-machine-learning/microsoft-security-copilot"],
    sourceNames: ["Microsoft Security Copilot, official product page"],
  }),
  // Hosted on Azure AI Foundry, owner stays original
  model({
    id: "model_azure_openai_gpt",
    vendorId: "msft", vendorName: "Microsoft",
    ownerVendorId: "openai", ownerVendorName: "OpenAI",
    modelName: "OpenAI GPT (Azure AI Foundry)", modelFamily: "GPT", modelCategory: "multimodal",
    ownershipType: "hosted_third_party", availabilityStage: "ga",
    commercialAvailability: "hosted_on_marketplace",
    sourceIds: ["src_azure_ai_foundry_models", "src_azure_ai_foundry_partners"],
    sourceUrls: ["https://learn.microsoft.com/en-us/azure/ai-foundry/foundry-models/overview", "https://learn.microsoft.com/en-us/azure/ai-foundry/foundry-models/concepts/models-from-partners"],
    sourceNames: ["Azure AI Foundry, Models", "Azure AI Foundry, Models from partners"],
  }),
  model({
    id: "model_azure_anthropic_claude",
    vendorId: "msft", vendorName: "Microsoft",
    ownerVendorId: "anthropic", ownerVendorName: "Anthropic",
    modelName: "Claude (Azure AI Foundry)", modelFamily: "Claude", modelCategory: "multimodal",
    ownershipType: "hosted_third_party", availabilityStage: "ga",
    commercialAvailability: "hosted_on_marketplace",
    sourceIds: ["src_azure_ai_foundry_partners"],
    sourceUrls: ["https://learn.microsoft.com/en-us/azure/ai-foundry/foundry-models/concepts/models-from-partners"],
    sourceNames: ["Azure AI Foundry, Models from partners"],
  }),
  model({
    id: "model_azure_mistral",
    vendorId: "msft", vendorName: "Microsoft",
    ownerVendorId: "mistral", ownerVendorName: "Mistral AI",
    modelName: "Mistral (Azure AI Foundry)", modelFamily: "Mistral", modelCategory: "llm_text",
    ownershipType: "hosted_third_party", availabilityStage: "ga",
    commercialAvailability: "hosted_on_marketplace",
    sourceIds: ["src_azure_ai_foundry_partners"],
    sourceUrls: ["https://learn.microsoft.com/en-us/azure/ai-foundry/foundry-models/concepts/models-from-partners"],
    sourceNames: ["Azure AI Foundry, Models from partners"],
  }),

  // ───────────── IBM (Granite first-party) ─────────────
  model({
    id: "model_ibm_granite",
    vendorId: "ibm", vendorName: "IBM",
    ownerVendorId: "ibm", ownerVendorName: "IBM",
    modelName: "Granite", modelFamily: "Granite", modelCategory: "llm_text",
    ownershipType: "first_party", availabilityStage: "ga",
    commercialAvailability: "api_available",
    sourceIds: ["src_ibm_watsonx_foundation_models"],
    sourceUrls: ["https://www.ibm.com/products/watsonx-ai/foundation-models"],
    sourceNames: ["IBM, watsonx.ai foundation models"],
  }),
  model({
    id: "model_ibm_granite_code",
    vendorId: "ibm", vendorName: "IBM",
    ownerVendorId: "ibm", ownerVendorName: "IBM",
    modelName: "Granite Code", modelFamily: "Granite", modelCategory: "coding",
    ownershipType: "first_party", availabilityStage: "ga",
    commercialAvailability: "api_available",
    sourceIds: ["src_ibm_watsonx_foundation_models"],
    sourceUrls: ["https://www.ibm.com/products/watsonx-ai/foundation-models"],
    sourceNames: ["IBM, watsonx.ai foundation models"],
  }),
  model({
    id: "model_ibm_granite_guardian",
    vendorId: "ibm", vendorName: "IBM",
    ownerVendorId: "ibm", ownerVendorName: "IBM",
    modelName: "Granite Guardian", modelFamily: "Granite", modelCategory: "guardrail_safety",
    ownershipType: "first_party", availabilityStage: "ga",
    commercialAvailability: "api_available",
    sourceIds: ["src_ibm_watsonx_foundation_models"],
    sourceUrls: ["https://www.ibm.com/products/watsonx-ai/foundation-models"],
    sourceNames: ["IBM, watsonx.ai foundation models"],
  }),

  // ───────────── Oracle (host only, third-party) ─────────────
  model({
    id: "model_oci_cohere",
    vendorId: "orcl", vendorName: "Oracle",
    ownerVendorId: "cohere", ownerVendorName: "Cohere",
    modelName: "Cohere (hosted on OCI)", modelFamily: "Command", modelCategory: "llm_text",
    ownershipType: "hosted_third_party", availabilityStage: "ga",
    commercialAvailability: "hosted_on_marketplace",
    sourceIds: ["src_oracle_genai_models"],
    sourceUrls: ["https://docs.oracle.com/en-us/iaas/Content/generative-ai/pretrained-models.htm"],
    sourceNames: ["Oracle, OCI Generative AI pretrained models"],
  }),
  model({
    id: "model_oci_meta",
    vendorId: "orcl", vendorName: "Oracle",
    ownerVendorId: "meta", ownerVendorName: "Meta",
    modelName: "Llama (hosted on OCI)", modelFamily: "Llama", modelCategory: "llm_text",
    ownershipType: "hosted_third_party", availabilityStage: "ga",
    commercialAvailability: "hosted_on_marketplace",
    sourceIds: ["src_oracle_genai_models"],
    sourceUrls: ["https://docs.oracle.com/en-us/iaas/Content/generative-ai/pretrained-models.htm"],
    sourceNames: ["Oracle, OCI Generative AI pretrained models"],
  }),

  // ───────────── Salesforce (orchestration / Default model) ─────────────
  model({
    id: "model_crm_default_orchestration",
    vendorId: "crm", vendorName: "Salesforce",
    ownerVendorId: "crm", ownerVendorName: "Salesforce",
    modelName: "Salesforce Default model (Einstein Trust Layer)", modelFamily: "Agentforce", modelCategory: "domain_specific",
    ownershipType: "underlying_product_model", availabilityStage: "ga",
    commercialAvailability: "underlying_product_model",
    sourceIds: ["src_salesforce_agentforce_models"],
    sourceUrls: ["https://developer.salesforce.com/docs/ai/agentforce/guide/supported-models.html"],
    sourceNames: ["Salesforce, Agentforce supported models"],
    uncertaintyNote: "Salesforce orchestrates external providers; Default model used inside Agentforce is not customer-selectable as a standalone API.",
  }),
  model({
    id: "model_crm_hosted_external",
    vendorId: "crm", vendorName: "Salesforce",
    ownerVendorId: "openai", ownerVendorName: "OpenAI",
    modelName: "Supported provider models (OpenAI, Anthropic, Google)", modelFamily: "Multi-provider", modelCategory: "llm_text",
    ownershipType: "hosted_third_party", availabilityStage: "ga",
    commercialAvailability: "hosted_on_marketplace",
    sourceIds: ["src_salesforce_agentforce_models"],
    sourceUrls: ["https://developer.salesforce.com/docs/ai/agentforce/guide/supported-models.html"],
    sourceNames: ["Salesforce, Agentforce supported models"],
    uncertaintyNote: "Multiple providers supported. Source confirms list; ownership remains with each underlying provider.",
  }),

  // ───────────── ServiceNow (Now LLM domain + hosted) ─────────────
  model({
    id: "model_now_llm",
    vendorId: "now", vendorName: "ServiceNow",
    ownerVendorId: "now", ownerVendorName: "ServiceNow",
    modelName: "Now LLM", modelFamily: "Now LLM", modelCategory: "domain_specific",
    ownershipType: "first_party", availabilityStage: "ga",
    commercialAvailability: "underlying_product_model",
    sourceIds: ["src_now_llm_docs"],
    sourceUrls: ["https://www.servicenow.com/docs/r/intelligent-experiences/servicenow-large-language-model-now-llm/exploring-large-language-models.html"],
    sourceNames: ["ServiceNow, Now LLM exploration"],
    uncertaintyNote: "ServiceNow domain LLM. Not customer-selectable as a general API.",
  }),
  model({
    id: "model_now_llm_service_hosted",
    vendorId: "now", vendorName: "ServiceNow",
    ownerVendorId: "openai", ownerVendorName: "OpenAI",
    modelName: "Third-party LLMs via Now LLM Service", modelFamily: "Multi-provider", modelCategory: "llm_text",
    ownershipType: "hosted_third_party", availabilityStage: "ga",
    commercialAvailability: "hosted_on_marketplace",
    sourceIds: ["src_now_llm_docs"],
    sourceUrls: ["https://www.servicenow.com/docs/r/intelligent-experiences/servicenow-large-language-model-now-llm/exploring-large-language-models.html"],
    sourceNames: ["ServiceNow, Now LLM exploration"],
    uncertaintyNote: "Now LLM Service brokers third-party LLMs; ownership remains with each provider.",
  }),

  // ───────────── Writer (Palmyra first-party) ─────────────
  // Expanded from generic "Palmyra X5" to the full source-backed
  // Palmyra family per dev.writer.com.
  model({
    id: "model_writer_palmyra_x5",
    vendorId: "writer", vendorName: "Writer",
    ownerVendorId: "writer", ownerVendorName: "Writer",
    modelName: "Palmyra X5", modelFamily: "Palmyra", modelCategory: "llm_text",
    ownershipType: "first_party", availabilityStage: "ga",
    commercialAvailability: "api_available",
    sourceIds: ["src_writer_palmyra_models"],
    sourceUrls: ["https://dev.writer.com/home/models"],
    sourceNames: ["Writer, Palmyra models"],
  }),
  model({
    id: "model_writer_palmyra_x4",
    vendorId: "writer", vendorName: "Writer",
    ownerVendorId: "writer", ownerVendorName: "Writer",
    modelName: "Palmyra X4", modelFamily: "Palmyra", modelCategory: "llm_text",
    ownershipType: "first_party", availabilityStage: "ga",
    commercialAvailability: "api_available",
    sourceIds: ["src_writer_palmyra_models"],
    sourceUrls: ["https://dev.writer.com/home/models"],
    sourceNames: ["Writer, Palmyra models"],
  }),
  model({
    id: "model_writer_palmyra_x_003_instruct",
    vendorId: "writer", vendorName: "Writer",
    ownerVendorId: "writer", ownerVendorName: "Writer",
    modelName: "Palmyra X 003 Instruct", modelFamily: "Palmyra", modelCategory: "llm_text",
    ownershipType: "first_party", availabilityStage: "ga",
    commercialAvailability: "api_available",
    sourceIds: ["src_writer_palmyra_models"],
    sourceUrls: ["https://dev.writer.com/home/models"],
    sourceNames: ["Writer, Palmyra models"],
  }),
  model({
    id: "model_writer_palmyra_vision",
    vendorId: "writer", vendorName: "Writer",
    ownerVendorId: "writer", ownerVendorName: "Writer",
    modelName: "Palmyra Vision", modelFamily: "Palmyra", modelCategory: "multimodal",
    ownershipType: "first_party", availabilityStage: "ga",
    commercialAvailability: "api_available",
    sourceIds: ["src_writer_palmyra_models"],
    sourceUrls: ["https://dev.writer.com/home/models"],
    sourceNames: ["Writer, Palmyra models"],
  }),
  model({
    id: "model_writer_palmyra_med",
    vendorId: "writer", vendorName: "Writer",
    ownerVendorId: "writer", ownerVendorName: "Writer",
    modelName: "Palmyra Med", modelFamily: "Palmyra", modelCategory: "domain_specific",
    ownershipType: "first_party", availabilityStage: "ga",
    commercialAvailability: "api_available",
    sourceIds: ["src_writer_palmyra_models"],
    sourceUrls: ["https://dev.writer.com/home/models"],
    sourceNames: ["Writer, Palmyra models"],
    uncertaintyNote: "Healthcare-tuned variant.",
  }),
  model({
    id: "model_writer_palmyra_fin",
    vendorId: "writer", vendorName: "Writer",
    ownerVendorId: "writer", ownerVendorName: "Writer",
    modelName: "Palmyra Fin", modelFamily: "Palmyra", modelCategory: "domain_specific",
    ownershipType: "first_party", availabilityStage: "ga",
    commercialAvailability: "api_available",
    sourceIds: ["src_writer_palmyra_models"],
    sourceUrls: ["https://dev.writer.com/home/models"],
    sourceNames: ["Writer, Palmyra models"],
    uncertaintyNote: "Financial-services-tuned variant.",
  }),
  model({
    id: "model_writer_palmyra_creative",
    vendorId: "writer", vendorName: "Writer",
    ownerVendorId: "writer", ownerVendorName: "Writer",
    modelName: "Palmyra Creative", modelFamily: "Palmyra", modelCategory: "llm_text",
    ownershipType: "first_party", availabilityStage: "ga",
    commercialAvailability: "api_available",
    sourceIds: ["src_writer_palmyra_models"],
    sourceUrls: ["https://dev.writer.com/home/models"],
    sourceNames: ["Writer, Palmyra models"],
  }),

  // ───────────── Glean (orchestration) ─────────────
  model({
    id: "model_glean_hosted",
    vendorId: "glean", vendorName: "Glean",
    ownerVendorId: "openai", ownerVendorName: "OpenAI",
    modelName: "Configured LLMs (OpenAI, Google, Anthropic, AWS, Meta)", modelFamily: "Multi-provider", modelCategory: "llm_text",
    ownershipType: "hosted_third_party", availabilityStage: "ga",
    commercialAvailability: "hosted_on_marketplace",
    sourceIds: ["src_glean_llms"],
    sourceUrls: ["https://docs.glean.com/administration/llms"],
    sourceNames: ["Glean, LLM administration"],
    uncertaintyNote: "Glean is a model hub; supported LLMs remain owned by their original providers.",
  }),

  // ───────────── Harvey (orchestration) ─────────────
  model({
    id: "model_harvey_used",
    vendorId: "harvey", vendorName: "Harvey",
    ownerVendorId: "anthropic", ownerVendorName: "Anthropic",
    modelName: "Models used by Harvey (Anthropic, OpenAI, Google)", modelFamily: "Multi-provider", modelCategory: "llm_text",
    ownershipType: "hosted_third_party", availabilityStage: "ga",
    commercialAvailability: "hosted_on_marketplace",
    sourceIds: ["src_harvey_models"],
    sourceUrls: ["https://help.harvey.ai/articles/what-ai-models-does-harvey-use"],
    sourceNames: ["Harvey, supported AI models"],
    uncertaintyNote: "Harvey is an application/orchestration vendor; models remain owned by their original providers.",
  }),

  // ───────────── Perplexity (Sonar family) ─────────────
  // Refreshed: Sonar is the commercial search-answering API. NOT a
  // general frontier LLM, classified narrowly.
  model({
    id: "model_perplexity_sonar",
    vendorId: "perplexity", vendorName: "Perplexity",
    ownerVendorId: "perplexity", ownerVendorName: "Perplexity",
    modelName: "Sonar", modelFamily: "Sonar", modelCategory: "domain_specific",
    ownershipType: "first_party", availabilityStage: "ga",
    commercialAvailability: "api_available",
    sourceIds: ["src_perplexity_pending"],
    sourceUrls: ["https://docs.perplexity.ai/docs/sonar/models"],
    sourceNames: ["Perplexity, Sonar models"],
    uncertaintyNote: "Sonar is a search-answering API, not a general frontier LLM.",
  }),
  model({
    id: "model_perplexity_sonar_pro",
    vendorId: "perplexity", vendorName: "Perplexity",
    ownerVendorId: "perplexity", ownerVendorName: "Perplexity",
    modelName: "Sonar Pro", modelFamily: "Sonar", modelCategory: "domain_specific",
    ownershipType: "first_party", availabilityStage: "ga",
    commercialAvailability: "api_available",
    sourceIds: ["src_perplexity_pending"],
    sourceUrls: ["https://docs.perplexity.ai/docs/sonar/models"],
    sourceNames: ["Perplexity, Sonar models"],
  }),
  model({
    id: "model_perplexity_sonar_reasoning_pro",
    vendorId: "perplexity", vendorName: "Perplexity",
    ownerVendorId: "perplexity", ownerVendorName: "Perplexity",
    modelName: "Sonar Reasoning Pro", modelFamily: "Sonar", modelCategory: "reasoning",
    ownershipType: "first_party", availabilityStage: "ga",
    commercialAvailability: "api_available",
    sourceIds: ["src_perplexity_pending"],
    sourceUrls: ["https://docs.perplexity.ai/docs/sonar/models"],
    sourceNames: ["Perplexity, Sonar models"],
  }),
  model({
    id: "model_perplexity_sonar_deep_research",
    vendorId: "perplexity", vendorName: "Perplexity",
    ownerVendorId: "perplexity", ownerVendorName: "Perplexity",
    modelName: "Sonar Deep Research", modelFamily: "Sonar", modelCategory: "domain_specific",
    ownershipType: "first_party", availabilityStage: "ga",
    commercialAvailability: "api_available",
    sourceIds: ["src_perplexity_pending"],
    sourceUrls: ["https://docs.perplexity.ai/docs/sonar/models"],
    sourceNames: ["Perplexity, Sonar models"],
  }),

  // ───────────── NVIDIA (refresh required) ─────────────
  model({
    id: "model_nvidia_refresh",
    vendorId: "nvda", vendorName: "Nvidia",
    ownerVendorId: "nvda", ownerVendorName: "Nvidia",
    modelName: "Nemotron / NIM (verification required)", modelFamily: "Nemotron", modelCategory: "unknown",
    ownershipType: "unknown", availabilityStage: "unknown",
    commercialAvailability: "unknown",
    sourceIds: ["src_nvidia_pending"],
    sourceUrls: ["https://developer.nvidia.com/nemotron"],
    sourceNames: ["NVIDIA, Nemotron developer hub"],
    uncertaintyNote: "Nemotron 3 family, Nano / Super / Speech / Safety / RAG variants per developer.nvidia.com.",
  }),
  model({
    id: "model_nvda_nemotron_3_super",
    vendorId: "nvda", vendorName: "NVIDIA",
    ownerVendorId: "nvda", ownerVendorName: "NVIDIA",
    modelName: "Nemotron 3 Super", modelFamily: "Nemotron", modelCategory: "llm_text",
    ownershipType: "first_party", availabilityStage: "ga",
    commercialAvailability: "api_available",
    sourceIds: ["src_nvidia_nemotron"],
    sourceUrls: ["https://developer.nvidia.com/nemotron"],
    sourceNames: ["NVIDIA, Nemotron developer hub"],
  }),
  model({
    id: "model_nvda_nemotron_3_omni",
    vendorId: "nvda", vendorName: "NVIDIA",
    ownerVendorId: "nvda", ownerVendorName: "NVIDIA",
    modelName: "Nemotron 3 Nano Omni", modelFamily: "Nemotron", modelCategory: "multimodal",
    ownershipType: "first_party", availabilityStage: "ga",
    commercialAvailability: "api_available",
    sourceIds: ["src_nvidia_nemotron"],
    sourceUrls: ["https://developer.nvidia.com/nemotron"],
    sourceNames: ["NVIDIA, Nemotron developer hub"],
  }),
  model({
    id: "model_nvda_nemotron_speech",
    vendorId: "nvda", vendorName: "NVIDIA",
    ownerVendorId: "nvda", ownerVendorName: "NVIDIA",
    modelName: "Nemotron Speech", modelFamily: "Nemotron", modelCategory: "speech_audio",
    ownershipType: "first_party", availabilityStage: "ga",
    commercialAvailability: "api_available",
    sourceIds: ["src_nvidia_nemotron"],
    sourceUrls: ["https://developer.nvidia.com/nemotron"],
    sourceNames: ["NVIDIA, Nemotron developer hub"],
  }),

  // ───────────── Meta (first-party Llama owner) ─────────────
  // Per user direction: Meta is added as the original owner. Llama
  // entries hosted on Bedrock/OCI keep their existing hosted_third_party
  // classification with ownerVendorId="meta" (already correct for Bedrock).
  model({
    id: "model_meta_llama_4",
    vendorId: "meta", vendorName: "Meta",
    ownerVendorId: "meta", ownerVendorName: "Meta",
    modelName: "Llama 4", modelFamily: "Llama", modelCategory: "multimodal",
    ownershipType: "first_party", availabilityStage: "ga",
    commercialAvailability: "api_available",
    inputModalities: ["text", "image"], outputModalities: ["text"],
    sourceIds: ["src_meta_llama"],
    sourceUrls: ["https://www.llama.com/docs/overview/"],
    sourceNames: ["Meta, Llama overview"],
  }),
  model({
    id: "model_meta_llama_4_scout",
    vendorId: "meta", vendorName: "Meta",
    ownerVendorId: "meta", ownerVendorName: "Meta",
    modelName: "Llama 4 Scout", modelFamily: "Llama", modelCategory: "llm_text",
    ownershipType: "first_party", availabilityStage: "ga",
    commercialAvailability: "api_available",
    sourceIds: ["src_meta_llama"],
    sourceUrls: ["https://www.llama.com/docs/overview/"],
    sourceNames: ["Meta, Llama overview"],
  }),

  // ───────────── DeepSeek (first-party) ─────────────
  model({
    id: "model_deepseek_v4_pro",
    vendorId: "deepseek", vendorName: "DeepSeek",
    ownerVendorId: "deepseek", ownerVendorName: "DeepSeek",
    modelName: "deepseek-v4-pro", modelFamily: "DeepSeek V4", modelCategory: "reasoning",
    ownershipType: "first_party", availabilityStage: "ga",
    commercialAvailability: "api_available",
    sourceIds: ["src_deepseek_models"],
    sourceUrls: ["https://api-docs.deepseek.com/quick_start/pricing"],
    sourceNames: ["DeepSeek, pricing & model docs"],
  }),
  model({
    id: "model_deepseek_v4_flash",
    vendorId: "deepseek", vendorName: "DeepSeek",
    ownerVendorId: "deepseek", ownerVendorName: "DeepSeek",
    modelName: "deepseek-v4-flash", modelFamily: "DeepSeek V4", modelCategory: "llm_text",
    ownershipType: "first_party", availabilityStage: "ga",
    commercialAvailability: "api_available",
    sourceIds: ["src_deepseek_models"],
    sourceUrls: ["https://api-docs.deepseek.com/quick_start/pricing"],
    sourceNames: ["DeepSeek, pricing & model docs"],
  }),

  // ───────────── Snowflake (first-party Arctic) ─────────────
  // Per user direction: Snowflake moves out of infrastructure-only.
  // Cortex is treated separately as a hosting layer for third-party
  // models, Arctic is the first-party open enterprise LLM family.
  model({
    id: "model_snowflake_arctic",
    vendorId: "snow", vendorName: "Snowflake",
    ownerVendorId: "snow", ownerVendorName: "Snowflake",
    modelName: "Snowflake Arctic", modelFamily: "Arctic", modelCategory: "llm_text",
    ownershipType: "first_party", availabilityStage: "ga",
    commercialAvailability: "api_available",
    sourceIds: ["src_snowflake_arctic"],
    sourceUrls: ["https://www.snowflake.com/en/product/features/arctic/"],
    sourceNames: ["Snowflake, Arctic model family"],
    uncertaintyNote: "Arctic published as open-weight enterprise LLM. Cortex separately hosts third-party models (treated as hosted layer).",
  }),

  // ───────────── Alibaba / Qwen (first-party) ─────────────
  // Global frontier family, Qwen3 + Qwen3.5 series with reasoning,
  // multimodal, and flash size variants per Alibaba Cloud Model Studio.
  model({
    id: "model_alibaba_qwen3_max",
    vendorId: "alibaba", vendorName: "Alibaba",
    ownerVendorId: "alibaba", ownerVendorName: "Alibaba",
    modelName: "Qwen3-Max", modelFamily: "Qwen3", modelCategory: "multimodal",
    ownershipType: "first_party", availabilityStage: "ga",
    commercialAvailability: "api_available",
    sourceIds: ["src_alibaba_qwen"],
    sourceUrls: ["https://www.alibabacloud.com/help/en/model-studio/models"],
    sourceNames: ["Alibaba Cloud, Model Studio"],
  }),
  model({
    id: "model_alibaba_qwen35_plus",
    vendorId: "alibaba", vendorName: "Alibaba",
    ownerVendorId: "alibaba", ownerVendorName: "Alibaba",
    modelName: "Qwen3.5-Plus", modelFamily: "Qwen3.5", modelCategory: "llm_text",
    ownershipType: "first_party", availabilityStage: "ga",
    commercialAvailability: "api_available",
    sourceIds: ["src_alibaba_qwen"],
    sourceUrls: ["https://www.alibabacloud.com/help/en/model-studio/models"],
    sourceNames: ["Alibaba Cloud, Model Studio"],
  }),
  model({
    id: "model_alibaba_qwen35_flash",
    vendorId: "alibaba", vendorName: "Alibaba",
    ownerVendorId: "alibaba", ownerVendorName: "Alibaba",
    modelName: "Qwen3.5-Flash", modelFamily: "Qwen3.5", modelCategory: "llm_text",
    ownershipType: "first_party", availabilityStage: "ga",
    commercialAvailability: "api_available",
    sourceIds: ["src_alibaba_qwen"],
    sourceUrls: ["https://www.alibabacloud.com/help/en/model-studio/models"],
    sourceNames: ["Alibaba Cloud, Model Studio"],
  }),
  model({
    id: "model_alibaba_qwq",
    vendorId: "alibaba", vendorName: "Alibaba",
    ownerVendorId: "alibaba", ownerVendorName: "Alibaba",
    modelName: "QwQ", modelFamily: "QwQ", modelCategory: "reasoning",
    ownershipType: "first_party", availabilityStage: "ga",
    commercialAvailability: "api_available",
    sourceIds: ["src_alibaba_qwen"],
    sourceUrls: ["https://www.alibabacloud.com/help/en/model-studio/models"],
    sourceNames: ["Alibaba Cloud, Model Studio"],
  }),

  // ───────────── Moonshot AI / Kimi (first-party) ─────────────
  model({
    id: "model_moonshot_k26",
    vendorId: "moonshot", vendorName: "Moonshot AI",
    ownerVendorId: "moonshot", ownerVendorName: "Moonshot AI",
    modelName: "Kimi K2.6", modelFamily: "Kimi K2", modelCategory: "llm_text",
    ownershipType: "first_party", availabilityStage: "ga",
    commercialAvailability: "api_available",
    sourceIds: ["src_moonshot_kimi"],
    sourceUrls: ["https://platform.moonshot.ai"],
    sourceNames: ["Moonshot AI, Platform docs"],
  }),
  model({
    id: "model_moonshot_k25",
    vendorId: "moonshot", vendorName: "Moonshot AI",
    ownerVendorId: "moonshot", ownerVendorName: "Moonshot AI",
    modelName: "Kimi K2.5", modelFamily: "Kimi K2", modelCategory: "llm_text",
    ownershipType: "first_party", availabilityStage: "ga",
    commercialAvailability: "api_available",
    sourceIds: ["src_moonshot_kimi"],
    sourceUrls: ["https://platform.moonshot.ai"],
    sourceNames: ["Moonshot AI, Platform docs"],
  }),
  model({
    id: "model_moonshot_k2_thinking",
    vendorId: "moonshot", vendorName: "Moonshot AI",
    ownerVendorId: "moonshot", ownerVendorName: "Moonshot AI",
    modelName: "Kimi K2 Thinking", modelFamily: "Kimi K2", modelCategory: "reasoning",
    ownershipType: "first_party", availabilityStage: "ga",
    commercialAvailability: "api_available",
    sourceIds: ["src_moonshot_kimi"],
    sourceUrls: ["https://platform.moonshot.ai"],
    sourceNames: ["Moonshot AI, Platform docs"],
  }),

  // ───────────── Z.ai / Zhipu (first-party) ─────────────
  model({
    id: "model_zai_glm_51",
    vendorId: "zai", vendorName: "Z.ai",
    ownerVendorId: "zai", ownerVendorName: "Z.ai",
    modelName: "GLM-5.1", modelFamily: "GLM", modelCategory: "multimodal",
    ownershipType: "first_party", availabilityStage: "ga",
    commercialAvailability: "api_available",
    sourceIds: ["src_zai_glm"],
    sourceUrls: ["https://docs.z.ai/guides/llm/glm-5.1"],
    sourceNames: ["Z.ai, GLM model docs"],
  }),

  // ───────────── MiniMax (first-party) ─────────────
  model({
    id: "model_minimax_m27",
    vendorId: "minimax", vendorName: "MiniMax",
    ownerVendorId: "minimax", ownerVendorName: "MiniMax",
    modelName: "MiniMax-M2.7", modelFamily: "MiniMax M2", modelCategory: "multimodal",
    ownershipType: "first_party", availabilityStage: "ga",
    commercialAvailability: "api_available",
    sourceIds: ["src_minimax_models"],
    sourceUrls: ["https://platform.minimax.io/docs/guides/models-intro"],
    sourceNames: ["MiniMax, Platform model docs"],
  }),
  model({
    id: "model_minimax_m25",
    vendorId: "minimax", vendorName: "MiniMax",
    ownerVendorId: "minimax", ownerVendorName: "MiniMax",
    modelName: "MiniMax-M2.5", modelFamily: "MiniMax M2", modelCategory: "llm_text",
    ownershipType: "first_party", availabilityStage: "ga",
    commercialAvailability: "api_available",
    sourceIds: ["src_minimax_models"],
    sourceUrls: ["https://platform.minimax.io/docs/guides/models-intro"],
    sourceNames: ["MiniMax, Platform model docs"],
  }),
  model({
    id: "model_minimax_m2_her",
    vendorId: "minimax", vendorName: "MiniMax",
    ownerVendorId: "minimax", ownerVendorName: "MiniMax",
    modelName: "MiniMax-M2-her", modelFamily: "MiniMax M2", modelCategory: "speech_audio",
    ownershipType: "first_party", availabilityStage: "ga",
    commercialAvailability: "api_available",
    sourceIds: ["src_minimax_models"],
    sourceUrls: ["https://platform.minimax.io/docs/guides/models-intro"],
    sourceNames: ["MiniMax, Platform model docs"],
    uncertaintyNote: "Speech / voice variant.",
  }),

  // ───────────── AI21 Labs (first-party) ─────────────
  model({
    id: "model_ai21_jamba_large",
    vendorId: "ai21", vendorName: "AI21 Labs",
    ownerVendorId: "ai21", ownerVendorName: "AI21 Labs",
    modelName: "Jamba Large", modelFamily: "Jamba", modelCategory: "llm_text",
    ownershipType: "first_party", availabilityStage: "ga",
    commercialAvailability: "api_available",
    sourceIds: ["src_ai21_jamba"],
    sourceUrls: ["https://docs.ai21.com/docs/jamba-foundation-models"],
    sourceNames: ["AI21, Jamba foundation models"],
    uncertaintyNote: "Hybrid Mamba + Transformer architecture, long context.",
  }),
  model({
    id: "model_ai21_jamba_mini",
    vendorId: "ai21", vendorName: "AI21 Labs",
    ownerVendorId: "ai21", ownerVendorName: "AI21 Labs",
    modelName: "Jamba Mini", modelFamily: "Jamba", modelCategory: "llm_text",
    ownershipType: "first_party", availabilityStage: "ga",
    commercialAvailability: "api_available",
    sourceIds: ["src_ai21_jamba"],
    sourceUrls: ["https://docs.ai21.com/docs/jamba-foundation-models"],
    sourceNames: ["AI21, Jamba foundation models"],
  }),

  // ───────────── Aleph Alpha, Pharia (lower-confidence) ─────────────
  model({
    id: "model_aleph_pharia",
    vendorId: "aleph", vendorName: "Aleph Alpha",
    ownerVendorId: "aleph", ownerVendorName: "Aleph Alpha",
    modelName: "Pharia", modelFamily: "Pharia", modelCategory: "llm_text",
    ownershipType: "open_weight", availabilityStage: "ga",
    commercialAvailability: "unknown",
    sourceIds: ["src_aleph_alpha_pharia"],
    sourceUrls: ["https://docs.aleph-alpha.com/phariaai-dev-guide/latest/pharia-llm/model-variants.html"],
    sourceNames: ["Aleph Alpha, Pharia model variants"],
    evidenceGrade: "E1", confidenceScore: 55, dataStatus: "seed",
    uncertaintyNote: "Weight-available release. Commercial API availability unclear from current source set.",
  }),

  // ───────────── Deprecated example (truthfulness gate test) ─────────────
  model({
    id: "model_anthropic_claude2_deprecated",
    vendorId: "anthropic", vendorName: "Anthropic",
    ownerVendorId: "anthropic", ownerVendorName: "Anthropic",
    modelName: "Claude 2", modelFamily: "Claude", modelCategory: "llm_text",
    ownershipType: "first_party", availabilityStage: "deprecated",
    commercialAvailability: "not_commercially_available",
    sourceIds: ["src_anthropic_models_overview"],
    sourceUrls: ["https://docs.anthropic.com/en/docs/about-claude/models/overview"],
    sourceNames: ["Anthropic, Claude Models overview"],
    deprecationDate: "2025-07-21",
  }),
];

/**
 * Vendors in our universe with no first-party commercial LLM and no third-party
 * hosted via their platform. They appear in the dashboard with an
 * "infrastructure-only" or "refresh required" badge, never invented entries.
 */
// `snow` removed, Snowflake now has first-party Arctic.
export const INFRASTRUCTURE_ONLY_VENDOR_IDS = ["amd", "avgo", "asml", "arm", "sap", "databricks", "cerebras", "hebbia", "rogo"];
