// The Decision Pack spec. Pure.
//
// ORIGIN. Ported 6 August 2026 from The Security Desk
// (~/Documents/Dev Projects/the-desk, lib/deck.ts, commit b9bb51c), read-only
// and unmodified at source. Editorial punctuation adapted to the house rule.
//
// ONE SPEC, BOTH OUTPUTS. This builds a structured, cited pack from the
// decision state, and the same object drives the on-screen brief and the
// downloaded file. That is the whole point: a number cannot differ between
// what the reader saw and what they handed to their board, because there is
// only one place either could have read it from. CODE writes it, not a model,
// so nothing in a board pack was generated by something that can invent.
//
// EXPORT FORMAT. The source renders this to .pptx via pptxgenjs, imported on
// click so it never enters the initial bundle. That dependency is NOT added
// here: another session was mid-flight in package.json and package-lock.json
// when this was built, and adding a package to a tree somebody else is editing
// is the one change most likely to collide. The renderer in ./pack-html.ts
// produces a self-contained, print-ready document from the identical spec, so
// swapping in a .pptx renderer later is a new function over the same object
// and changes nothing above it.

import { PILOT_STEPS, pilotProbesFor } from "./pilot";
import { topPriorities, type Ranked, type ShieldWeights } from "./sourcing";
import type { MarkState } from "@/lib/shield/data";
import { SHIELD_VERSION } from "@/lib/shield/data";

export interface CitedLine {
  text: string;
  /** "name · verified date", where a receipt exists. */
  source?: string;
}

export interface PackSection {
  kind:
    | "cover"
    | "recommendation"
    | "shortlist"
    | "rejected"
    | "scope"
    | "pilot"
    | "authority";
  eyebrow: string;
  title: string;
  subtitle?: string;
  lines?: CitedLine[];
  table?: { headers: string[]; rows: string[][] };
}

export interface PackSpec {
  fileTitle: string;
  useCase: string;
  dateLabel: string;
  sections: PackSection[];
  sources: { name: string; url: string }[];
}

const MARK_WORD: Record<MarkState, string> = {
  protective: "protective",
  conditional: "conditional",
  adverse: "adverse",
  unverified: "not verified",
};

export function buildPack(
  useCases: string[],
  weights: ShieldWeights,
  ranked: Ranked[],
  dateLabel: string
): PackSpec {
  const useCase = useCases.length
    ? useCases.join(" + ")
    : "An enterprise AI sourcing decision";
  const passing = ranked.filter((r) => r.passes);
  const rejected = ranked.filter((r) => !r.passes);
  const winner = passing[0] ?? null;

  const sections: PackSection[] = [];

  sections.push({
    kind: "cover",
    eyebrow: "AI SOURCING DECISION · PREPARED FOR THE BOARD",
    title: useCase,
    subtitle: dateLabel,
  });

  if (winner) {
    const m = winner.vendor.marks;
    const raised = topPriorities(weights);
    sections.push({
      kind: "recommendation",
      eyebrow: "THE RECOMMENDATION",
      title: winner.vendor.vendor,
      subtitle: `Weighted data-protection score ${winner.weightedScore} of ${winner.maxScore}, ${raised ? `with ${raised} weighted above the rest` : "with all four questions weighted equally"}.`,
      lines: [
        {
          text: `Will not train on our data: ${MARK_WORD[m.training.state]}.`,
          source: m.training.source?.name,
        },
        {
          text: `Retention and zero-retention: ${MARK_WORD[m.retention.state]}.`,
          source: m.retention.source?.name,
        },
        {
          text: `Output IP indemnity: ${MARK_WORD[m.indemnity.state]}.`,
          source: m.indemnity.source?.name,
        },
        {
          text: `Data residency: ${MARK_WORD[m.residency.state]}.`,
          source: m.residency.source?.name,
        },
      ],
    });
  } else {
    sections.push({
      kind: "recommendation",
      eyebrow: "THE RECOMMENDATION",
      title: "No vendor clears your constraints",
      subtitle:
        "Every candidate was filtered out by the requirements you set. Relax a constraint, or accept a conditional grade and say so explicitly.",
    });
  }

  sections.push({
    kind: "shortlist",
    eyebrow: "THE SHORTLIST · RANKED ON VERIFIED DATA-PROTECTION POSTURE",
    title: "How they compare",
    table: {
      headers: [
        "Vendor",
        "No-train",
        "Retention",
        "Indemnity",
        "Residency",
        "Score",
      ],
      rows: passing.map((r) => [
        r.vendor.vendor,
        MARK_WORD[r.vendor.marks.training.state],
        MARK_WORD[r.vendor.marks.retention.state],
        MARK_WORD[r.vendor.marks.indemnity.state],
        MARK_WORD[r.vendor.marks.residency.state],
        `${r.weightedScore}/${r.maxScore}`,
      ]),
    },
  });

  if (rejected.length > 0) {
    sections.push({
      kind: "rejected",
      eyebrow: "WHY NOT THE OTHERS",
      title: "Ruled out, and exactly why",
      lines: rejected.map((r) => ({
        text: `${r.vendor.vendor}: ${r.failReason ?? "did not meet a stated requirement"}.`,
      })),
    });
  }

  // The honesty section. A pack that does not state its own limits will have
  // them stated for it, in the meeting, by someone less friendly.
  sections.push({
    kind: "scope",
    eyebrow: "WHAT THIS DECISION DOES AND DOES NOT COVER",
    title: "Read this before you present it",
    lines: [
      {
        text: `This ranks vendors on verified data-protection and IP posture, weighted to our priorities. It does not rank them on capability for ${useCase.toLowerCase()}.`,
      },
      {
        text: "Capability fit has to be proven on our own data, because public benchmarks mislead for specific workflows. Run a scoped pilot before signing.",
      },
      {
        text: `Grades marked "not verified" are gaps in our evidence, not verdicts against the vendor.`,
      },
      {
        text: `Every grade was read from the vendor's own published document on the stated date. Shield version ${SHIELD_VERSION}.`,
      },
    ],
  });

  const probes = pilotProbesFor(useCases);
  sections.push({
    kind: "pilot",
    eyebrow: "PROVE THE CAPABILITY · THE PILOT THE SCORE CANNOT RUN FOR YOU",
    title: "Run this bake-off before you sign",
    lines: [
      ...PILOT_STEPS.map((s, i) => ({ text: `${i + 1}. ${s.title}` })),
      ...probes.map((p) => ({
        text: `Add your own failure modes to the eval set. ${p.useCase}: ${p.probe}`,
      })),
    ],
  });

  sections.push({
    kind: "authority",
    eyebrow: "METHOD AND INDEPENDENCE",
    title: "Why you can defend these numbers",
    lines: [
      {
        text: "No vendor money. AnalystGenius takes no payment from any vendor it rates, and independence is the product.",
      },
      {
        text: "Cited or silent. Every grade traces to the vendor's own published document, dated. Unverified stays blank rather than guessed.",
      },
      {
        text: "Code writes the numbers. Scores come from a fixed, re-weightable rubric, and no model invents a figure.",
      },
      {
        text: "Prepared by AnalystGenius.",
      },
    ],
  });

  // Every receipt behind every mark shown, deduplicated.
  const srcMap = new Map<string, string>();
  for (const r of ranked) {
    for (const key of [
      "training",
      "retention",
      "indemnity",
      "residency",
    ] as const) {
      const s = r.vendor.marks[key].source;
      if (s) srcMap.set(s.name, s.url);
    }
  }

  return {
    fileTitle: `AI Sourcing Decision: ${useCase}`,
    useCase,
    dateLabel,
    sections,
    sources: [...srcMap.entries()].map(([name, url]) => ({ name, url })),
  };
}
