// Ported from ranking-engine repo: lib/intelligence/seed-news.ts
// Origin snapshot: _archive/ranking-engine-stray-copy-2026-07-08, copied 30 July 2026.

// Mock news intelligence (v0.2). Each item is structured for downstream
// classification + scoring impact. Real ingestion will replace these.

import type { NewsItem, NewsCategory } from "./types";
import type { PillarId } from "../types";

const make = (
  id: string, daysAgo: number, title: string, summary: string,
  whyItMatters: string,
  vendors: string[], categories: NewsCategory[], affectedPillars: PillarId[],
  impactScore: number, confidenceScore: number,
  sentiment: NewsItem["sentiment"], source: string, sourceUrl?: string,
  related: string[] = [],
): NewsItem => ({
  id, title, summary, whyItMatters,
  // Source URLs intentionally stripped from seed data — these news items are
  // illustrative MOCKS, not real published articles. Live ingestion (admin →
  // ingestion) populates real source URLs after analyst review.
  sourceName: `[MOCK] ${source}`,
  sourceUrl: undefined,
  publishedAt: new Date(Date.parse("2026-05-04") - daysAgo * 86_400_000).toISOString(),
  vendors, relatedVendors: related,
  categories, affectedPillars,
  impactScore, confidenceScore, sentiment,
  suggestedScoreImpact: vendors.map(() => ({
    pillar: affectedPillars[0] ?? "market_strength",
    direction: sentiment === "positive" ? "up" : sentiment === "negative" ? "down" : "watch",
    magnitude: Math.round(impactScore / 10),
    rationale: whyItMatters,
  })),
});

export const NEWS_ITEMS: NewsItem[] = [
  make("news_1", 1,
    "Microsoft launches Copilot Tuning for regulated workloads",
    "Microsoft introduced Copilot Tuning that allows enterprises to fine-tune Copilot inside their tenant boundary using their own permissioned data, with extended audit logs and Sovereign Cloud support.",
    "Sharpens Microsoft's enterprise-control narrative for regulated buyers — narrows the practical gap with vertical AI providers in legal and financial workflows.",
    ["vendor_microsoft"], ["Product launch", "Enterprise control"],
    ["enterprise_control", "business_fit"], 78, 84, "positive",
    "Microsoft AI Blog", "https://blogs.microsoft.com",
    ["vendor_openai", "vendor_anthropic"]),

  make("news_2", 2,
    "Anthropic ships Claude 4.7 with computer-use general availability",
    "Anthropic moved Claude's computer-use capability out of beta to GA, alongside Claude 4.7 reasoning improvements. Bedrock and Vertex availability is same-day.",
    "Cements Anthropic's agentic leadership and reduces buyers' rationale for waiting on agentic procurement.",
    ["vendor_anthropic"], ["Product launch", "Agentic AI"],
    ["reliability_safety", "integration_ops"], 86, 82, "positive",
    "Anthropic", "https://www.anthropic.com/news",
    ["vendor_aws", "vendor_google"]),

  make("news_3", 3,
    "Salesforce shifts Agentforce pricing to per-conversation",
    "Salesforce announced a per-conversation consumption model for Agentforce, replacing the prior per-seat pricing for new customers.",
    "Restructures the commercial bet: deflection economics now matter more than seat count. Procurement complexity rises.",
    ["vendor_salesforce"], ["Pricing", "Strategy signal"],
    ["integration_ops"], 72, 80, "mixed",
    "Salesforce Investor Update", "https://investor.salesforce.com"),

  make("news_4", 4,
    "EU AI Office issues guidance on general-purpose AI obligations",
    "Final guidance clarifies obligations for general-purpose AI providers under the EU AI Act, including documentation, copyright disclosures and systemic-risk thresholds.",
    "Increases compliance costs across frontier model providers; rewards vendors with mature governance products (Microsoft, IBM, SAP).",
    ["vendor_openai", "vendor_anthropic", "vendor_google", "vendor_mistral", "vendor_microsoft", "vendor_ibm", "vendor_sap"],
    ["Regulation"],
    ["enterprise_control"], 82, 88, "neutral",
    "EU AI Office", "https://digital-strategy.ec.europa.eu",
    ["vendor_aws"]),

  make("news_5", 5,
    "ServiceNow + Moveworks integration shipping in Q3",
    "ServiceNow confirmed deeper integration of Moveworks conversational front-end into Now Assist; combined product GA scheduled for Q3.",
    "Strengthens the ITSM/HR conversational moat — and reduces standalone Moveworks differentiation.",
    ["vendor_servicenow", "vendor_moveworks"], ["Strategy signal", "Partnership"],
    ["business_fit", "market_strength"], 68, 78, "positive",
    "ServiceNow newsroom", "https://www.servicenow.com/company/media.html"),

  make("news_6", 6,
    "OpenAI raises rates on heavy-reasoning workloads",
    "OpenAI announced a 25 percent increase on extended-thinking and tool-use heavy workloads on GPT-5 family models effective next month.",
    "Reinforces FinOps discipline as a procurement criterion; widens Anthropic's commercial wedge in cost-sensitive workloads.",
    ["vendor_openai"], ["Pricing"],
    ["integration_ops"], 70, 80, "negative",
    "OpenAI", "https://openai.com/pricing",
    ["vendor_anthropic", "vendor_microsoft"]),

  make("news_7", 7,
    "Harvey raises Series E at $5B valuation",
    "Harvey closed a Series E led by a top-tier growth fund at a $5B valuation, citing 60% YoY ARR growth in legal vertical.",
    "Locks in Harvey's lead in legal AI and increases capital pressure on vertical entrants like Robin AI and Spellbook.",
    ["vendor_harvey"], ["Market movement"],
    ["vendor_resilience", "market_strength"], 74, 84, "positive",
    "Bloomberg", "https://www.bloomberg.com",
    ["vendor_anthropic", "vendor_openai"]),

  make("news_8", 8,
    "AWS Bedrock adds inline model evaluations",
    "Bedrock now lets enterprise teams run inline evaluation on candidate model deployments using customer-curated test sets, including bias and PII checks.",
    "Removes a key adoption objection in regulated workloads and puts pressure on Azure AI Foundry's evaluation story.",
    ["vendor_aws"], ["Enterprise control", "Product launch"],
    ["enterprise_control", "reliability_safety"], 70, 80, "positive",
    "AWS news", "https://aws.amazon.com/blogs",
    ["vendor_microsoft", "vendor_anthropic"]),

  make("news_9", 9,
    "Mistral wins French government sovereign-cloud AI tender",
    "Mistral selected as primary AI provider for a €450M French government sovereign-cloud framework over a 4-year horizon.",
    "Validates the EU sovereign-AI thesis and strengthens Mistral's commercial story for public-sector buyers.",
    ["vendor_mistral"], ["Market movement", "Partnership"],
    ["market_strength", "vendor_resilience"], 80, 86, "positive",
    "Le Monde", "https://www.lemonde.fr"),

  make("news_10", 10,
    "Hebbia launches deal-room agents for buy-side analysts",
    "Hebbia announced Matrix Deal Rooms with agentic workflows for buy-side analyst use cases including comps, model checks, and DD prep.",
    "Sharpens Hebbia's wedge against Rogo and bespoke bank-built copilots; adoption signal worth tracking.",
    ["vendor_hebbia"], ["Product launch"],
    ["business_fit"], 64, 76, "positive",
    "Hebbia", "https://www.hebbia.com",
    ["vendor_rogo"]),

  make("news_11", 11,
    "Cohere reports SOC 2 Type II + ISO 42001",
    "Cohere announced completion of SOC 2 Type II and ISO 42001 audits, with reports available under NDA.",
    "Strengthens Cohere's enterprise-control story and supports on-prem / sovereign deployments in regulated estates.",
    ["vendor_cohere"], ["Enterprise control"],
    ["enterprise_control"], 60, 84, "positive",
    "Cohere", "https://cohere.com"),

  make("news_12", 12,
    "Glean adds enterprise-wide agent audit + replay",
    "Glean shipped agent audit + replay across all permission-aware connectors — every action captured for review by audit + security teams.",
    "Differentiates Glean further on permission semantics + auditability vs hyperscaler assistants.",
    ["vendor_glean"], ["Product launch", "Enterprise control"],
    ["enterprise_control"], 64, 80, "positive",
    "Glean blog", "https://www.glean.com/blog"),

  make("news_13", 13,
    "Salesforce posts strong Agentforce production references at Dreamforce",
    "Salesforce highlighted multi-million-dollar customer-service deflection wins at Dreamforce with named references including a top-3 US bank and a major airline.",
    "Strongest production-evidence event yet for Agentforce; pushes the agent platform conversation past demos.",
    ["vendor_salesforce"], ["Market movement", "Strategy signal"],
    ["market_strength", "business_fit"], 78, 82, "positive",
    "Dreamforce", "https://www.salesforce.com/dreamforce"),

  make("news_14", 14,
    "Risk: data exfiltration via prompt injection in third-party connector",
    "A research disclosure showed prompt-injection-driven data exfiltration was possible through a popular third-party calendar connector across multiple assistant platforms.",
    "Raises connector-supply-chain risk; vendors with permission-inheritance + audit controls (Glean, Microsoft) more defensible.",
    ["vendor_glean", "vendor_microsoft", "vendor_openai", "vendor_google", "vendor_anthropic"],
    ["Risk event", "Enterprise control"],
    ["enterprise_control", "reliability_safety"], 72, 76, "negative",
    "Security research", "https://example.com/security",
    []),

  make("news_15", 15,
    "Databricks acquires AI eval startup Lightyear",
    "Databricks acquired model-evaluation startup Lightyear to bolster Mosaic AI evaluation tooling for regulated buyers.",
    "Closes a known gap and supports Databricks's data-grounded AI narrative.",
    ["vendor_databricks"], ["Partnership", "Strategy signal"],
    ["reliability_safety", "vendor_resilience"], 60, 78, "positive",
    "Databricks newsroom", "https://www.databricks.com/company/newsroom"),

  make("news_16", 16,
    "Google launches Gemini Enterprise Permissioning Layer",
    "Google announced an enterprise permissioning layer that integrates with Workspace + Drive ACLs to provide source-permission inheritance for Gemini Apps.",
    "Closes a long-standing gap with Glean and Microsoft Copilot's permission semantics — but Workspace conversion remains the gating factor.",
    ["vendor_google"], ["Enterprise control", "Product launch"],
    ["enterprise_control"], 70, 78, "positive",
    "Google Cloud Next", "https://cloud.google.com/next",
    ["vendor_glean", "vendor_microsoft"]),

  make("news_17", 17,
    "OpenAI signs $7B compute commitment with new infra partner",
    "OpenAI announced a multi-year compute commitment beyond Azure, partly diversifying inference capacity.",
    "Reduces single-provider concentration but increases capital-intensity exposure in OpenAI's commercial model.",
    ["vendor_openai"], ["Infrastructure", "Strategy signal"],
    ["vendor_resilience"], 78, 76, "mixed",
    "WSJ", "https://www.wsj.com",
    ["vendor_microsoft"]),

  make("news_18", 18,
    "SAP Joule Studio adds multi-step business agents",
    "SAP shipped Joule Studio with multi-step agent flows wired into S/4HANA, SuccessFactors and Ariba.",
    "Lifts SAP's agentic credibility inside the back-office estate; not a frontier agent platform but the system-of-record gravity is real.",
    ["vendor_sap"], ["Product launch", "Agentic AI"],
    ["business_fit", "integration_ops"], 64, 76, "positive",
    "SAP newsroom", "https://news.sap.com"),

  make("news_19", 19,
    "IBM Concert v3 ships with EU AI Act control templates",
    "IBM Concert v3 includes pre-built control templates mapped to EU AI Act articles 9–15 for high-risk AI systems.",
    "Strengthens IBM's governance-led play in regulated estates; reduces audit prep time for risk teams.",
    ["vendor_ibm"], ["Enterprise control", "Regulation"],
    ["enterprise_control"], 62, 80, "positive",
    "IBM newsroom", "https://newsroom.ibm.com"),

  make("news_20", 20,
    "Snowflake Cortex Agents reaches GA across regions",
    "Cortex Agents now generally available across all major Snowflake regions, with Cortex Guard policy enforcement and audit log integration.",
    "Snowflake catches up to Databricks on agent surface area inside the warehouse boundary; data-resident agentic workloads gain a credible second option.",
    ["vendor_snowflake"], ["Product launch"],
    ["integration_ops", "enterprise_control"], 70, 82, "positive",
    "Snowflake", "https://www.snowflake.com",
    ["vendor_databricks"]),

  make("news_21", 21,
    "Oracle reports record sovereign-region AI revenue",
    "Oracle disclosed >40% YoY AI revenue growth in sovereign + regulated regions, citing wins in defence and public sector.",
    "Validates Oracle's sovereign positioning; the under-told growth story in enterprise AI.",
    ["vendor_oracle"], ["Market movement"],
    ["market_strength", "vendor_resilience"], 64, 76, "positive",
    "Oracle Q-results call", "https://investor.oracle.com"),

  make("news_22", 22,
    "Writer ships clinical-content guardrails for med-comms",
    "Writer announced clinical-content guardrails developed with a Top 10 pharma customer for med-comms and MLR review workflows.",
    "Reinforces Writer's regulated-content niche; makes pharma med-comms a defendable lane vs hyperscaler assistants.",
    ["vendor_writer"], ["Product launch", "Enterprise control"],
    ["business_fit", "enterprise_control"], 56, 76, "positive",
    "Writer blog", "https://writer.com/blog"),

  make("news_23", 23,
    "Risk: regulator opens enquiry into model-training data practices",
    "A regulator opened a formal enquiry into the training-data practices of a frontier model provider.",
    "Increases legal/risk overhead for frontier providers; reinforces buyer preference for vendors with documented training-data policy.",
    ["vendor_openai"], ["Risk event", "Regulation"],
    ["enterprise_control"], 76, 70, "negative",
    "FT", "https://www.ft.com"),

  make("news_24", 24,
    "Rogo lands first European IB customer",
    "Rogo signed its first European investment-bank customer, expanding beyond US-only deployments.",
    "Modest but useful expansion signal; key question is whether Rogo can defend in a Hebbia-led buy-side market.",
    ["vendor_rogo"], ["Market movement"],
    ["market_strength"], 50, 64, "positive",
    "Reuters", "https://www.reuters.com",
    ["vendor_hebbia"]),

  make("news_25", 25,
    "Mistral Large 3 launches with category-leading EU benchmarks",
    "Mistral released Mistral Large 3 with strong reasoning + multilingual benchmarks, available on Azure and Le Plateforme.",
    "Strengthens Mistral's commercial story in EU-regulated workloads.",
    ["vendor_mistral"], ["Product launch"],
    ["reliability_safety", "market_strength"], 66, 76, "positive",
    "Mistral", "https://mistral.ai"),

  make("news_26", 26,
    "Salesforce + AWS deepen Agentforce + Bedrock interop",
    "Agentforce now supports Bedrock-hosted Anthropic + Amazon Nova models with native Trust-Layer mediation.",
    "Multi-model agent platforms accelerate; reduces single-frontier-model lock-in for Agentforce buyers.",
    ["vendor_salesforce", "vendor_aws", "vendor_anthropic"],
    ["Partnership", "Strategy signal"],
    ["integration_ops"], 64, 78, "positive",
    "AWS + Salesforce joint blog", "https://aws.amazon.com/blogs",
    []),

  make("news_27", 27,
    "Glean + ServiceNow co-sell agreement announced",
    "Glean and ServiceNow announced a co-sell agreement covering enterprise search + Now Assist deployments.",
    "Validates Glean's enterprise-search differentiation and gives ServiceNow a stronger knowledge layer.",
    ["vendor_glean", "vendor_servicenow"], ["Partnership"],
    ["integration_ops", "market_strength"], 56, 76, "positive",
    "ServiceNow newsroom", "https://www.servicenow.com/company/media.html"),

  make("news_28", 28,
    "OpenAI ships DPA + EU residency expansion",
    "OpenAI extended Data Processing Addendum coverage and EU residency to all Enterprise + Team customers, plus added auditor-friendly logs.",
    "Reduces friction with EU regulated buyers — closes a long-standing gap.",
    ["vendor_openai"], ["Enterprise control"],
    ["enterprise_control"], 68, 80, "positive",
    "OpenAI", "https://openai.com/enterprise",
    ["vendor_microsoft"]),

  make("news_29", 29,
    "Cohere wins UK central-government RAG framework",
    "Cohere awarded a place on a UK central-government RAG framework alongside Microsoft and IBM.",
    "Strengthens Cohere's public-sector commercial story; small absolute share but high-signal validation.",
    ["vendor_cohere", "vendor_microsoft", "vendor_ibm"],
    ["Market movement", "Partnership"],
    ["market_strength"], 58, 78, "positive",
    "UK gov.uk", "https://www.gov.uk"),

  make("news_30", 30,
    "Anthropic + Databricks deepen integration",
    "Anthropic and Databricks announced extended integration: Claude available natively for Mosaic AI Agent Framework and Genie Spaces.",
    "Tightens Claude's lakehouse story; closes a meaningful gap vs OpenAI on Snowflake and AWS Bedrock.",
    ["vendor_anthropic", "vendor_databricks"], ["Partnership"],
    ["integration_ops"], 62, 80, "positive",
    "Databricks newsroom", "https://www.databricks.com/company/newsroom",
    ["vendor_openai", "vendor_snowflake"]),
];
