// Ported from ranking-engine repo: lib/intelligence/vendor-uptake-seed.ts
// Origin snapshot: _archive/ranking-engine-stray-copy-2026-07-08, copied 30 July 2026.

// AUTO-GENERATED from /Users/michaelcook/Desktop/Ai vendor breakouts/*.xlsx on 2026-05-28.
// Sources:
//   - vendor_industry_region_ai_share_model.xlsx → Segment_Shares (585 rows, 5 regions × 9 industries × 13 vendors)
//   - Enterprise_AI_Market_Share_2026.xlsx → Company Size (Large Enterprise vs SME per vendor)
// Shares are FRACTIONS in [0,1], normalised within each (region, industry) cell.

export type Region = "North America" | "Europe & UK" | "APAC" | "Latin America" | "Middle East & Africa";
export type Industry = "Technology / software" | "Financial services" | "Legal" | "Professional services / consulting" | "Healthcare / life sciences" | "Manufacturing / industrials" | "Retail / consumer / ecommerce" | "Public sector / government" | "Education / research / media";
export type CompanySize = "Large Enterprise" | "SME";
export type ConfidenceLabel = "Low" | "Low-Medium" | "Medium-Low" | "Medium" | "High";

export interface SegmentShareRow {
  region: Region;
  industry: Industry;
  vendor: string;
  share: number;        // 0..1
  confidence: ConfidenceLabel;
}

export interface CompanySizeRow {
  vendor: string;
  large: number;        // 0..1 — large-enterprise share
  sme: number;          // 0..1 — SME share
}

export const REGIONS: Region[] = ["North America","Europe & UK","APAC","Latin America","Middle East & Africa"];
export const INDUSTRIES: Industry[] = ["Technology / software","Financial services","Legal","Professional services / consulting","Healthcare / life sciences","Manufacturing / industrials","Retail / consumer / ecommerce","Public sector / government","Education / research / media"];
export const COMPANY_SIZES: CompanySize[] = ["Large Enterprise", "SME"];
export const UPTAKE_VENDORS: string[] = ["Anthropic","Cohere","Google DeepMind","Harvey","IBM watsonx","Meta","Mistral AI","Moveworks","OpenAI","Perplexity","Rogo","Writer","xAI"];

export const SEGMENT_SHARES: SegmentShareRow[] = [
  { region: "North America", industry: "Technology / software", vendor: "Anthropic", share: 0.3834, confidence: "Medium" },
  { region: "North America", industry: "Technology / software", vendor: "OpenAI", share: 0.2358, confidence: "Medium" },
  { region: "North America", industry: "Technology / software", vendor: "Google DeepMind", share: 0.1396, confidence: "Medium" },
  { region: "North America", industry: "Technology / software", vendor: "Meta", share: 0.0624, confidence: "Low-Medium" },
  { region: "North America", industry: "Technology / software", vendor: "Perplexity", share: 0.0397, confidence: "Low-Medium" },
  { region: "North America", industry: "Technology / software", vendor: "Cohere", share: 0.0372, confidence: "Medium-Low" },
  { region: "North America", industry: "Technology / software", vendor: "Moveworks", share: 0.0273, confidence: "Medium-Low" },
  { region: "North America", industry: "Technology / software", vendor: "Writer", share: 0.0223, confidence: "Low-Medium" },
  { region: "North America", industry: "Technology / software", vendor: "xAI", share: 0.0205, confidence: "Low" },
  { region: "North America", industry: "Technology / software", vendor: "Mistral AI", share: 0.0149, confidence: "Low" },
  { region: "North America", industry: "Technology / software", vendor: "IBM watsonx", share: 0.0106, confidence: "Low" },
  { region: "North America", industry: "Technology / software", vendor: "Rogo", share: 0.0062, confidence: "Low" },
  { region: "North America", industry: "Technology / software", vendor: "Harvey", share: 0, confidence: "Low" },
  { region: "North America", industry: "Financial services", vendor: "Anthropic", share: 0.2588, confidence: "Medium" },
  { region: "North America", industry: "Financial services", vendor: "OpenAI", share: 0.2329, confidence: "Medium" },
  { region: "North America", industry: "Financial services", vendor: "Google DeepMind", share: 0.1277, confidence: "Medium" },
  { region: "North America", industry: "Financial services", vendor: "IBM watsonx", share: 0.0919, confidence: "Medium" },
  { region: "North America", industry: "Financial services", vendor: "Cohere", share: 0.0901, confidence: "Medium-Low" },
  { region: "North America", industry: "Financial services", vendor: "Perplexity", share: 0.0481, confidence: "Low-Medium" },
  { region: "North America", industry: "Financial services", vendor: "Rogo", share: 0.0481, confidence: "Medium" },
  { region: "North America", industry: "Financial services", vendor: "Moveworks", share: 0.0264, confidence: "Medium-Low" },
  { region: "North America", industry: "Financial services", vendor: "Meta", share: 0.0227, confidence: "Low-Medium" },
  { region: "North America", industry: "Financial services", vendor: "Writer", share: 0.0216, confidence: "Low-Medium" },
  { region: "North America", industry: "Financial services", vendor: "Mistral AI", share: 0.0144, confidence: "Low" },
  { region: "North America", industry: "Financial services", vendor: "Harvey", share: 0.0106, confidence: "Low" },
  { region: "North America", industry: "Financial services", vendor: "xAI", share: 0.0066, confidence: "Low" },
  { region: "North America", industry: "Legal", vendor: "Harvey", share: 0.3736, confidence: "High" },
  { region: "North America", industry: "Legal", vendor: "Anthropic", share: 0.1703, confidence: "Medium" },
  { region: "North America", industry: "Legal", vendor: "OpenAI", share: 0.166, confidence: "Medium" },
  { region: "North America", industry: "Legal", vendor: "Google DeepMind", share: 0.0682, confidence: "Medium" },
  { region: "North America", industry: "Legal", vendor: "Writer", share: 0.0491, confidence: "Low-Medium" },
  { region: "North America", industry: "Legal", vendor: "Perplexity", share: 0.0485, confidence: "Low-Medium" },
  { region: "North America", industry: "Legal", vendor: "Cohere", share: 0.0364, confidence: "Medium-Low" },
  { region: "North America", industry: "Legal", vendor: "Mistral AI", share: 0.0243, confidence: "Medium-Low" },
  { region: "North America", industry: "Legal", vendor: "Meta", share: 0.0229, confidence: "Low-Medium" },
  { region: "North America", industry: "Legal", vendor: "IBM watsonx", share: 0.0206, confidence: "Low" },
  { region: "North America", industry: "Legal", vendor: "Moveworks", share: 0.0133, confidence: "Medium-Low" },
  { region: "North America", industry: "Legal", vendor: "xAI", share: 0.0067, confidence: "Low" },
  { region: "North America", industry: "Legal", vendor: "Rogo", share: 0, confidence: "Low" },
  { region: "North America", industry: "Professional services / consulting", vendor: "Anthropic", share: 0.2858, confidence: "Medium" },
  { region: "North America", industry: "Professional services / consulting", vendor: "OpenAI", share: 0.2599, confidence: "Medium" },
  { region: "North America", industry: "Professional services / consulting", vendor: "Google DeepMind", share: 0.1222, confidence: "Medium" },
  { region: "North America", industry: "Professional services / consulting", vendor: "Perplexity", share: 0.0586, confidence: "Low-Medium" },
  { region: "North America", industry: "Professional services / consulting", vendor: "Writer", share: 0.055, confidence: "Low-Medium" },
  { region: "North America", industry: "Professional services / consulting", vendor: "Harvey", share: 0.0537, confidence: "Low" },
  { region: "North America", industry: "Professional services / consulting", vendor: "IBM watsonx", share: 0.0415, confidence: "Low" },
  { region: "North America", industry: "Professional services / consulting", vendor: "Moveworks", share: 0.0403, confidence: "Medium-Low" },
  { region: "North America", industry: "Professional services / consulting", vendor: "Cohere", share: 0.0366, confidence: "Medium-Low" },
  { region: "North America", industry: "Professional services / consulting", vendor: "Meta", share: 0.023, confidence: "Low-Medium" },
  { region: "North America", industry: "Professional services / consulting", vendor: "xAI", share: 0.0134, confidence: "Low" },
  { region: "North America", industry: "Professional services / consulting", vendor: "Mistral AI", share: 0.0098, confidence: "Low" },
  { region: "North America", industry: "Professional services / consulting", vendor: "Rogo", share: 0, confidence: "Low" },
  { region: "North America", industry: "Healthcare / life sciences", vendor: "OpenAI", share: 0.2784, confidence: "Medium" },
  { region: "North America", industry: "Healthcare / life sciences", vendor: "Anthropic", share: 0.2515, confidence: "Medium" },
  { region: "North America", industry: "Healthcare / life sciences", vendor: "Google DeepMind", share: 0.1297, confidence: "Medium" },
  { region: "North America", industry: "Healthcare / life sciences", vendor: "Cohere", share: 0.0733, confidence: "Medium-Low" },
  { region: "North America", industry: "Healthcare / life sciences", vendor: "IBM watsonx", share: 0.0727, confidence: "Medium" },
  { region: "North America", industry: "Healthcare / life sciences", vendor: "Perplexity", share: 0.0391, confidence: "Low-Medium" },
  { region: "North America", industry: "Healthcare / life sciences", vendor: "Writer", share: 0.033, confidence: "Low-Medium" },
  { region: "North America", industry: "Healthcare / life sciences", vendor: "Harvey", share: 0.0322, confidence: "Low" },
  { region: "North America", industry: "Healthcare / life sciences", vendor: "Moveworks", share: 0.0269, confidence: "Medium-Low" },
  { region: "North America", industry: "Healthcare / life sciences", vendor: "Meta", share: 0.023, confidence: "Low-Medium" },
  { region: "North America", industry: "Healthcare / life sciences", vendor: "Mistral AI", share: 0.0147, confidence: "Low" },
  { region: "North America", industry: "Healthcare / life sciences", vendor: "xAI", share: 0.0134, confidence: "Low" },
  { region: "North America", industry: "Healthcare / life sciences", vendor: "Rogo", share: 0.0122, confidence: "Low" },
  { region: "North America", industry: "Manufacturing / industrials", vendor: "OpenAI", share: 0.2989, confidence: "Medium" },
  { region: "North America", industry: "Manufacturing / industrials", vendor: "Anthropic", share: 0.2137, confidence: "Medium" },
  { region: "North America", industry: "Manufacturing / industrials", vendor: "Google DeepMind", share: 0.1586, confidence: "Medium" },
  { region: "North America", industry: "Manufacturing / industrials", vendor: "IBM watsonx", share: 0.0863, confidence: "Low" },
  { region: "North America", industry: "Manufacturing / industrials", vendor: "Cohere", share: 0.0571, confidence: "Medium-Low" },
  { region: "North America", industry: "Manufacturing / industrials", vendor: "Moveworks", share: 0.0419, confidence: "Medium-Low" },
  { region: "North America", industry: "Manufacturing / industrials", vendor: "Meta", share: 0.0399, confidence: "Low-Medium" },
  { region: "North America", industry: "Manufacturing / industrials", vendor: "Perplexity", share: 0.0304, confidence: "Low-Medium" },
  { region: "North America", industry: "Manufacturing / industrials", vendor: "Mistral AI", share: 0.0254, confidence: "Medium-Low" },
  { region: "North America", industry: "Manufacturing / industrials", vendor: "Writer", share: 0.0228, confidence: "Low-Medium" },
  { region: "North America", industry: "Manufacturing / industrials", vendor: "xAI", share: 0.014, confidence: "Low" },
  { region: "North America", industry: "Manufacturing / industrials", vendor: "Harvey", share: 0.0112, confidence: "Low" },
  { region: "North America", industry: "Manufacturing / industrials", vendor: "Rogo", share: 0, confidence: "Low" },
  { region: "North America", industry: "Retail / consumer / ecommerce", vendor: "OpenAI", share: 0.3075, confidence: "Medium" },
  { region: "North America", industry: "Retail / consumer / ecommerce", vendor: "Anthropic", share: 0.1893, confidence: "Medium" },
  { region: "North America", industry: "Retail / consumer / ecommerce", vendor: "Google DeepMind", share: 0.1738, confidence: "Medium" },
  { region: "North America", industry: "Retail / consumer / ecommerce", vendor: "Moveworks", share: 0.0556, confidence: "Medium-Low" },
  { region: "North America", industry: "Retail / consumer / ecommerce", vendor: "Perplexity", share: 0.0506, confidence: "Low-Medium" },
  { region: "North America", industry: "Retail / consumer / ecommerce", vendor: "Meta", share: 0.0477, confidence: "Low-Medium" },
  { region: "North America", industry: "Retail / consumer / ecommerce", vendor: "Writer", share: 0.0455, confidence: "Low-Medium" },
  { region: "North America", industry: "Retail / consumer / ecommerce", vendor: "IBM watsonx", share: 0.043, confidence: "Low" },
  { region: "North America", industry: "Retail / consumer / ecommerce", vendor: "Cohere", share: 0.0379, confidence: "Medium-Low" },
  { region: "North America", industry: "Retail / consumer / ecommerce", vendor: "xAI", share: 0.0278, confidence: "Low" },
  { region: "North America", industry: "Retail / consumer / ecommerce", vendor: "Harvey", share: 0.0111, confidence: "Low" },
  { region: "North America", industry: "Retail / consumer / ecommerce", vendor: "Mistral AI", share: 0.0101, confidence: "Low" },
  { region: "North America", industry: "Retail / consumer / ecommerce", vendor: "Rogo", share: 0, confidence: "Low" },
  { region: "North America", industry: "Public sector / government", vendor: "IBM watsonx", share: 0.2491, confidence: "Medium" },
  { region: "North America", industry: "Public sector / government", vendor: "OpenAI", share: 0.1671, confidence: "Medium" },
  { region: "North America", industry: "Public sector / government", vendor: "Anthropic", share: 0.1486, confidence: "Medium" },
  { region: "North America", industry: "Public sector / government", vendor: "Cohere", share: 0.1465, confidence: "Medium-Low" },
  { region: "North America", industry: "Public sector / government", vendor: "Google DeepMind", share: 0.1145, confidence: "Medium" },
  { region: "North America", industry: "Public sector / government", vendor: "Mistral AI", share: 0.0488, confidence: "Medium-Low" },
  { region: "North America", industry: "Public sector / government", vendor: "Perplexity", share: 0.0293, confidence: "Low-Medium" },
  { region: "North America", industry: "Public sector / government", vendor: "Moveworks", share: 0.0269, confidence: "Medium-Low" },
  { region: "North America", industry: "Public sector / government", vendor: "Meta", share: 0.023, confidence: "Low-Medium" },
  { region: "North America", industry: "Public sector / government", vendor: "Writer", share: 0.022, confidence: "Low-Medium" },
  { region: "North America", industry: "Public sector / government", vendor: "xAI", share: 0.0134, confidence: "Low" },
  { region: "North America", industry: "Public sector / government", vendor: "Harvey", share: 0.0107, confidence: "Low" },
  { region: "North America", industry: "Public sector / government", vendor: "Rogo", share: 0, confidence: "Low" },
  { region: "North America", industry: "Education / research / media", vendor: "OpenAI", share: 0.3404, confidence: "Medium" },
  { region: "North America", industry: "Education / research / media", vendor: "Anthropic", share: 0.1916, confidence: "Medium" },
  { region: "North America", industry: "Education / research / media", vendor: "Google DeepMind", share: 0.16, confidence: "Medium" },
  { region: "North America", industry: "Education / research / media", vendor: "Perplexity", share: 0.0921, confidence: "Low-Medium" },
  { region: "North America", industry: "Education / research / media", vendor: "Writer", share: 0.0576, confidence: "Low-Medium" },
  { region: "North America", industry: "Education / research / media", vendor: "Meta", share: 0.0402, confidence: "Low-Medium" },
  { region: "North America", industry: "Education / research / media", vendor: "Cohere", share: 0.0384, confidence: "Medium-Low" },
  { region: "North America", industry: "Education / research / media", vendor: "xAI", share: 0.0282, confidence: "Low" },
  { region: "North America", industry: "Education / research / media", vendor: "Mistral AI", share: 0.0154, confidence: "Low" },
  { region: "North America", industry: "Education / research / media", vendor: "Moveworks", share: 0.0141, confidence: "Medium-Low" },
  { region: "North America", industry: "Education / research / media", vendor: "Harvey", share: 0.0113, confidence: "Low" },
  { region: "North America", industry: "Education / research / media", vendor: "IBM watsonx", share: 0.0109, confidence: "Low" },
  { region: "North America", industry: "Education / research / media", vendor: "Rogo", share: 0, confidence: "Low" },
  { region: "Europe & UK", industry: "Technology / software", vendor: "Anthropic", share: 0.2773, confidence: "Medium" },
  { region: "Europe & UK", industry: "Technology / software", vendor: "OpenAI", share: 0.2276, confidence: "Medium" },
  { region: "Europe & UK", industry: "Technology / software", vendor: "Google DeepMind", share: 0.1772, confidence: "Medium" },
  { region: "Europe & UK", industry: "Technology / software", vendor: "Mistral AI", share: 0.105, confidence: "Medium-Low" },
  { region: "Europe & UK", industry: "Technology / software", vendor: "Cohere", share: 0.0525, confidence: "Medium-Low" },
  { region: "Europe & UK", industry: "Technology / software", vendor: "Meta", share: 0.048, confidence: "Low-Medium" },
  { region: "Europe & UK", industry: "Technology / software", vendor: "Perplexity", share: 0.0336, confidence: "Low-Medium" },
  { region: "Europe & UK", industry: "Technology / software", vendor: "Writer", share: 0.021, confidence: "Low-Medium" },
  { region: "Europe & UK", industry: "Technology / software", vendor: "xAI", share: 0.0158, confidence: "Low" },
  { region: "Europe & UK", industry: "Technology / software", vendor: "IBM watsonx", share: 0.0158, confidence: "Low" },
  { region: "Europe & UK", industry: "Technology / software", vendor: "Moveworks", share: 0.0158, confidence: "Medium-Low" },
  { region: "Europe & UK", industry: "Technology / software", vendor: "Rogo", share: 0.0105, confidence: "Low" },
  { region: "Europe & UK", industry: "Technology / software", vendor: "Harvey", share: 0, confidence: "Low" },
  { region: "Europe & UK", industry: "Financial services", vendor: "OpenAI", share: 0.1974, confidence: "Medium" },
  { region: "Europe & UK", industry: "Financial services", vendor: "Anthropic", share: 0.1644, confidence: "Medium" },
  { region: "Europe & UK", industry: "Financial services", vendor: "Google DeepMind", share: 0.1424, confidence: "Medium" },
  { region: "Europe & UK", industry: "Financial services", vendor: "IBM watsonx", share: 0.1206, confidence: "Medium" },
  { region: "Europe & UK", industry: "Financial services", vendor: "Cohere", share: 0.1117, confidence: "Medium-Low" },
  { region: "Europe & UK", industry: "Financial services", vendor: "Mistral AI", share: 0.0893, confidence: "Medium-Low" },
  { region: "Europe & UK", industry: "Financial services", vendor: "Rogo", share: 0.0715, confidence: "Medium" },
  { region: "Europe & UK", industry: "Financial services", vendor: "Perplexity", share: 0.0357, confidence: "Low-Medium" },
  { region: "Europe & UK", industry: "Financial services", vendor: "Writer", share: 0.0179, confidence: "Low-Medium" },
  { region: "Europe & UK", industry: "Financial services", vendor: "Harvey", share: 0.0161, confidence: "Low" },
  { region: "Europe & UK", industry: "Financial services", vendor: "Meta", share: 0.0153, confidence: "Low-Medium" },
  { region: "Europe & UK", industry: "Financial services", vendor: "Moveworks", share: 0.0134, confidence: "Medium-Low" },
  { region: "Europe & UK", industry: "Financial services", vendor: "xAI", share: 0.0045, confidence: "Low" },
  { region: "Europe & UK", industry: "Legal", vendor: "Harvey", share: 0.4661, confidence: "High" },
  { region: "Europe & UK", industry: "Legal", vendor: "Mistral AI", share: 0.1233, confidence: "Medium-Low" },
  { region: "Europe & UK", industry: "Legal", vendor: "OpenAI", share: 0.1154, confidence: "Medium" },
  { region: "Europe & UK", industry: "Legal", vendor: "Anthropic", share: 0.0888, confidence: "Medium" },
  { region: "Europe & UK", industry: "Legal", vendor: "Google DeepMind", share: 0.0624, confidence: "Medium" },
  { region: "Europe & UK", industry: "Legal", vendor: "Cohere", share: 0.037, confidence: "Medium-Low" },
  { region: "Europe & UK", industry: "Legal", vendor: "Writer", share: 0.0333, confidence: "Low-Medium" },
  { region: "Europe & UK", industry: "Legal", vendor: "Perplexity", share: 0.0296, confidence: "Low-Medium" },
  { region: "Europe & UK", industry: "Legal", vendor: "IBM watsonx", share: 0.0222, confidence: "Low" },
  { region: "Europe & UK", industry: "Legal", vendor: "Meta", share: 0.0127, confidence: "Low-Medium" },
  { region: "Europe & UK", industry: "Legal", vendor: "Moveworks", share: 0.0055, confidence: "Medium-Low" },
  { region: "Europe & UK", industry: "Legal", vendor: "xAI", share: 0.0037, confidence: "Low" },
  { region: "Europe & UK", industry: "Legal", vendor: "Rogo", share: 0, confidence: "Low" },
  { region: "Europe & UK", industry: "Professional services / consulting", vendor: "OpenAI", share: 0.241, confidence: "Medium" },
  { region: "Europe & UK", industry: "Professional services / consulting", vendor: "Anthropic", share: 0.1986, confidence: "Medium" },
  { region: "Europe & UK", industry: "Professional services / consulting", vendor: "Google DeepMind", share: 0.149, confidence: "Medium" },
  { region: "Europe & UK", industry: "Professional services / consulting", vendor: "Harvey", share: 0.0894, confidence: "Low" },
  { region: "Europe & UK", industry: "Professional services / consulting", vendor: "Mistral AI", share: 0.0662, confidence: "Medium-Low" },
  { region: "Europe & UK", industry: "Professional services / consulting", vendor: "IBM watsonx", share: 0.0596, confidence: "Low" },
  { region: "Europe & UK", industry: "Professional services / consulting", vendor: "Cohere", share: 0.0497, confidence: "Medium-Low" },
  { region: "Europe & UK", industry: "Professional services / consulting", vendor: "Writer", share: 0.0497, confidence: "Low-Medium" },
  { region: "Europe & UK", industry: "Professional services / consulting", vendor: "Perplexity", share: 0.0477, confidence: "Low-Medium" },
  { region: "Europe & UK", industry: "Professional services / consulting", vendor: "Moveworks", share: 0.0223, confidence: "Medium-Low" },
  { region: "Europe & UK", industry: "Professional services / consulting", vendor: "Meta", share: 0.017, confidence: "Low-Medium" },
  { region: "Europe & UK", industry: "Professional services / consulting", vendor: "xAI", share: 0.0099, confidence: "Low" },
  { region: "Europe & UK", industry: "Professional services / consulting", vendor: "Rogo", share: 0, confidence: "Low" },
  { region: "Europe & UK", industry: "Healthcare / life sciences", vendor: "OpenAI", share: 0.2411, confidence: "Medium" },
  { region: "Europe & UK", industry: "Healthcare / life sciences", vendor: "Anthropic", share: 0.1632, confidence: "Medium" },
  { region: "Europe & UK", industry: "Healthcare / life sciences", vendor: "Google DeepMind", share: 0.1478, confidence: "Medium" },
  { region: "Europe & UK", industry: "Healthcare / life sciences", vendor: "IBM watsonx", share: 0.0974, confidence: "Medium" },
  { region: "Europe & UK", industry: "Healthcare / life sciences", vendor: "Cohere", share: 0.0927, confidence: "Medium-Low" },
  { region: "Europe & UK", industry: "Healthcare / life sciences", vendor: "Mistral AI", share: 0.0927, confidence: "Medium-Low" },
  { region: "Europe & UK", industry: "Healthcare / life sciences", vendor: "Harvey", share: 0.0501, confidence: "Low" },
  { region: "Europe & UK", industry: "Healthcare / life sciences", vendor: "Perplexity", share: 0.0297, confidence: "Low-Medium" },
  { region: "Europe & UK", industry: "Healthcare / life sciences", vendor: "Writer", share: 0.0278, confidence: "Low-Medium" },
  { region: "Europe & UK", industry: "Healthcare / life sciences", vendor: "Rogo", share: 0.0185, confidence: "Low" },
  { region: "Europe & UK", industry: "Healthcare / life sciences", vendor: "Meta", share: 0.0159, confidence: "Low-Medium" },
  { region: "Europe & UK", industry: "Healthcare / life sciences", vendor: "Moveworks", share: 0.0139, confidence: "Medium-Low" },
  { region: "Europe & UK", industry: "Healthcare / life sciences", vendor: "xAI", share: 0.0093, confidence: "Low" },
  { region: "Europe & UK", industry: "Manufacturing / industrials", vendor: "OpenAI", share: 0.2476, confidence: "Medium" },
  { region: "Europe & UK", industry: "Manufacturing / industrials", vendor: "Google DeepMind", share: 0.1728, confidence: "Medium" },
  { region: "Europe & UK", industry: "Manufacturing / industrials", vendor: "Mistral AI", share: 0.1536, confidence: "Medium-Low" },
  { region: "Europe & UK", industry: "Manufacturing / industrials", vendor: "Anthropic", share: 0.1327, confidence: "Medium" },
  { region: "Europe & UK", industry: "Manufacturing / industrials", vendor: "IBM watsonx", share: 0.1106, confidence: "Low" },
  { region: "Europe & UK", industry: "Manufacturing / industrials", vendor: "Cohere", share: 0.0691, confidence: "Medium-Low" },
  { region: "Europe & UK", industry: "Manufacturing / industrials", vendor: "Meta", share: 0.0263, confidence: "Low-Medium" },
  { region: "Europe & UK", industry: "Manufacturing / industrials", vendor: "Perplexity", share: 0.0221, confidence: "Low-Medium" },
  { region: "Europe & UK", industry: "Manufacturing / industrials", vendor: "Moveworks", share: 0.0207, confidence: "Medium-Low" },
  { region: "Europe & UK", industry: "Manufacturing / industrials", vendor: "Writer", share: 0.0184, confidence: "Low-Medium" },
  { region: "Europe & UK", industry: "Manufacturing / industrials", vendor: "Harvey", share: 0.0166, confidence: "Low" },
  { region: "Europe & UK", industry: "Manufacturing / industrials", vendor: "xAI", share: 0.0092, confidence: "Low" },
  { region: "Europe & UK", industry: "Manufacturing / industrials", vendor: "Rogo", share: 0, confidence: "Low" },
  { region: "Europe & UK", industry: "Retail / consumer / ecommerce", vendor: "OpenAI", share: 0.2858, confidence: "Medium" },
  { region: "Europe & UK", industry: "Retail / consumer / ecommerce", vendor: "Google DeepMind", share: 0.2125, confidence: "Medium" },
  { region: "Europe & UK", industry: "Retail / consumer / ecommerce", vendor: "Anthropic", share: 0.1319, confidence: "Medium" },
  { region: "Europe & UK", industry: "Retail / consumer / ecommerce", vendor: "Mistral AI", share: 0.0687, confidence: "Medium-Low" },
  { region: "Europe & UK", industry: "Retail / consumer / ecommerce", vendor: "IBM watsonx", share: 0.0618, confidence: "Low" },
  { region: "Europe & UK", industry: "Retail / consumer / ecommerce", vendor: "Cohere", share: 0.0515, confidence: "Medium-Low" },
  { region: "Europe & UK", industry: "Retail / consumer / ecommerce", vendor: "Perplexity", share: 0.0412, confidence: "Low-Medium" },
  { region: "Europe & UK", industry: "Retail / consumer / ecommerce", vendor: "Writer", share: 0.0412, confidence: "Low-Medium" },
  { region: "Europe & UK", industry: "Retail / consumer / ecommerce", vendor: "Meta", share: 0.0353, confidence: "Low-Medium" },
  { region: "Europe & UK", industry: "Retail / consumer / ecommerce", vendor: "Moveworks", share: 0.0309, confidence: "Medium-Low" },
  { region: "Europe & UK", industry: "Retail / consumer / ecommerce", vendor: "xAI", share: 0.0206, confidence: "Low" },
  { region: "Europe & UK", industry: "Retail / consumer / ecommerce", vendor: "Harvey", share: 0.0185, confidence: "Low" },
  { region: "Europe & UK", industry: "Retail / consumer / ecommerce", vendor: "Rogo", share: 0, confidence: "Low" },
  { region: "Europe & UK", industry: "Public sector / government", vendor: "IBM watsonx", share: 0.2575, confidence: "Medium" },
  { region: "Europe & UK", industry: "Public sector / government", vendor: "Mistral AI", share: 0.2384, confidence: "Medium-Low" },
  { region: "Europe & UK", industry: "Public sector / government", vendor: "Cohere", share: 0.1431, confidence: "Medium-Low" },
  { region: "Europe & UK", industry: "Public sector / government", vendor: "OpenAI", share: 0.1116, confidence: "Medium" },
  { region: "Europe & UK", industry: "Public sector / government", vendor: "Google DeepMind", share: 0.1006, confidence: "Medium" },
  { region: "Europe & UK", industry: "Public sector / government", vendor: "Anthropic", share: 0.0744, confidence: "Medium" },
  { region: "Europe & UK", industry: "Public sector / government", vendor: "Perplexity", share: 0.0172, confidence: "Low-Medium" },
  { region: "Europe & UK", industry: "Public sector / government", vendor: "Writer", share: 0.0143, confidence: "Low-Medium" },
  { region: "Europe & UK", industry: "Public sector / government", vendor: "Harvey", share: 0.0129, confidence: "Low" },
  { region: "Europe & UK", industry: "Public sector / government", vendor: "Meta", share: 0.0123, confidence: "Low-Medium" },
  { region: "Europe & UK", industry: "Public sector / government", vendor: "Moveworks", share: 0.0107, confidence: "Medium-Low" },
  { region: "Europe & UK", industry: "Public sector / government", vendor: "xAI", share: 0.0072, confidence: "Low" },
  { region: "Europe & UK", industry: "Public sector / government", vendor: "Rogo", share: 0, confidence: "Low" },
  { region: "Europe & UK", industry: "Education / research / media", vendor: "OpenAI", share: 0.3096, confidence: "Medium" },
  { region: "Europe & UK", industry: "Education / research / media", vendor: "Google DeepMind", share: 0.1913, confidence: "Medium" },
  { region: "Europe & UK", industry: "Education / research / media", vendor: "Anthropic", share: 0.1306, confidence: "Medium" },
  { region: "Europe & UK", industry: "Education / research / media", vendor: "Mistral AI", share: 0.1021, confidence: "Medium-Low" },
  { region: "Europe & UK", industry: "Education / research / media", vendor: "Perplexity", share: 0.0735, confidence: "Low-Medium" },
  { region: "Europe & UK", industry: "Education / research / media", vendor: "Cohere", share: 0.051, confidence: "Medium-Low" },
  { region: "Europe & UK", industry: "Education / research / media", vendor: "Writer", share: 0.051, confidence: "Low-Medium" },
  { region: "Europe & UK", industry: "Education / research / media", vendor: "Meta", share: 0.0292, confidence: "Low-Medium" },
  { region: "Europe & UK", industry: "Education / research / media", vendor: "xAI", share: 0.0204, confidence: "Low" },
  { region: "Europe & UK", industry: "Education / research / media", vendor: "Harvey", share: 0.0184, confidence: "Low" },
  { region: "Europe & UK", industry: "Education / research / media", vendor: "IBM watsonx", share: 0.0153, confidence: "Low" },
  { region: "Europe & UK", industry: "Education / research / media", vendor: "Moveworks", share: 0.0077, confidence: "Medium-Low" },
  { region: "Europe & UK", industry: "Education / research / media", vendor: "Rogo", share: 0, confidence: "Low" },
  { region: "APAC", industry: "Technology / software", vendor: "Anthropic", share: 0.3151, confidence: "Medium" },
  { region: "APAC", industry: "Technology / software", vendor: "OpenAI", share: 0.2652, confidence: "Medium" },
  { region: "APAC", industry: "Technology / software", vendor: "Google DeepMind", share: 0.2126, confidence: "Medium" },
  { region: "APAC", industry: "Technology / software", vendor: "Meta", share: 0.0568, confidence: "Low-Medium" },
  { region: "APAC", industry: "Technology / software", vendor: "Perplexity", share: 0.0358, confidence: "Low-Medium" },
  { region: "APAC", industry: "Technology / software", vendor: "Cohere", share: 0.0249, confidence: "Low" },
  { region: "APAC", industry: "Technology / software", vendor: "Mistral AI", share: 0.0249, confidence: "Low" },
  { region: "APAC", industry: "Technology / software", vendor: "Writer", share: 0.0169, confidence: "Low-Medium" },
  { region: "APAC", industry: "Technology / software", vendor: "xAI", share: 0.0149, confidence: "Low" },
  { region: "APAC", industry: "Technology / software", vendor: "Moveworks", share: 0.0149, confidence: "Medium-Low" },
  { region: "APAC", industry: "Technology / software", vendor: "IBM watsonx", share: 0.0099, confidence: "Low" },
  { region: "APAC", industry: "Technology / software", vendor: "Rogo", share: 0.008, confidence: "Low" },
  { region: "APAC", industry: "Technology / software", vendor: "Harvey", share: 0, confidence: "Low" },
  { region: "APAC", industry: "Financial services", vendor: "OpenAI", share: 0.2601, confidence: "Medium" },
  { region: "APAC", industry: "Financial services", vendor: "Anthropic", share: 0.2112, confidence: "Medium" },
  { region: "APAC", industry: "Financial services", vendor: "Google DeepMind", share: 0.1931, confidence: "Medium" },
  { region: "APAC", industry: "Financial services", vendor: "IBM watsonx", share: 0.0861, confidence: "Medium" },
  { region: "APAC", industry: "Financial services", vendor: "Rogo", share: 0.0612, confidence: "Medium" },
  { region: "APAC", industry: "Financial services", vendor: "Cohere", share: 0.0598, confidence: "Medium-Low" },
  { region: "APAC", industry: "Financial services", vendor: "Perplexity", share: 0.043, confidence: "Low-Medium" },
  { region: "APAC", industry: "Financial services", vendor: "Mistral AI", share: 0.0239, confidence: "Low" },
  { region: "APAC", industry: "Financial services", vendor: "Meta", share: 0.0205, confidence: "Low-Medium" },
  { region: "APAC", industry: "Financial services", vendor: "Writer", share: 0.0163, confidence: "Low-Medium" },
  { region: "APAC", industry: "Financial services", vendor: "Moveworks", share: 0.0143, confidence: "Medium-Low" },
  { region: "APAC", industry: "Financial services", vendor: "Harvey", share: 0.0057, confidence: "Low" },
  { region: "APAC", industry: "Financial services", vendor: "xAI", share: 0.0048, confidence: "Low" },
  { region: "APAC", industry: "Legal", vendor: "Harvey", share: 0.2451, confidence: "High" },
  { region: "APAC", industry: "Legal", vendor: "OpenAI", share: 0.2241, confidence: "Medium" },
  { region: "APAC", industry: "Legal", vendor: "Anthropic", share: 0.1681, confidence: "Medium" },
  { region: "APAC", industry: "Legal", vendor: "Google DeepMind", share: 0.1247, confidence: "Medium" },
  { region: "APAC", industry: "Legal", vendor: "Perplexity", share: 0.0525, confidence: "Low-Medium" },
  { region: "APAC", industry: "Legal", vendor: "Mistral AI", share: 0.0486, confidence: "Medium-Low" },
  { region: "APAC", industry: "Legal", vendor: "Writer", share: 0.0446, confidence: "Low-Medium" },
  { region: "APAC", industry: "Legal", vendor: "Cohere", share: 0.0292, confidence: "Low" },
  { region: "APAC", industry: "Legal", vendor: "Meta", share: 0.025, confidence: "Low-Medium" },
  { region: "APAC", industry: "Legal", vendor: "IBM watsonx", share: 0.0233, confidence: "Low" },
  { region: "APAC", industry: "Legal", vendor: "Moveworks", share: 0.0088, confidence: "Medium-Low" },
  { region: "APAC", industry: "Legal", vendor: "xAI", share: 0.0058, confidence: "Low" },
  { region: "APAC", industry: "Legal", vendor: "Rogo", share: 0, confidence: "Low" },
  { region: "APAC", industry: "Professional services / consulting", vendor: "OpenAI", share: 0.3015, confidence: "Medium" },
  { region: "APAC", industry: "Professional services / consulting", vendor: "Anthropic", share: 0.2422, confidence: "Medium" },
  { region: "APAC", industry: "Professional services / consulting", vendor: "Google DeepMind", share: 0.1918, confidence: "Medium" },
  { region: "APAC", industry: "Professional services / consulting", vendor: "Perplexity", share: 0.0545, confidence: "Low-Medium" },
  { region: "APAC", industry: "Professional services / consulting", vendor: "Writer", share: 0.0429, confidence: "Low-Medium" },
  { region: "APAC", industry: "Professional services / consulting", vendor: "IBM watsonx", share: 0.0404, confidence: "Low" },
  { region: "APAC", industry: "Professional services / consulting", vendor: "Harvey", share: 0.0303, confidence: "Low" },
  { region: "APAC", industry: "Professional services / consulting", vendor: "Cohere", share: 0.0252, confidence: "Low" },
  { region: "APAC", industry: "Professional services / consulting", vendor: "Moveworks", share: 0.0227, confidence: "Medium-Low" },
  { region: "APAC", industry: "Professional services / consulting", vendor: "Meta", share: 0.0216, confidence: "Low-Medium" },
  { region: "APAC", industry: "Professional services / consulting", vendor: "Mistral AI", share: 0.0168, confidence: "Low" },
  { region: "APAC", industry: "Professional services / consulting", vendor: "xAI", share: 0.0101, confidence: "Low" },
  { region: "APAC", industry: "Professional services / consulting", vendor: "Rogo", share: 0, confidence: "Low" },
  { region: "APAC", industry: "Healthcare / life sciences", vendor: "OpenAI", share: 0.3137, confidence: "Medium" },
  { region: "APAC", industry: "Healthcare / life sciences", vendor: "Anthropic", share: 0.2071, confidence: "Medium" },
  { region: "APAC", industry: "Healthcare / life sciences", vendor: "Google DeepMind", share: 0.1979, confidence: "Medium" },
  { region: "APAC", industry: "Healthcare / life sciences", vendor: "IBM watsonx", share: 0.0686, confidence: "Medium" },
  { region: "APAC", industry: "Healthcare / life sciences", vendor: "Cohere", share: 0.049, confidence: "Low" },
  { region: "APAC", industry: "Healthcare / life sciences", vendor: "Perplexity", share: 0.0353, confidence: "Low-Medium" },
  { region: "APAC", industry: "Healthcare / life sciences", vendor: "Writer", share: 0.025, confidence: "Low-Medium" },
  { region: "APAC", industry: "Healthcare / life sciences", vendor: "Mistral AI", share: 0.0245, confidence: "Low" },
  { region: "APAC", industry: "Healthcare / life sciences", vendor: "Meta", share: 0.021, confidence: "Low-Medium" },
  { region: "APAC", industry: "Healthcare / life sciences", vendor: "Harvey", share: 0.0176, confidence: "Low" },
  { region: "APAC", industry: "Healthcare / life sciences", vendor: "Rogo", share: 0.0157, confidence: "Low" },
  { region: "APAC", industry: "Healthcare / life sciences", vendor: "Moveworks", share: 0.0147, confidence: "Medium-Low" },
  { region: "APAC", industry: "Healthcare / life sciences", vendor: "xAI", share: 0.0098, confidence: "Low" },
  { region: "APAC", industry: "Manufacturing / industrials", vendor: "OpenAI", share: 0.3247, confidence: "Medium" },
  { region: "APAC", industry: "Manufacturing / industrials", vendor: "Google DeepMind", share: 0.2332, confidence: "Medium" },
  { region: "APAC", industry: "Manufacturing / industrials", vendor: "Anthropic", share: 0.1697, confidence: "Medium" },
  { region: "APAC", industry: "Manufacturing / industrials", vendor: "IBM watsonx", share: 0.0786, confidence: "Low" },
  { region: "APAC", industry: "Manufacturing / industrials", vendor: "Mistral AI", share: 0.0409, confidence: "Medium-Low" },
  { region: "APAC", industry: "Manufacturing / industrials", vendor: "Cohere", share: 0.0368, confidence: "Low" },
  { region: "APAC", industry: "Manufacturing / industrials", vendor: "Meta", share: 0.0351, confidence: "Low-Medium" },
  { region: "APAC", industry: "Manufacturing / industrials", vendor: "Perplexity", share: 0.0265, confidence: "Low-Medium" },
  { region: "APAC", industry: "Manufacturing / industrials", vendor: "Moveworks", share: 0.0221, confidence: "Medium-Low" },
  { region: "APAC", industry: "Manufacturing / industrials", vendor: "Writer", share: 0.0167, confidence: "Low-Medium" },
  { region: "APAC", industry: "Manufacturing / industrials", vendor: "xAI", share: 0.0098, confidence: "Low" },
  { region: "APAC", industry: "Manufacturing / industrials", vendor: "Harvey", share: 0.0059, confidence: "Low" },
  { region: "APAC", industry: "Manufacturing / industrials", vendor: "Rogo", share: 0, confidence: "Low" },
  { region: "APAC", industry: "Retail / consumer / ecommerce", vendor: "OpenAI", share: 0.3361, confidence: "Medium" },
  { region: "APAC", industry: "Retail / consumer / ecommerce", vendor: "Google DeepMind", share: 0.2572, confidence: "Medium" },
  { region: "APAC", industry: "Retail / consumer / ecommerce", vendor: "Anthropic", share: 0.1512, confidence: "Medium" },
  { region: "APAC", industry: "Retail / consumer / ecommerce", vendor: "Perplexity", share: 0.0443, confidence: "Low-Medium" },
  { region: "APAC", industry: "Retail / consumer / ecommerce", vendor: "Meta", share: 0.0422, confidence: "Low-Medium" },
  { region: "APAC", industry: "Retail / consumer / ecommerce", vendor: "IBM watsonx", share: 0.0394, confidence: "Low" },
  { region: "APAC", industry: "Retail / consumer / ecommerce", vendor: "Writer", share: 0.0335, confidence: "Low-Medium" },
  { region: "APAC", industry: "Retail / consumer / ecommerce", vendor: "Moveworks", share: 0.0295, confidence: "Medium-Low" },
  { region: "APAC", industry: "Retail / consumer / ecommerce", vendor: "Cohere", share: 0.0246, confidence: "Low" },
  { region: "APAC", industry: "Retail / consumer / ecommerce", vendor: "xAI", share: 0.0197, confidence: "Low" },
  { region: "APAC", industry: "Retail / consumer / ecommerce", vendor: "Mistral AI", share: 0.0164, confidence: "Low" },
  { region: "APAC", industry: "Retail / consumer / ecommerce", vendor: "Harvey", share: 0.0059, confidence: "Low" },
  { region: "APAC", industry: "Retail / consumer / ecommerce", vendor: "Rogo", share: 0, confidence: "Low" },
  { region: "APAC", industry: "Public sector / government", vendor: "IBM watsonx", share: 0.2365, confidence: "Medium" },
  { region: "APAC", industry: "Public sector / government", vendor: "OpenAI", share: 0.1892, confidence: "Medium" },
  { region: "APAC", industry: "Public sector / government", vendor: "Google DeepMind", share: 0.1755, confidence: "Medium" },
  { region: "APAC", industry: "Public sector / government", vendor: "Anthropic", share: 0.123, confidence: "Medium" },
  { region: "APAC", industry: "Public sector / government", vendor: "Cohere", share: 0.0986, confidence: "Medium-Low" },
  { region: "APAC", industry: "Public sector / government", vendor: "Mistral AI", share: 0.0821, confidence: "Medium-Low" },
  { region: "APAC", industry: "Public sector / government", vendor: "Perplexity", share: 0.0266, confidence: "Low-Medium" },
  { region: "APAC", industry: "Public sector / government", vendor: "Meta", share: 0.0211, confidence: "Low-Medium" },
  { region: "APAC", industry: "Public sector / government", vendor: "Writer", share: 0.0168, confidence: "Low-Medium" },
  { region: "APAC", industry: "Public sector / government", vendor: "Moveworks", share: 0.0148, confidence: "Medium-Low" },
  { region: "APAC", industry: "Public sector / government", vendor: "xAI", share: 0.0099, confidence: "Low" },
  { region: "APAC", industry: "Public sector / government", vendor: "Harvey", share: 0.0059, confidence: "Low" },
  { region: "APAC", industry: "Public sector / government", vendor: "Rogo", share: 0, confidence: "Low" },
  { region: "APAC", industry: "Education / research / media", vendor: "OpenAI", share: 0.367, confidence: "Medium" },
  { region: "APAC", industry: "Education / research / media", vendor: "Google DeepMind", share: 0.2335, confidence: "Medium" },
  { region: "APAC", industry: "Education / research / media", vendor: "Anthropic", share: 0.151, confidence: "Medium" },
  { region: "APAC", industry: "Education / research / media", vendor: "Perplexity", share: 0.0796, confidence: "Low-Medium" },
  { region: "APAC", industry: "Education / research / media", vendor: "Writer", share: 0.0418, confidence: "Low-Medium" },
  { region: "APAC", industry: "Education / research / media", vendor: "Meta", share: 0.0351, confidence: "Low-Medium" },
  { region: "APAC", industry: "Education / research / media", vendor: "Cohere", share: 0.0246, confidence: "Low" },
  { region: "APAC", industry: "Education / research / media", vendor: "Mistral AI", share: 0.0246, confidence: "Low" },
  { region: "APAC", industry: "Education / research / media", vendor: "xAI", share: 0.0197, confidence: "Low" },
  { region: "APAC", industry: "Education / research / media", vendor: "IBM watsonx", share: 0.0098, confidence: "Low" },
  { region: "APAC", industry: "Education / research / media", vendor: "Moveworks", share: 0.0074, confidence: "Medium-Low" },
  { region: "APAC", industry: "Education / research / media", vendor: "Harvey", share: 0.0059, confidence: "Low" },
  { region: "APAC", industry: "Education / research / media", vendor: "Rogo", share: 0, confidence: "Low" },
  { region: "Latin America", industry: "Technology / software", vendor: "OpenAI", share: 0.2813, confidence: "Medium" },
  { region: "Latin America", industry: "Technology / software", vendor: "Google DeepMind", share: 0.2457, confidence: "Medium" },
  { region: "Latin America", industry: "Technology / software", vendor: "Anthropic", share: 0.2359, confidence: "Medium" },
  { region: "Latin America", industry: "Technology / software", vendor: "Meta", share: 0.0908, confidence: "Low-Medium" },
  { region: "Latin America", industry: "Technology / software", vendor: "Perplexity", share: 0.0397, confidence: "Low-Medium" },
  { region: "Latin America", industry: "Technology / software", vendor: "xAI", share: 0.0298, confidence: "Low" },
  { region: "Latin America", industry: "Technology / software", vendor: "Mistral AI", share: 0.0199, confidence: "Low" },
  { region: "Latin America", industry: "Technology / software", vendor: "Writer", share: 0.0199, confidence: "Low-Medium" },
  { region: "Latin America", industry: "Technology / software", vendor: "Cohere", share: 0.0099, confidence: "Low" },
  { region: "Latin America", industry: "Technology / software", vendor: "Moveworks", share: 0.0099, confidence: "Medium-Low" },
  { region: "Latin America", industry: "Technology / software", vendor: "Rogo", share: 0.0099, confidence: "Low" },
  { region: "Latin America", industry: "Technology / software", vendor: "IBM watsonx", share: 0.0074, confidence: "Low" },
  { region: "Latin America", industry: "Technology / software", vendor: "Harvey", share: 0, confidence: "Low" },
  { region: "Latin America", industry: "Financial services", vendor: "OpenAI", share: 0.2864, confidence: "Medium" },
  { region: "Latin America", industry: "Financial services", vendor: "Google DeepMind", share: 0.2316, confidence: "Medium" },
  { region: "Latin America", industry: "Financial services", vendor: "Anthropic", share: 0.1641, confidence: "Medium" },
  { region: "Latin America", industry: "Financial services", vendor: "Rogo", share: 0.0793, confidence: "Medium" },
  { region: "Latin America", industry: "Financial services", vendor: "IBM watsonx", share: 0.0669, confidence: "Medium" },
  { region: "Latin America", industry: "Financial services", vendor: "Perplexity", share: 0.0495, confidence: "Low-Medium" },
  { region: "Latin America", industry: "Financial services", vendor: "Meta", share: 0.034, confidence: "Low-Medium" },
  { region: "Latin America", industry: "Financial services", vendor: "Cohere", share: 0.0248, confidence: "Medium-Low" },
  { region: "Latin America", industry: "Financial services", vendor: "Mistral AI", share: 0.0198, confidence: "Low" },
  { region: "Latin America", industry: "Financial services", vendor: "Writer", share: 0.0198, confidence: "Low-Medium" },
  { region: "Latin America", industry: "Financial services", vendor: "xAI", share: 0.0099, confidence: "Low" },
  { region: "Latin America", industry: "Financial services", vendor: "Moveworks", share: 0.0099, confidence: "Medium-Low" },
  { region: "Latin America", industry: "Financial services", vendor: "Harvey", share: 0.004, confidence: "Low" },
  { region: "Latin America", industry: "Legal", vendor: "OpenAI", share: 0.2621, confidence: "Medium" },
  { region: "Latin America", industry: "Legal", vendor: "Harvey", share: 0.1799, confidence: "High" },
  { region: "Latin America", industry: "Legal", vendor: "Google DeepMind", share: 0.159, confidence: "Medium" },
  { region: "Latin America", industry: "Legal", vendor: "Anthropic", share: 0.1388, confidence: "Medium" },
  { region: "Latin America", industry: "Legal", vendor: "Perplexity", share: 0.0642, confidence: "Low-Medium" },
  { region: "Latin America", industry: "Legal", vendor: "Writer", share: 0.0578, confidence: "Low-Medium" },
  { region: "Latin America", industry: "Legal", vendor: "Meta", share: 0.044, confidence: "Low-Medium" },
  { region: "Latin America", industry: "Legal", vendor: "Mistral AI", share: 0.0428, confidence: "Medium-Low" },
  { region: "Latin America", industry: "Legal", vendor: "IBM watsonx", share: 0.0193, confidence: "Low" },
  { region: "Latin America", industry: "Legal", vendor: "Cohere", share: 0.0128, confidence: "Low" },
  { region: "Latin America", industry: "Legal", vendor: "xAI", share: 0.0128, confidence: "Low" },
  { region: "Latin America", industry: "Legal", vendor: "Moveworks", share: 0.0064, confidence: "Medium-Low" },
  { region: "Latin America", industry: "Legal", vendor: "Rogo", share: 0, confidence: "Low" },
  { region: "Latin America", industry: "Professional services / consulting", vendor: "OpenAI", share: 0.3272, confidence: "Medium" },
  { region: "Latin America", industry: "Professional services / consulting", vendor: "Google DeepMind", share: 0.2268, confidence: "Medium" },
  { region: "Latin America", industry: "Professional services / consulting", vendor: "Anthropic", share: 0.1856, confidence: "Medium" },
  { region: "Latin America", industry: "Professional services / consulting", vendor: "Perplexity", share: 0.0619, confidence: "Low-Medium" },
  { region: "Latin America", industry: "Professional services / consulting", vendor: "Writer", share: 0.0515, confidence: "Low-Medium" },
  { region: "Latin America", industry: "Professional services / consulting", vendor: "Meta", share: 0.0353, confidence: "Low-Medium" },
  { region: "Latin America", industry: "Professional services / consulting", vendor: "IBM watsonx", share: 0.0309, confidence: "Low" },
  { region: "Latin America", industry: "Professional services / consulting", vendor: "xAI", share: 0.0206, confidence: "Low" },
  { region: "Latin America", industry: "Professional services / consulting", vendor: "Harvey", share: 0.0206, confidence: "Low" },
  { region: "Latin America", industry: "Professional services / consulting", vendor: "Moveworks", share: 0.0155, confidence: "Medium-Low" },
  { region: "Latin America", industry: "Professional services / consulting", vendor: "Mistral AI", share: 0.0137, confidence: "Low" },
  { region: "Latin America", industry: "Professional services / consulting", vendor: "Cohere", share: 0.0103, confidence: "Low" },
  { region: "Latin America", industry: "Professional services / consulting", vendor: "Rogo", share: 0, confidence: "Low" },
  { region: "Latin America", industry: "Healthcare / life sciences", vendor: "OpenAI", share: 0.3431, confidence: "Medium" },
  { region: "Latin America", industry: "Healthcare / life sciences", vendor: "Google DeepMind", share: 0.2359, confidence: "Medium" },
  { region: "Latin America", industry: "Healthcare / life sciences", vendor: "Anthropic", share: 0.1598, confidence: "Medium" },
  { region: "Latin America", industry: "Healthcare / life sciences", vendor: "IBM watsonx", share: 0.053, confidence: "Medium" },
  { region: "Latin America", industry: "Healthcare / life sciences", vendor: "Perplexity", share: 0.0404, confidence: "Low-Medium" },
  { region: "Latin America", industry: "Healthcare / life sciences", vendor: "Meta", share: 0.0346, confidence: "Low-Medium" },
  { region: "Latin America", industry: "Healthcare / life sciences", vendor: "Writer", share: 0.0303, confidence: "Low-Medium" },
  { region: "Latin America", industry: "Healthcare / life sciences", vendor: "Cohere", share: 0.0202, confidence: "Low" },
  { region: "Latin America", industry: "Healthcare / life sciences", vendor: "Mistral AI", share: 0.0202, confidence: "Low" },
  { region: "Latin America", industry: "Healthcare / life sciences", vendor: "xAI", share: 0.0202, confidence: "Low" },
  { region: "Latin America", industry: "Healthcare / life sciences", vendor: "Rogo", share: 0.0202, confidence: "Low" },
  { region: "Latin America", industry: "Healthcare / life sciences", vendor: "Harvey", share: 0.0121, confidence: "Low" },
  { region: "Latin America", industry: "Healthcare / life sciences", vendor: "Moveworks", share: 0.0101, confidence: "Medium-Low" },
  { region: "Latin America", industry: "Manufacturing / industrials", vendor: "OpenAI", share: 0.3477, confidence: "Medium" },
  { region: "Latin America", industry: "Manufacturing / industrials", vendor: "Google DeepMind", share: 0.2722, confidence: "Medium" },
  { region: "Latin America", industry: "Manufacturing / industrials", vendor: "Anthropic", share: 0.1283, confidence: "Medium" },
  { region: "Latin America", industry: "Manufacturing / industrials", vendor: "IBM watsonx", share: 0.0594, confidence: "Low" },
  { region: "Latin America", industry: "Manufacturing / industrials", vendor: "Meta", share: 0.0566, confidence: "Low-Medium" },
  { region: "Latin America", industry: "Manufacturing / industrials", vendor: "Mistral AI", share: 0.033, confidence: "Medium-Low" },
  { region: "Latin America", industry: "Manufacturing / industrials", vendor: "Perplexity", share: 0.0297, confidence: "Low-Medium" },
  { region: "Latin America", industry: "Manufacturing / industrials", vendor: "xAI", share: 0.0198, confidence: "Low" },
  { region: "Latin America", industry: "Manufacturing / industrials", vendor: "Writer", share: 0.0198, confidence: "Low-Medium" },
  { region: "Latin America", industry: "Manufacturing / industrials", vendor: "Cohere", share: 0.0148, confidence: "Low" },
  { region: "Latin America", industry: "Manufacturing / industrials", vendor: "Moveworks", share: 0.0148, confidence: "Medium-Low" },
  { region: "Latin America", industry: "Manufacturing / industrials", vendor: "Harvey", share: 0.004, confidence: "Low" },
  { region: "Latin America", industry: "Manufacturing / industrials", vendor: "Rogo", share: 0, confidence: "Low" },
  { region: "Latin America", industry: "Retail / consumer / ecommerce", vendor: "OpenAI", share: 0.3433, confidence: "Medium" },
  { region: "Latin America", industry: "Retail / consumer / ecommerce", vendor: "Google DeepMind", share: 0.2864, confidence: "Medium" },
  { region: "Latin America", industry: "Retail / consumer / ecommerce", vendor: "Anthropic", share: 0.1091, confidence: "Medium" },
  { region: "Latin America", industry: "Retail / consumer / ecommerce", vendor: "Meta", share: 0.0649, confidence: "Low-Medium" },
  { region: "Latin America", industry: "Retail / consumer / ecommerce", vendor: "Perplexity", share: 0.0473, confidence: "Low-Medium" },
  { region: "Latin America", industry: "Retail / consumer / ecommerce", vendor: "xAI", share: 0.0379, confidence: "Low" },
  { region: "Latin America", industry: "Retail / consumer / ecommerce", vendor: "Writer", share: 0.0379, confidence: "Low-Medium" },
  { region: "Latin America", industry: "Retail / consumer / ecommerce", vendor: "IBM watsonx", share: 0.0284, confidence: "Low" },
  { region: "Latin America", industry: "Retail / consumer / ecommerce", vendor: "Moveworks", share: 0.0189, confidence: "Medium-Low" },
  { region: "Latin America", industry: "Retail / consumer / ecommerce", vendor: "Mistral AI", share: 0.0126, confidence: "Low" },
  { region: "Latin America", industry: "Retail / consumer / ecommerce", vendor: "Cohere", share: 0.0095, confidence: "Low" },
  { region: "Latin America", industry: "Retail / consumer / ecommerce", vendor: "Harvey", share: 0.0038, confidence: "Low" },
  { region: "Latin America", industry: "Retail / consumer / ecommerce", vendor: "Rogo", share: 0, confidence: "Low" },
  { region: "Latin America", industry: "Public sector / government", vendor: "Google DeepMind", share: 0.2269, confidence: "Medium" },
  { region: "Latin America", industry: "Public sector / government", vendor: "OpenAI", share: 0.2245, confidence: "Medium" },
  { region: "Latin America", industry: "Public sector / government", vendor: "IBM watsonx", share: 0.1981, confidence: "Medium" },
  { region: "Latin America", industry: "Public sector / government", vendor: "Anthropic", share: 0.103, confidence: "Medium" },
  { region: "Latin America", industry: "Public sector / government", vendor: "Mistral AI", share: 0.0734, confidence: "Medium-Low" },
  { region: "Latin America", industry: "Public sector / government", vendor: "Cohere", share: 0.044, confidence: "Medium-Low" },
  { region: "Latin America", industry: "Public sector / government", vendor: "Meta", share: 0.0377, confidence: "Low-Medium" },
  { region: "Latin America", industry: "Public sector / government", vendor: "Perplexity", share: 0.033, confidence: "Low-Medium" },
  { region: "Latin America", industry: "Public sector / government", vendor: "xAI", share: 0.022, confidence: "Low" },
  { region: "Latin America", industry: "Public sector / government", vendor: "Writer", share: 0.022, confidence: "Low-Medium" },
  { region: "Latin America", industry: "Public sector / government", vendor: "Moveworks", share: 0.011, confidence: "Medium-Low" },
  { region: "Latin America", industry: "Public sector / government", vendor: "Harvey", share: 0.0044, confidence: "Low" },
  { region: "Latin America", industry: "Public sector / government", vendor: "Rogo", share: 0, confidence: "Low" },
  { region: "Latin America", industry: "Education / research / media", vendor: "OpenAI", share: 0.3705, confidence: "Medium" },
  { region: "Latin America", industry: "Education / research / media", vendor: "Google DeepMind", share: 0.2569, confidence: "Medium" },
  { region: "Latin America", industry: "Education / research / media", vendor: "Anthropic", share: 0.1076, confidence: "Medium" },
  { region: "Latin America", industry: "Education / research / media", vendor: "Perplexity", share: 0.0841, confidence: "Low-Medium" },
  { region: "Latin America", industry: "Education / research / media", vendor: "Meta", share: 0.0534, confidence: "Low-Medium" },
  { region: "Latin America", industry: "Education / research / media", vendor: "Writer", share: 0.0467, confidence: "Low-Medium" },
  { region: "Latin America", industry: "Education / research / media", vendor: "xAI", share: 0.0374, confidence: "Low" },
  { region: "Latin America", industry: "Education / research / media", vendor: "Mistral AI", share: 0.0187, confidence: "Low" },
  { region: "Latin America", industry: "Education / research / media", vendor: "Cohere", share: 0.0093, confidence: "Low" },
  { region: "Latin America", industry: "Education / research / media", vendor: "IBM watsonx", share: 0.007, confidence: "Low" },
  { region: "Latin America", industry: "Education / research / media", vendor: "Moveworks", share: 0.0047, confidence: "Medium-Low" },
  { region: "Latin America", industry: "Education / research / media", vendor: "Harvey", share: 0.0037, confidence: "Low" },
  { region: "Latin America", industry: "Education / research / media", vendor: "Rogo", share: 0, confidence: "Low" },
  { region: "Middle East & Africa", industry: "Technology / software", vendor: "OpenAI", share: 0.266, confidence: "Medium" },
  { region: "Middle East & Africa", industry: "Technology / software", vendor: "Anthropic", share: 0.2528, confidence: "Medium" },
  { region: "Middle East & Africa", industry: "Technology / software", vendor: "Google DeepMind", share: 0.2155, confidence: "Medium" },
  { region: "Middle East & Africa", industry: "Technology / software", vendor: "Cohere", share: 0.0532, confidence: "Medium-Low" },
  { region: "Middle East & Africa", industry: "Technology / software", vendor: "Mistral AI", share: 0.0532, confidence: "Low" },
  { region: "Middle East & Africa", industry: "Technology / software", vendor: "Meta", share: 0.0486, confidence: "Low-Medium" },
  { region: "Middle East & Africa", industry: "Technology / software", vendor: "IBM watsonx", share: 0.0266, confidence: "Medium" },
  { region: "Middle East & Africa", industry: "Technology / software", vendor: "Perplexity", share: 0.0255, confidence: "Low-Medium" },
  { region: "Middle East & Africa", industry: "Technology / software", vendor: "Writer", share: 0.0213, confidence: "Low-Medium" },
  { region: "Middle East & Africa", industry: "Technology / software", vendor: "xAI", share: 0.016, confidence: "Low" },
  { region: "Middle East & Africa", industry: "Technology / software", vendor: "Moveworks", share: 0.0106, confidence: "Medium-Low" },
  { region: "Middle East & Africa", industry: "Technology / software", vendor: "Rogo", share: 0.0106, confidence: "Low" },
  { region: "Middle East & Africa", industry: "Technology / software", vendor: "Harvey", share: 0, confidence: "Low" },
  { region: "Middle East & Africa", industry: "Financial services", vendor: "OpenAI", share: 0.2157, confidence: "Medium" },
  { region: "Middle East & Africa", industry: "Financial services", vendor: "IBM watsonx", share: 0.1904, confidence: "Medium" },
  { region: "Middle East & Africa", industry: "Financial services", vendor: "Google DeepMind", share: 0.1618, confidence: "Medium" },
  { region: "Middle East & Africa", industry: "Financial services", vendor: "Anthropic", share: 0.1401, confidence: "Medium" },
  { region: "Middle East & Africa", industry: "Financial services", vendor: "Cohere", share: 0.1058, confidence: "Medium-Low" },
  { region: "Middle East & Africa", industry: "Financial services", vendor: "Rogo", share: 0.0677, confidence: "Medium" },
  { region: "Middle East & Africa", industry: "Financial services", vendor: "Mistral AI", share: 0.0423, confidence: "Low" },
  { region: "Middle East & Africa", industry: "Financial services", vendor: "Perplexity", share: 0.0254, confidence: "Low-Medium" },
  { region: "Middle East & Africa", industry: "Financial services", vendor: "Writer", share: 0.0169, confidence: "Low-Medium" },
  { region: "Middle East & Africa", industry: "Financial services", vendor: "Meta", share: 0.0145, confidence: "Low-Medium" },
  { region: "Middle East & Africa", industry: "Financial services", vendor: "Moveworks", share: 0.0085, confidence: "Medium-Low" },
  { region: "Middle East & Africa", industry: "Financial services", vendor: "Harvey", share: 0.0068, confidence: "Low" },
  { region: "Middle East & Africa", industry: "Financial services", vendor: "xAI", share: 0.0042, confidence: "Low" },
  { region: "Middle East & Africa", industry: "Legal", vendor: "Harvey", share: 0.2933, confidence: "High" },
  { region: "Middle East & Africa", industry: "Legal", vendor: "OpenAI", share: 0.1885, confidence: "Medium" },
  { region: "Middle East & Africa", industry: "Legal", vendor: "Anthropic", share: 0.1131, confidence: "Medium" },
  { region: "Middle East & Africa", industry: "Legal", vendor: "Google DeepMind", share: 0.1061, confidence: "Medium" },
  { region: "Middle East & Africa", industry: "Legal", vendor: "Mistral AI", share: 0.0873, confidence: "Medium-Low" },
  { region: "Middle East & Africa", industry: "Legal", vendor: "Cohere", share: 0.0524, confidence: "Medium-Low" },
  { region: "Middle East & Africa", industry: "Legal", vendor: "IBM watsonx", share: 0.0524, confidence: "Medium" },
  { region: "Middle East & Africa", industry: "Legal", vendor: "Writer", share: 0.0471, confidence: "Low-Medium" },
  { region: "Middle East & Africa", industry: "Legal", vendor: "Perplexity", share: 0.0314, confidence: "Low-Medium" },
  { region: "Middle East & Africa", industry: "Legal", vendor: "Meta", share: 0.018, confidence: "Low-Medium" },
  { region: "Middle East & Africa", industry: "Legal", vendor: "xAI", share: 0.0052, confidence: "Low" },
  { region: "Middle East & Africa", industry: "Legal", vendor: "Moveworks", share: 0.0052, confidence: "Medium-Low" },
  { region: "Middle East & Africa", industry: "Legal", vendor: "Rogo", share: 0, confidence: "Low" },
  { region: "Middle East & Africa", industry: "Professional services / consulting", vendor: "OpenAI", share: 0.2824, confidence: "Medium" },
  { region: "Middle East & Africa", industry: "Professional services / consulting", vendor: "Anthropic", share: 0.1815, confidence: "Medium" },
  { region: "Middle East & Africa", industry: "Professional services / consulting", vendor: "Google DeepMind", share: 0.1815, confidence: "Medium" },
  { region: "Middle East & Africa", industry: "Professional services / consulting", vendor: "IBM watsonx", share: 0.1009, confidence: "Medium" },
  { region: "Middle East & Africa", industry: "Professional services / consulting", vendor: "Cohere", share: 0.0504, confidence: "Medium-Low" },
  { region: "Middle East & Africa", industry: "Professional services / consulting", vendor: "Writer", share: 0.0504, confidence: "Low-Medium" },
  { region: "Middle East & Africa", industry: "Professional services / consulting", vendor: "Harvey", share: 0.0403, confidence: "Low" },
  { region: "Middle East & Africa", industry: "Professional services / consulting", vendor: "Perplexity", share: 0.0363, confidence: "Low-Medium" },
  { region: "Middle East & Africa", industry: "Professional services / consulting", vendor: "Mistral AI", share: 0.0336, confidence: "Low" },
  { region: "Middle East & Africa", industry: "Professional services / consulting", vendor: "Meta", share: 0.0173, confidence: "Low-Medium" },
  { region: "Middle East & Africa", industry: "Professional services / consulting", vendor: "Moveworks", share: 0.0151, confidence: "Medium-Low" },
  { region: "Middle East & Africa", industry: "Professional services / consulting", vendor: "xAI", share: 0.0101, confidence: "Low" },
  { region: "Middle East & Africa", industry: "Professional services / consulting", vendor: "Rogo", share: 0, confidence: "Low" },
  { region: "Middle East & Africa", industry: "Healthcare / life sciences", vendor: "OpenAI", share: 0.2703, confidence: "Medium" },
  { region: "Middle East & Africa", industry: "Healthcare / life sciences", vendor: "Google DeepMind", share: 0.1723, confidence: "Medium" },
  { region: "Middle East & Africa", industry: "Healthcare / life sciences", vendor: "IBM watsonx", share: 0.1577, confidence: "Medium" },
  { region: "Middle East & Africa", industry: "Healthcare / life sciences", vendor: "Anthropic", share: 0.1427, confidence: "Medium" },
  { region: "Middle East & Africa", industry: "Healthcare / life sciences", vendor: "Cohere", share: 0.0901, confidence: "Medium-Low" },
  { region: "Middle East & Africa", industry: "Healthcare / life sciences", vendor: "Mistral AI", share: 0.0451, confidence: "Low" },
  { region: "Middle East & Africa", industry: "Healthcare / life sciences", vendor: "Writer", share: 0.027, confidence: "Low-Medium" },
  { region: "Middle East & Africa", industry: "Healthcare / life sciences", vendor: "Perplexity", share: 0.0216, confidence: "Low-Medium" },
  { region: "Middle East & Africa", industry: "Healthcare / life sciences", vendor: "Harvey", share: 0.0216, confidence: "Low" },
  { region: "Middle East & Africa", industry: "Healthcare / life sciences", vendor: "Rogo", share: 0.018, confidence: "Low" },
  { region: "Middle East & Africa", industry: "Healthcare / life sciences", vendor: "Meta", share: 0.0154, confidence: "Low-Medium" },
  { region: "Middle East & Africa", industry: "Healthcare / life sciences", vendor: "xAI", share: 0.009, confidence: "Low" },
  { region: "Middle East & Africa", industry: "Healthcare / life sciences", vendor: "Moveworks", share: 0.009, confidence: "Medium-Low" },
  { region: "Middle East & Africa", industry: "Manufacturing / industrials", vendor: "OpenAI", share: 0.2762, confidence: "Medium" },
  { region: "Middle East & Africa", industry: "Manufacturing / industrials", vendor: "Google DeepMind", share: 0.2004, confidence: "Medium" },
  { region: "Middle East & Africa", industry: "Manufacturing / industrials", vendor: "IBM watsonx", share: 0.1782, confidence: "Medium" },
  { region: "Middle East & Africa", industry: "Manufacturing / industrials", vendor: "Anthropic", share: 0.1155, confidence: "Medium" },
  { region: "Middle East & Africa", industry: "Manufacturing / industrials", vendor: "Mistral AI", share: 0.0742, confidence: "Medium-Low" },
  { region: "Middle East & Africa", industry: "Manufacturing / industrials", vendor: "Cohere", share: 0.0668, confidence: "Medium-Low" },
  { region: "Middle East & Africa", industry: "Manufacturing / industrials", vendor: "Meta", share: 0.0255, confidence: "Low-Medium" },
  { region: "Middle East & Africa", industry: "Manufacturing / industrials", vendor: "Writer", share: 0.0178, confidence: "Low-Medium" },
  { region: "Middle East & Africa", industry: "Manufacturing / industrials", vendor: "Perplexity", share: 0.016, confidence: "Low-Medium" },
  { region: "Middle East & Africa", industry: "Manufacturing / industrials", vendor: "Moveworks", share: 0.0134, confidence: "Medium-Low" },
  { region: "Middle East & Africa", industry: "Manufacturing / industrials", vendor: "xAI", share: 0.0089, confidence: "Low" },
  { region: "Middle East & Africa", industry: "Manufacturing / industrials", vendor: "Harvey", share: 0.0071, confidence: "Low" },
  { region: "Middle East & Africa", industry: "Manufacturing / industrials", vendor: "Rogo", share: 0, confidence: "Low" },
  { region: "Middle East & Africa", industry: "Retail / consumer / ecommerce", vendor: "OpenAI", share: 0.3142, confidence: "Medium" },
  { region: "Middle East & Africa", industry: "Retail / consumer / ecommerce", vendor: "Google DeepMind", share: 0.243, confidence: "Medium" },
  { region: "Middle East & Africa", industry: "Retail / consumer / ecommerce", vendor: "Anthropic", share: 0.1131, confidence: "Medium" },
  { region: "Middle East & Africa", industry: "Retail / consumer / ecommerce", vendor: "IBM watsonx", share: 0.0982, confidence: "Medium" },
  { region: "Middle East & Africa", industry: "Retail / consumer / ecommerce", vendor: "Cohere", share: 0.0491, confidence: "Medium-Low" },
  { region: "Middle East & Africa", industry: "Retail / consumer / ecommerce", vendor: "Writer", share: 0.0393, confidence: "Low-Medium" },
  { region: "Middle East & Africa", industry: "Retail / consumer / ecommerce", vendor: "Meta", share: 0.0337, confidence: "Low-Medium" },
  { region: "Middle East & Africa", industry: "Retail / consumer / ecommerce", vendor: "Mistral AI", share: 0.0327, confidence: "Low" },
  { region: "Middle East & Africa", industry: "Retail / consumer / ecommerce", vendor: "Perplexity", share: 0.0295, confidence: "Low-Medium" },
  { region: "Middle East & Africa", industry: "Retail / consumer / ecommerce", vendor: "xAI", share: 0.0196, confidence: "Low" },
  { region: "Middle East & Africa", industry: "Retail / consumer / ecommerce", vendor: "Moveworks", share: 0.0196, confidence: "Medium-Low" },
  { region: "Middle East & Africa", industry: "Retail / consumer / ecommerce", vendor: "Harvey", share: 0.0079, confidence: "Low" },
  { region: "Middle East & Africa", industry: "Retail / consumer / ecommerce", vendor: "Rogo", share: 0, confidence: "Low" },
  { region: "Middle East & Africa", industry: "Public sector / government", vendor: "IBM watsonx", share: 0.4021, confidence: "Medium" },
  { region: "Middle East & Africa", industry: "Public sector / government", vendor: "Cohere", share: 0.134, confidence: "Medium-Low" },
  { region: "Middle East & Africa", industry: "Public sector / government", vendor: "OpenAI", share: 0.1206, confidence: "Medium" },
  { region: "Middle East & Africa", industry: "Public sector / government", vendor: "Google DeepMind", share: 0.1131, confidence: "Medium" },
  { region: "Middle East & Africa", industry: "Public sector / government", vendor: "Mistral AI", share: 0.1117, confidence: "Medium-Low" },
  { region: "Middle East & Africa", industry: "Public sector / government", vendor: "Anthropic", share: 0.0627, confidence: "Medium" },
  { region: "Middle East & Africa", industry: "Public sector / government", vendor: "Writer", share: 0.0134, confidence: "Low-Medium" },
  { region: "Middle East & Africa", industry: "Public sector / government", vendor: "Perplexity", share: 0.0121, confidence: "Low-Medium" },
  { region: "Middle East & Africa", industry: "Public sector / government", vendor: "Meta", share: 0.0115, confidence: "Low-Medium" },
  { region: "Middle East & Africa", industry: "Public sector / government", vendor: "xAI", share: 0.0067, confidence: "Low" },
  { region: "Middle East & Africa", industry: "Public sector / government", vendor: "Moveworks", share: 0.0067, confidence: "Medium-Low" },
  { region: "Middle East & Africa", industry: "Public sector / government", vendor: "Harvey", share: 0.0054, confidence: "Low" },
  { region: "Middle East & Africa", industry: "Public sector / government", vendor: "Rogo", share: 0, confidence: "Low" },
  { region: "Middle East & Africa", industry: "Education / research / media", vendor: "OpenAI", share: 0.3569, confidence: "Medium" },
  { region: "Middle East & Africa", industry: "Education / research / media", vendor: "Google DeepMind", share: 0.2294, confidence: "Medium" },
  { region: "Middle East & Africa", industry: "Education / research / media", vendor: "Anthropic", share: 0.1175, confidence: "Medium" },
  { region: "Middle East & Africa", industry: "Education / research / media", vendor: "Perplexity", share: 0.0551, confidence: "Low-Medium" },
  { region: "Middle East & Africa", industry: "Education / research / media", vendor: "Cohere", share: 0.051, confidence: "Medium-Low" },
  { region: "Middle East & Africa", industry: "Education / research / media", vendor: "Mistral AI", share: 0.051, confidence: "Low" },
  { region: "Middle East & Africa", industry: "Education / research / media", vendor: "Writer", share: 0.051, confidence: "Low-Medium" },
  { region: "Middle East & Africa", industry: "Education / research / media", vendor: "Meta", share: 0.0291, confidence: "Low-Medium" },
  { region: "Middle East & Africa", industry: "Education / research / media", vendor: "IBM watsonx", share: 0.0255, confidence: "Medium" },
  { region: "Middle East & Africa", industry: "Education / research / media", vendor: "xAI", share: 0.0204, confidence: "Low" },
  { region: "Middle East & Africa", industry: "Education / research / media", vendor: "Harvey", share: 0.0082, confidence: "Low" },
  { region: "Middle East & Africa", industry: "Education / research / media", vendor: "Moveworks", share: 0.0051, confidence: "Medium-Low" },
  { region: "Middle East & Africa", industry: "Education / research / media", vendor: "Rogo", share: 0, confidence: "Low" },
];

export const COMPANY_SIZE_SHARES: CompanySizeRow[] = [
  { vendor: "Anthropic", large: 0.46, sme: 0.26 },
  { vendor: "Google DeepMind", large: 0.23, sme: 0.17 },
  { vendor: "OpenAI", large: 0.18, sme: 0.44 },
  { vendor: "IBM watsonx", large: 0.04, sme: 0.01 },
  { vendor: "Cohere", large: 0.03, sme: 0.01 },
  { vendor: "Mistral AI", large: 0.02, sme: 0.02 },
  { vendor: "Meta", large: 0.01, sme: 0.005 },
  { vendor: "Writer", large: 0.01, sme: 0.03 },
  { vendor: "Harvey", large: 0.01, sme: 0.005 },
  { vendor: "Moveworks", large: 0.01, sme: 0.005 },
  { vendor: "Perplexity", large: 0.005, sme: 0.05 },
  { vendor: "Rogo", large: 0.005, sme: 0.005 },
  { vendor: "xAI", large: 0.005, sme: 0.01 },
];

// ── Aggregation helper ──────────────────────────────────────────────
// Returns vendor-share pairs filtered by any subset of (regions, industries,
// companySize). Shares are averaged across matching segment cells, then
// optionally re-weighted by the vendor's company-size propensity, then
// renormalised to sum to 1. Each entry also includes the average confidence
// label across the contributing rows so the UI can flag thin-evidence cells.

const CONF_RANK: Record<ConfidenceLabel, number> = { "Low": 1, "Low-Medium": 2, "Medium-Low": 2, "Medium": 3, "High": 4 };
const CONF_LABEL: Record<number, ConfidenceLabel> = { 1: "Low", 2: "Low-Medium", 3: "Medium", 4: "High" };

export interface UptakeAggregateRow {
  vendor: string;
  share: number;          // 0..1, renormalised inside the filtered slice
  contributingCells: number;
  confidence: ConfidenceLabel;
}

export function aggregateUptake(opts: {
  regions?: Region[];
  industries?: Industry[];
  companySize?: CompanySize | null;
}): UptakeAggregateRow[] {
  const regions = opts.regions && opts.regions.length > 0 ? new Set(opts.regions) : null;
  const industries = opts.industries && opts.industries.length > 0 ? new Set(opts.industries) : null;
  const filtered = SEGMENT_SHARES.filter((r) => (!regions || regions.has(r.region)) && (!industries || industries.has(r.industry)));
  if (filtered.length === 0) return [];

  // Sum share + count contributing cells per vendor; track confidence rank average.
  const byVendor = new Map<string, { sum: number; cells: number; confSum: number }>();
  for (const r of filtered) {
    const cur = byVendor.get(r.vendor) ?? { sum: 0, cells: 0, confSum: 0 };
    cur.sum += r.share;
    cur.cells += 1;
    cur.confSum += CONF_RANK[r.confidence] ?? 2;
    byVendor.set(r.vendor, cur);
  }

  // Average share inside the slice → vendor mean share.
  const mean: { vendor: string; share: number; cells: number; conf: number }[] = [];
  for (const [vendor, v] of byVendor.entries()) {
    mean.push({ vendor, share: v.sum / v.cells, cells: v.cells, conf: v.confSum / v.cells });
  }

  // Optional company-size reweighting.
  if (opts.companySize) {
    const sizeMap = new Map(COMPANY_SIZE_SHARES.map((s) => [s.vendor, opts.companySize === "Large Enterprise" ? s.large : s.sme]));
    for (const m of mean) {
      const weight = sizeMap.get(m.vendor) ?? 0;
      m.share = m.share * weight;
    }
  }

  // Renormalise so the slice sums to 1 (so the UI shows share-within-this-cut).
  const total = mean.reduce((acc, m) => acc + m.share, 0);
  const out: UptakeAggregateRow[] = mean.map((m) => ({
    vendor: m.vendor,
    share: total > 0 ? m.share / total : 0,
    contributingCells: m.cells,
    confidence: CONF_LABEL[Math.round(m.conf)] ?? "Low-Medium",
  }));
  return out.sort((a, b) => b.share - a.share);
}

// Heatmap helper — returns share for one (region, industry, vendor) cell.
export function getCellShare(region: Region, industry: Industry, vendor: string): number {
  const row = SEGMENT_SHARES.find((r) => r.region === region && r.industry === industry && r.vendor === vendor);
  return row?.share ?? 0;
}
