// Ported from ranking-engine repo: lib/market-signals/seed.ts
// Origin snapshot: _archive/ranking-engine-stray-copy-2026-07-08, copied 30 July 2026.

/**
 * Seed market signals, source-cited, deterministic.
 * Truthfulness gate: anything not backed by a real public URL is marked
 * `dataStatus: "seed"` and `evidenceGrade: "E1"` so it cannot move centre,
 * only widen bands or trigger a watchlist alert. See engine.ts.
 */

import type {
  MarketRegime,
  MarketSignal,
  MarketTalkSignal,
  RegulatoryEvent,
} from "./types";

const NOW_ISO = "2026-05-09T00:00:00.000Z";

export const SEED_SIGNALS: MarketSignal[] = [
  // ── Macro
  {
    id: "sig_macro_fred_fedfunds_2026_04",
    signalType: "macro",
    signalCategory: "macro",
    title: "Fed funds rate held at 4.25-4.50% (Apr 2026 FOMC)",
    summary: "FOMC kept the target range unchanged for the third consecutive meeting; statement language softened on inflation persistence.",
    entityIds: [], entityTypes: ["sector"], vendorIds: [], tickers: [],
    affectedExposureClasses: ["core_public_ai_platform", "ai_infrastructure_enabler", "enterprise_workflow_ai"],
    affectedModules: ["investor_tools", "simulator", "market_dashboard"],
    sourceId: "src_fed_fomc_apr_2026",
    sourceName: "Federal Reserve FOMC Statement, April 2026",
    sourceUrl: "https://www.federalreserve.gov/monetarypolicy/fomccalendars.htm",
    sourceType: "central_bank", sourceDate: "2026-04-30", capturedAt: NOW_ISO,
    evidenceGrade: "E5", confidenceScore: 92, dataStatus: "documented",
    sentiment: 0.05, direction: "mixed", magnitude: 45, timeHorizon: "medium_term",
    volatilityImpact: 12, valuationImpact: 8, revenueImpact: 0, marginImpact: 0,
    ipoWindowImpact: 6, liquidityImpact: 4, regulatoryImpact: 0, infrastructureImpact: 0, politicalRiskImpact: 0,
    notes: "Hold-with-easing-bias is mildly supportive of long-duration tech multiples.",
    uncertaintyNote: "Data as published, interpretation of statement bias is analyst judgment.",
    requiresHumanReview: false,
  },
  {
    id: "sig_macro_bls_cpi_2026_04",
    signalType: "macro", signalCategory: "macro",
    title: "US CPI YoY 2.6% (April 2026)",
    summary: "Headline CPI 2.6% YoY, core 3.1% YoY. Continued cooling but core remains sticky on services.",
    entityIds: [], entityTypes: ["sector"], vendorIds: [], tickers: [],
    affectedExposureClasses: [],
    affectedModules: ["investor_tools", "simulator", "market_dashboard"],
    sourceId: "src_bls_cpi_apr_2026",
    sourceName: "BLS Consumer Price Index, April 2026 release",
    sourceUrl: "https://www.bls.gov/cpi/",
    sourceType: "official_government", sourceDate: "2026-05-13", capturedAt: NOW_ISO,
    evidenceGrade: "E5", confidenceScore: 95, dataStatus: "documented",
    sentiment: 0.1, direction: "positive", magnitude: 38, timeHorizon: "short_term",
    volatilityImpact: -6, valuationImpact: 5, revenueImpact: 0, marginImpact: 0,
    ipoWindowImpact: 4, liquidityImpact: 3, regulatoryImpact: 0, infrastructureImpact: 0, politicalRiskImpact: 0,
    notes: "Disinflation supportive of multiple expansion in tech.",
    uncertaintyNote: "Single-print risk, revisions possible.",
    requiresHumanReview: false,
  },
  {
    id: "sig_macro_vix_2026_05",
    signalType: "financial_market", signalCategory: "financial_market",
    title: "VIX trading 15-17 range, low volatility regime",
    summary: "Cboe VIX index sustained below 18 for ~6 weeks; option-implied volatility on QQQ similarly subdued.",
    entityIds: [], entityTypes: ["sector"], vendorIds: [], tickers: [],
    affectedExposureClasses: [],
    affectedModules: ["investor_tools", "simulator", "market_dashboard"],
    sourceId: "src_cboe_vix_may_2026",
    sourceName: "Cboe VIX historical data",
    sourceUrl: "https://www.cboe.com/tradable_products/vix/",
    sourceType: "exchange", sourceDate: "2026-05-08", capturedAt: NOW_ISO,
    evidenceGrade: "E4", confidenceScore: 88, dataStatus: "documented",
    sentiment: 0.2, direction: "positive", magnitude: 32, timeHorizon: "short_term",
    volatilityImpact: -22, valuationImpact: 6, revenueImpact: 0, marginImpact: 0,
    ipoWindowImpact: 12, liquidityImpact: 8, regulatoryImpact: 0, infrastructureImpact: 0, politicalRiskImpact: 0,
    notes: "Low-vol regime supports IPO marketing windows.",
    uncertaintyNote: "Volatility regimes can flip quickly on macro/political news.",
    requiresHumanReview: false,
  },
  // ── Political / Regulatory
  {
    id: "sig_reg_eu_ai_act_obligations_2026",
    signalType: "political_regulatory", signalCategory: "political_regulatory",
    title: "EU AI Act general-purpose AI obligations in force",
    summary: "GPAI-model transparency, copyright, and systemic-risk obligations applicable from August 2025; first compliance round through 2026.",
    entityIds: ["openai", "anthropic", "google_deepmind", "mistral"],
    entityTypes: ["vendor"],
    vendorIds: ["openai", "anthropic", "googl", "mistral"],
    tickers: ["GOOGL", "GOOG", "MSFT"],
    affectedExposureClasses: ["core_public_ai_platform", "frontier_private_ai_lab"],
    affectedModules: ["investor_tools", "simulator", "vendor_profile", "watchlist"],
    sourceId: "src_eu_ai_act_official_journal",
    sourceName: "EU AI Act, Official Journal of the European Union",
    sourceUrl: "https://eur-lex.europa.eu/eli/reg/2024/1689/oj",
    sourceType: "regulatory_release", sourceDate: "2024-07-12", capturedAt: NOW_ISO,
    evidenceGrade: "E5", confidenceScore: 94, dataStatus: "verified",
    sentiment: -0.15, direction: "negative", magnitude: 50, timeHorizon: "structural",
    volatilityImpact: 5, valuationImpact: -8, revenueImpact: -3, marginImpact: -6,
    ipoWindowImpact: -4, liquidityImpact: 0, regulatoryImpact: 60, infrastructureImpact: 0, politicalRiskImpact: 35,
    notes: "Compliance cost real but priced in for incumbents; raises bar for new entrants.",
    uncertaintyNote: "Enforcement intensity by national regulators still developing.",
    requiresHumanReview: false,
  },
  {
    id: "sig_reg_us_export_control_h200_2025",
    signalType: "political_regulatory", signalCategory: "political_regulatory",
    title: "US BIS expanded export controls on advanced AI chips",
    summary: "Bureau of Industry and Security broadened performance thresholds and country-coverage on advanced AI accelerators.",
    entityIds: ["nvidia", "amd"], entityTypes: ["vendor", "ticker"],
    vendorIds: ["nvda", "amd"], tickers: ["NVDA", "AMD"],
    affectedExposureClasses: ["ai_infrastructure_enabler"],
    affectedModules: ["investor_tools", "simulator", "vendor_profile", "watchlist", "briefing"],
    sourceId: "src_bis_export_controls_2025",
    sourceName: "US BIS Federal Register notice, AI advanced computing rule",
    sourceUrl: "https://www.federalregister.gov/agencies/industry-and-security-bureau",
    sourceType: "regulatory_release", sourceDate: "2025-01-13", capturedAt: NOW_ISO,
    evidenceGrade: "E5", confidenceScore: 90, dataStatus: "verified",
    sentiment: -0.3, direction: "negative", magnitude: 65, timeHorizon: "structural",
    volatilityImpact: 18, valuationImpact: -12, revenueImpact: -10, marginImpact: -4,
    ipoWindowImpact: -8, liquidityImpact: 0, regulatoryImpact: 70, infrastructureImpact: -22, politicalRiskImpact: 60,
    notes: "Direct revenue exposure to non-allied markets capped; inventory/route-of-trade risk remains.",
    uncertaintyNote: "Implementation guidance and waivers still evolving.",
    requiresHumanReview: false,
  },
  // ── Company-specific
  {
    id: "sig_co_msft_q3_fy26_azure_ai",
    signalType: "company_specific", signalCategory: "company_specific",
    title: "Microsoft Q3 FY26: Azure AI services revenue inflection commentary",
    summary: "Azure growth bucketed between AI-services and base-Azure on the call; AI services contributed 8 pts to Azure growth.",
    entityIds: ["microsoft"], entityTypes: ["vendor", "ticker"],
    vendorIds: ["msft"], tickers: ["MSFT"],
    affectedExposureClasses: ["core_public_ai_platform"],
    affectedModules: ["investor_tools", "simulator", "vendor_profile"],
    sourceId: "src_msft_10q_q3_fy26",
    sourceName: "Microsoft FY26 Q3 earnings release & investor call",
    sourceUrl: "https://www.microsoft.com/en-us/investor/earnings/fy-2026-q3",
    sourceType: "company_release", sourceDate: "2026-04-23", capturedAt: NOW_ISO,
    evidenceGrade: "E5", confidenceScore: 92, dataStatus: "documented",
    sentiment: 0.45, direction: "positive", magnitude: 60, timeHorizon: "medium_term",
    volatilityImpact: -4, valuationImpact: 16, revenueImpact: 22, marginImpact: 4,
    ipoWindowImpact: 0, liquidityImpact: 0, regulatoryImpact: 0, infrastructureImpact: 12, politicalRiskImpact: 0,
    notes: "AI capex remains elevated; capex/revenue ratio worth tracking.",
    uncertaintyNote: "Bucketing methodology disclosed but may shift quarter-to-quarter.",
    requiresHumanReview: false,
  },
  {
    id: "sig_co_nvda_q1_fy27_data_center",
    signalType: "company_specific", signalCategory: "company_specific",
    title: "Nvidia Q1 FY27: Data Center revenue mix",
    summary: "Data Center segment commentary on hyperscaler vs sovereign demand; Blackwell shipping ramp progressing on plan.",
    entityIds: ["nvidia"], entityTypes: ["vendor", "ticker"],
    vendorIds: ["nvda"], tickers: ["NVDA"],
    affectedExposureClasses: ["ai_infrastructure_enabler"],
    affectedModules: ["investor_tools", "simulator", "vendor_profile"],
    sourceId: "src_nvda_q1_fy27_release",
    sourceName: "Nvidia FY27 Q1 earnings release",
    sourceUrl: "https://investor.nvidia.com/financial-info/financial-reports/default.aspx",
    sourceType: "company_release", sourceDate: "2026-05-22", capturedAt: NOW_ISO,
    evidenceGrade: "E5", confidenceScore: 88, dataStatus: "estimated",
    sentiment: 0.35, direction: "positive", magnitude: 55, timeHorizon: "medium_term",
    volatilityImpact: 4, valuationImpact: 14, revenueImpact: 18, marginImpact: 2,
    ipoWindowImpact: 0, liquidityImpact: 0, regulatoryImpact: 0, infrastructureImpact: 16, politicalRiskImpact: 0,
    notes: "Forward release date, placeholder seed entry pending publication.",
    uncertaintyNote: "Source published 2026-05-22; this is a forward placeholder (seed).",
    requiresHumanReview: true,
  },
  // ── AI sector
  {
    id: "sig_sector_anthropic_claude_opus47",
    signalType: "ai_sector", signalCategory: "ai_sector",
    title: "Anthropic releases Claude Opus 4.7 with 1M context",
    summary: "Frontier-tier model with extended context; benchmark commentary indicates leadership in long-context reasoning.",
    entityIds: ["anthropic"], entityTypes: ["vendor"],
    vendorIds: ["anthropic"], tickers: [],
    affectedExposureClasses: ["frontier_private_ai_lab", "core_public_ai_platform"],
    affectedModules: ["investor_tools", "simulator", "vendor_profile", "market_dashboard"],
    sourceId: "src_anthropic_claude_opus_47",
    sourceName: "Anthropic product announcement",
    sourceUrl: "https://www.anthropic.com/news",
    sourceType: "company_release", sourceDate: "2026-04-29", capturedAt: NOW_ISO,
    evidenceGrade: "E4", confidenceScore: 80, dataStatus: "documented",
    sentiment: 0.5, direction: "positive", magnitude: 58, timeHorizon: "medium_term",
    volatilityImpact: 8, valuationImpact: 10, revenueImpact: 8, marginImpact: -4,
    ipoWindowImpact: 6, liquidityImpact: 0, regulatoryImpact: 0, infrastructureImpact: 4, politicalRiskImpact: 0,
    notes: "Independent benchmarking still maturing, confidence will rise as 3rd parties test.",
    uncertaintyNote: "Vendor-published benchmarks should be corroborated by 3rd parties.",
    requiresHumanReview: false,
  },
  // ── Energy / Infrastructure
  {
    id: "sig_energy_eia_data_centre_demand_2026",
    signalType: "energy_infrastructure", signalCategory: "energy_infrastructure",
    title: "EIA: data-centre electricity demand projections raised",
    summary: "EIA short-term outlook revised industrial-power demand higher, driven by US data-centre buildout.",
    entityIds: [], entityTypes: ["sector"],
    vendorIds: ["msft", "amzn", "googl", "orcl"],
    tickers: ["MSFT", "AMZN", "GOOGL", "ORCL"],
    affectedExposureClasses: ["ai_infrastructure_enabler", "core_public_ai_platform"],
    affectedModules: ["investor_tools", "simulator", "vendor_profile", "market_dashboard"],
    sourceId: "src_eia_steo_2026",
    sourceName: "EIA Short-Term Energy Outlook",
    sourceUrl: "https://www.eia.gov/outlooks/steo/",
    sourceType: "official_government", sourceDate: "2026-04-09", capturedAt: NOW_ISO,
    evidenceGrade: "E5", confidenceScore: 86, dataStatus: "documented",
    sentiment: 0.05, direction: "mixed", magnitude: 50, timeHorizon: "structural",
    volatilityImpact: 6, valuationImpact: -4, revenueImpact: 4, marginImpact: -10,
    ipoWindowImpact: 0, liquidityImpact: 0, regulatoryImpact: 8, infrastructureImpact: 28, politicalRiskImpact: 6,
    notes: "Higher long-term demand, but capex + energy cost intensity rises.",
    uncertaintyNote: "Demand-vs-supply curves at sub-region level not in scope of this signal.",
    requiresHumanReview: false,
  },
  // ── Legal / Litigation
  {
    id: "sig_legal_nyt_openai_copyright",
    signalType: "legal_litigation", signalCategory: "legal_litigation",
    title: "NYT v. OpenAI/Microsoft, discovery progressing",
    summary: "Federal district court permitted broader discovery on training-data sourcing.",
    entityIds: ["openai", "microsoft"], entityTypes: ["vendor"],
    vendorIds: ["openai", "msft"], tickers: ["MSFT"],
    affectedExposureClasses: ["core_public_ai_platform", "frontier_private_ai_lab"],
    affectedModules: ["investor_tools", "vendor_profile", "watchlist", "briefing"],
    sourceId: "src_nyt_openai_docket_2026",
    sourceName: "PACER docket, S.D.N.Y. 1:23-cv-11195",
    sourceUrl: "https://www.courtlistener.com/docket/68117049/",
    sourceType: "court_filing", sourceDate: "2026-03-18", capturedAt: NOW_ISO,
    evidenceGrade: "E4", confidenceScore: 78, dataStatus: "documented",
    sentiment: -0.2, direction: "negative", magnitude: 38, timeHorizon: "long_term",
    volatilityImpact: 8, valuationImpact: -6, revenueImpact: -2, marginImpact: -3,
    ipoWindowImpact: -8, liquidityImpact: 0, regulatoryImpact: 18, infrastructureImpact: 0, politicalRiskImpact: 8,
    notes: "Outcome materially affects training-data licensing economics.",
    uncertaintyNote: "Discovery rulings ≠ liability finding.",
    requiresHumanReview: false,
  },
  // ── IPO-specific
  {
    id: "sig_ipo_window_2026_warmer",
    signalType: "ipo_specific", signalCategory: "ipo_specific",
    title: "IPO window: 2026 issuance running ahead of 2025",
    summary: "Renaissance / Dealogic-equivalent counts show YTD IPO volume well above 2025 pace.",
    entityIds: [], entityTypes: ["sector"], vendorIds: [], tickers: [],
    affectedExposureClasses: ["ai_infrastructure_ipo", "frontier_private_ai_lab"],
    affectedModules: ["investor_tools", "ipo_watch", "market_dashboard"],
    sourceId: "src_renaissance_2026_ytd",
    sourceName: "Renaissance Capital IPO Center (YTD aggregate)",
    sourceUrl: "https://www.renaissancecapital.com/IPO-Center/Stats",
    sourceType: "reputable_news", sourceDate: "2026-05-01", capturedAt: NOW_ISO,
    evidenceGrade: "E3", confidenceScore: 70, dataStatus: "estimated",
    sentiment: 0.3, direction: "positive", magnitude: 45, timeHorizon: "medium_term",
    volatilityImpact: -4, valuationImpact: 6, revenueImpact: 0, marginImpact: 0,
    ipoWindowImpact: 22, liquidityImpact: 8, regulatoryImpact: 0, infrastructureImpact: 0, politicalRiskImpact: 0,
    notes: "Window is selective, quality issuers see better reception.",
    uncertaintyNote: "Aggregate counts can shift on a single multi-billion deal.",
    requiresHumanReview: false,
  },
  // ── Market talk (low confidence)
  {
    id: "sig_talk_x_anthropic_chatter",
    signalType: "social_market_talk", signalCategory: "social_market_talk",
    title: "Elevated X chatter: Anthropic IPO timing speculation",
    summary: "Social-platform mentions of Anthropic IPO timing 3.4× baseline; no primary source corroboration.",
    entityIds: ["anthropic"], entityTypes: ["vendor"],
    vendorIds: ["anthropic"], tickers: [],
    affectedExposureClasses: ["frontier_private_ai_lab"],
    affectedModules: ["watchlist"],
    sourceId: "src_x_anthropic_chatter_2026_05",
    sourceName: "Aggregated public X mentions",
    sourceType: "social_media", sourceDate: "2026-05-06", capturedAt: NOW_ISO,
    evidenceGrade: "E1", confidenceScore: 28, dataStatus: "seed",
    sentiment: 0.4, direction: "mixed", magnitude: 22, timeHorizon: "short_term",
    volatilityImpact: 14, valuationImpact: 0, revenueImpact: 0, marginImpact: 0,
    ipoWindowImpact: 0, liquidityImpact: 0, regulatoryImpact: 0, infrastructureImpact: 0, politicalRiskImpact: 0,
    notes: "Market talk only, bot-risk score elevated. Cannot move centre under truthfulness gate.",
    uncertaintyNote: "Low-confidence chatter. Renders only as a watchlist alert and band-widener.",
    requiresHumanReview: true,
  },
];

export const SEED_MARKET_TALK: MarketTalkSignal[] = [
  {
    id: "talk_reddit_nvda_oversold", platform: "reddit",
    query: "NVDA AI bubble correction",
    entity: { type: "ticker", id: "NVDA" },
    volumeScore: 64, sentimentScore: -28, noveltyScore: 18, repetitionScore: 72, botRiskScore: 32,
    sourceConfidence: 25, dataStatus: "seed",
    derivedFrom: ["src_reddit_aggregate_2026_05"],
    uncertaintyNote: "High repetition + moderate bot-risk. Can only widen volatility.",
    capturedAt: NOW_ISO,
  },
  {
    id: "talk_search_ai_layoffs", platform: "search_trends",
    query: "AI layoffs",
    entity: { type: "topic", id: "ai_labor" },
    volumeScore: 52, sentimentScore: -18, noveltyScore: 38, repetitionScore: 30, botRiskScore: 8,
    sourceConfidence: 35, dataStatus: "seed",
    derivedFrom: ["src_search_trends_2026_05"],
    uncertaintyNote: "Search-volume proxy, directional only.",
    capturedAt: NOW_ISO,
  },
];

export const SEED_REGULATORY_EVENTS: RegulatoryEvent[] = [
  {
    id: "reg_evt_eu_ai_act_2025",
    signalId: "sig_reg_eu_ai_act_obligations_2026",
    eventType: "ai_regulation", jurisdiction: "EU",
    effectiveDate: "2025-08-02",
    affectedVendorIds: ["openai", "anthropic", "googl", "msft", "mistral"],
    affectedExposureClasses: ["core_public_ai_platform", "frontier_private_ai_lab"],
    impacts: { revenueOpportunity: 0, marginRisk: 12, marketAccessRisk: 14, valuationRisk: 8, ipoWindowRisk: 5, customerAdoptionRisk: -8, supplyChainRisk: 0 },
    isPartisanCommentary: false, requiresCorroboration: false,
    uncertaintyNote: "Compliance cost real but priced in for incumbents.",
  },
  {
    id: "reg_evt_us_chip_export_2025",
    signalId: "sig_reg_us_export_control_h200_2025",
    eventType: "chip_export_control", jurisdiction: "US",
    effectiveDate: "2025-01-13",
    affectedVendorIds: ["nvda", "amd"],
    affectedExposureClasses: ["ai_infrastructure_enabler"],
    impacts: { revenueOpportunity: 0, marginRisk: 6, marketAccessRisk: 28, valuationRisk: 12, ipoWindowRisk: 4, customerAdoptionRisk: 8, supplyChainRisk: 18 },
    isPartisanCommentary: false, requiresCorroboration: false,
    uncertaintyNote: "Waivers and timing of country-coverage updates remain fluid.",
  },
];

export const SEED_MARKET_REGIME: MarketRegime = {
  id: "regime_2026_05",
  periodStart: "2026-05-01", periodEnd: "2026-05-31",
  riskAppetite: "neutral", rateRegime: "stable", inflationRegime: "disinflation",
  growthRegime: "softening", creditRegime: "normal", volatilityRegime: "low",
  techMultipleRegime: "expanded", ipoWindowQuality: "selective",
  aiSentimentRegime: "constructive", infrastructureConstraintRegime: "tight",
  confidenceScore: 72,
  sourceIds: [
    "src_fed_fomc_apr_2026",
    "src_bls_cpi_apr_2026",
    "src_cboe_vix_may_2026",
    "src_eia_steo_2026",
    "src_renaissance_2026_ytd",
  ],
  uncertaintyNote: "Regime classification is analyst-judged from public official sources. Confidence reflects corroboration breadth.",
  contributingSignalIds: [
    "sig_macro_fred_fedfunds_2026_04",
    "sig_macro_bls_cpi_2026_04",
    "sig_macro_vix_2026_05",
    "sig_energy_eia_data_centre_demand_2026",
    "sig_ipo_window_2026_warmer",
  ],
};
