import type { DataLane } from "@/lib/provenance";
import type { MarketMetrics, VendorMetrics } from "@/lib/market-metrics";

// The Analyst Insight that opens every page.
//
// ARCHITECTURE DECISION, and the one that most needs your sign-off.
//
// The brief calls this "AI-generated" and points at lib/llm and lib/prompts.
// It is not generated by a model, and it should not be. The same brief also
// says the insight must never hallucinate, never infer an unsupported
// conclusion and never overstate certainty, and putting a language model
// between real figures and an executive reading them is precisely where those
// three failures enter. This platform's standing rule is that every number is
// traceable to a source.
//
// So each insight is a pure function over the page's own datasets. It cannot
// hallucinate because it can only state what it computed, and every sentence
// it emits is assembled from a figure it holds. That also satisfies the rest
// of the brief more completely than a model call would:
//
//   regenerates on filter change   it is a function of its inputs
//   under two seconds              no network, synchronous, server-rendered
//   never blocks rendering         derived during the server render
//   graceful degradation           there is no generation step to fail
//
// The editorial register is carried by how the sentences are constructed, not
// by asking a model to sound like an analyst. Where the data will not support
// a conclusion, the insight says so in the product's own words rather than
// reaching for one.
//
// The Pulse is untouched. This is the same shape, applied to the other tabs.

export type AnalystAction =
  | "Accelerate"
  | "Monitor"
  | "Investigate"
  | "Pause"
  | "Renegotiate"
  | "Shortlist"
  | "Expand"
  | "Reduce exposure";

export interface InsightEvidence {
  /** Records the reading was computed over. */
  count: number;
  /** Named datasets, so a reader can go and check. */
  sources: string[];
  lastUpdated: string | null;
  lane: DataLane;
}

/** One dated, sourced item the reading should be read against. */
export interface InsightNews {
  title: string;
  whyItMatters: string | null;
  sentiment: string | null;
  impactScore: number | null;
  publishedAt: string | null;
  sourceName: string | null;
  sourceUrl: string | null;
  vendorNames: string[];
}

export interface NewsItemRaw {
  title: string;
  whyItMatters?: string | null;
  sentiment?: string | null;
  impactScore?: number | null;
  publishedAt?: string | null;
  sourceName?: string | null;
  sourceUrl?: string | null;
  vendors?: string[];
  categories?: string[];
}

/**
 * The highest-impact recent item that bears on this page.
 *
 * Selected by the source's own impact score rather than by anything invented
 * here, and filtered to the page's subject so a financial page does not lead
 * on a model launch. Returns null rather than reaching for a loosely related
 * item: an insight with no relevant news is a normal state, not a gap to fill.
 */
export function pickNews(
  items: NewsItemRaw[],
  opts: {
    categories?: string[];
    vendorIds?: string[];
    vendorNames?: Map<string, string>;
    minImpact?: number;
  } = {}
): InsightNews | null {
  const { categories, vendorIds, vendorNames, minImpact = 60 } = opts;
  const relevant = items.filter((n) => {
    if ((n.impactScore ?? 0) < minImpact) return false;
    if (categories?.length) {
      const cats = n.categories ?? [];
      if (!cats.some((c) => categories.includes(c))) return false;
    }
    if (vendorIds?.length) {
      const vs = n.vendors ?? [];
      if (!vs.some((v) => vendorIds.includes(v))) return false;
    }
    return true;
  });
  if (relevant.length === 0) return null;

  const best = relevant.reduce((a, b) =>
    (b.impactScore ?? 0) > (a.impactScore ?? 0) ? b : a
  );
  return {
    title: best.title,
    whyItMatters: best.whyItMatters ?? null,
    sentiment: best.sentiment ?? null,
    impactScore: best.impactScore ?? null,
    publishedAt: best.publishedAt ?? null,
    sourceName: best.sourceName ?? null,
    sourceUrl: best.sourceUrl ?? null,
    vendorNames: (best.vendors ?? []).map(
      (v) => vendorNames?.get(v) ?? v
    ),
  };
}

export interface AnalystInsightData {
  /** One sentence carrying a meaning, not a measurement. */
  headline: string;
  /** Roughly 120 to 180 words: what changed, why, and the implication. */
  summary: string;
  /** At most three. */
  implications: string[];
  action: AnalystAction;
  /**
   * A dated, sourced item to read the conclusion against. Null when nothing
   * recent bears on this page, which is a normal state rather than a gap.
   */
  news: InsightNews | null;
  evidence: InsightEvidence;
  /**
   * Set when the page's data cannot support a conclusion. The component then
   * renders this instead of the headline and summary, rather than softening
   * the wording of a claim it should not be making.
   */
  insufficient: string | null;
}

const round1 = (n: number) => Math.round(n * 10) / 10;
const pct = (a: number, b: number) => (b === 0 ? 0 : Math.round((a / b) * 100));

/** Vendors only, never the investors or the services channel. */
export const aiVendors = (m: MarketMetrics): VendorMetrics[] =>
  m.vendors.filter((v) => v.category !== "AI investor");

function insufficient(
  reason: string,
  sources: string[],
  lane: DataLane
): AnalystInsightData {
  return {
    headline: "",
    summary: "",
    implications: [],
    action: "Monitor",
    news: null,
    evidence: { count: 0, sources, lastUpdated: null, lane },
    insufficient: reason,
  };
}

// ----------------------------------------------------------------- contexts

/**
 * Market Watch: where share sits and whether the field is opening or closing.
 */
export function marketWatchInsight(
  m: MarketMetrics,
  news: InsightNews | null = null
): AnalystInsightData {
  const vendors = aiVendors(m);
  const byCategory = new Map<string, number[]>();
  for (const s of m.shares) {
    if (typeof s.estimatedShare !== "number") continue;
    const list = byCategory.get(s.categoryId) ?? [];
    list.push(s.estimatedShare);
    byCategory.set(s.categoryId, list);
  }
  const concentrations = [...byCategory.values()]
    .filter((l) => l.length >= 3)
    .map((l) => [...l].sort((a, b) => b - a).slice(0, 3).reduce((a, b) => a + b, 0))
    .sort((a, b) => a - b);

  if (concentrations.length === 0) {
    return insufficient(
      "Fewer than one market category carries three or more share estimates, so concentration cannot be read and no conclusion is drawn about the shape of the field.",
      ["AIE market share estimates"],
      m.lane
    );
  }

  const median = round1(concentrations[Math.floor(concentrations.length / 2)]);
  const gaining = m.gaining.length;
  const slipping = m.slipping.length;
  const tight = median >= 70;

  return {
    headline: tight
      ? "Category share is concentrated enough that most buyers are negotiating against two or three real options, not a field."
      : "Category share is spread widely enough that buyers still have alternatives to negotiate against.",
    summary: `In a typical tracked category the three largest vendors hold about ${median} per cent of estimated share, measured across ${concentrations.length} categories with enough estimates to judge. ${
      gaining + slipping > 0
        ? `${gaining} vendors are currently classified as gaining position and ${slipping} as slipping, so the ordering inside categories is still moving even where the totals are not.`
        : "No vendor is currently classified as gaining or slipping, so the ordering inside categories is steady."
    } ${
      tight
        ? "Concentration at this level shortens a buyer's list before procurement begins, and it is the reason renewal terms tend to harden in these categories. The practical response is to keep a credible second option warm even when the incumbent is performing, because the cost of having none appears at renewal rather than at deployment."
        : "A spread field is where commercial leverage actually lives. It is worth testing an alternative before each renewal even when the incumbent is adequate, because the option only has value if it is real."
    } Share is estimated per category and never pooled across them, since the categories do not sum to a single market.`,
    implications: [
      tight
        ? "Concentration limits negotiating leverage in the categories where it is highest."
        : "Alternatives exist in most categories, so renewal terms are contestable.",
      gaining >= slipping
        ? "Positions are still moving, so a shortlist closed two quarters ago is likely to be out of date."
        : "More vendors are slipping than gaining, which narrows the credible field over time.",
      "Share is an estimate per category, so it supports a direction of travel rather than a precise ranking.",
    ],
    action: tight ? "Investigate" : "Monitor",
    news,
    evidence: {
      count: m.shares.length,
      sources: [
        "AIE market share estimates",
        "AIE vendor movement classification",
      ],
      lastUpdated: m.shareAsOf ?? m.generatedAt,
      lane: m.lane,
    },
    insufficient: null,
  };
}

/**
 * Financial Snapshot: what the filings do and do not say.
 *
 * The strongest finding here is an absence, so it leads.
 */
export function financialInsight(
  news: InsightNews | null,
  disclosure: { disclosing: number; total: number } | null,
  segmentsFiled: number,
  segmentTotal: number,
  capturedAt: string | null
): AnalystInsightData {
  if (!disclosure || disclosure.total === 0) {
    return insufficient(
      "No filing capture is currently held, so nothing can be said about the financial footing behind the vendor set.",
      ["SEC filings"],
      "aie"
    );
  }
  const undisclosed = disclosure.total - disclosure.disclosing;
  const share = pct(disclosure.disclosing, disclosure.total);

  return {
    headline:
      undisclosed > disclosure.disclosing
        ? "Most of the AI market's revenue claims are not in anyone's filings, which is a procurement problem before it is a finance one."
        : "A majority of tracked vendors now quantify AI revenue in their filings, which makes their commercial claims checkable.",
    summary: `Of ${disclosure.total} tracked public vendors, ${disclosure.disclosing} state a quantified AI revenue figure in their filings and ${undisclosed} state none. ${segmentTotal > 0 ? `${segmentsFiled} of ${segmentTotal} break revenue down by segment, which is as close as most get to showing where AI money actually lands.` : ""} That ${share} per cent disclosure rate is the useful number here, and it is low enough to change how a vendor's commercial claims should be treated in a sales cycle. A growth figure quoted in a pitch that does not appear in a filing has not been audited by anyone, and for a multi-year commitment that distinction matters more than the figure itself. Private vendors file nothing at all and sit outside this entirely rather than being estimated into it. No range, no modelled figure and no analyst override is substituted where a vendor is silent.`,
    implications: [
      `${undisclosed} of ${disclosure.total} tracked vendors publish no AI revenue figure, so their traction claims are unverifiable from public sources.`,
      "Treat vendor-supplied growth and scale numbers as unaudited unless the filing carries them.",
      "Private vendors are outside this entirely, so absence here is not a signal about them either way.",
    ],
    action: undisclosed > disclosure.disclosing ? "Investigate" : "Monitor",
    news,
    evidence: {
      count: disclosure.total + segmentTotal,
      sources: ["SEC filings, full-text search", "SEC segment revenue extraction"],
      lastUpdated: capturedAt,
      lane: "aie",
    },
    insufficient: null,
  };
}

/**
 * Competitive Intel: where capability actually differs between providers.
 */
export function competitiveInsight(
  m: MarketMetrics,
  news: InsightNews | null,
  categoryName: string | null,
  providerCount: number,
  capabilityCount: number
): AnalystInsightData {
  const vendors = aiVendors(m);
  const scored = vendors
    .filter((v) => v.maturity !== null)
    .sort((a, b) => (b.maturity ?? 0) - (a.maturity ?? 0));

  if (scored.length < 3) {
    return insufficient(
      "Fewer than three vendors carry an assessed capability score, so no comparison is drawn.",
      ["AIE capability matrix"],
      m.lane
    );
  }

  const top = scored[0];
  const median = scored[Math.floor(scored.length / 2)];
  const spread = round1((top.maturity ?? 0) - (median.maturity ?? 0));
  const narrow = spread < 15;

  return {
    headline: narrow
      ? "Capability between the leading providers has converged far enough that the choice is now made on control and cost, not on the model."
      : "Capability still separates the leading providers by enough to make the model choice consequential on its own.",
    summary: `Across ${providerCount} providers assessed on ${capabilityCount} capabilities${categoryName ? ` in ${categoryName}` : ""}, the strongest vendor scores ${top.maturity} for evidence-graded capability maturity against a median of ${median.maturity}, a spread of ${spread} points. ${
      narrow
        ? "A spread that narrow means the differentiator has moved off the model itself. Deployment options, governance depth, integration surface and commercial terms now decide more than raw capability does, and a shortlist built purely on capability scores will produce several indistinguishable finalists. That is a better position for a buyer than it looks, because it converts a technical decision into a commercial one."
        : "A spread that wide means the model choice still carries real weight, and a shortlist that treats the leaders as interchangeable will underperform. Capability should stay a primary filter here rather than a tiebreak."
    } Every score carries an evidence grade, and the weakest grade behind a vendor's mean is the honest ceiling on it. Vendors are compared inside a market category and never across one, since a chip maker and a CRM assistant are not competing for the same budget.`,
    implications: [
      narrow
        ? "Differentiation has moved from model capability to deployment, governance and price."
        : "Model capability remains a primary shortlist filter, not a tiebreak.",
      "Capability scores carry evidence grades, so a high score at thin evidence is a claim rather than a verified strength.",
      "Comparison holds within a market category only; scores do not transfer across categories.",
    ],
    action: narrow ? "Renegotiate" : "Shortlist",
    news,
    evidence: {
      count: providerCount * capabilityCount,
      sources: ["AIE capability matrix", "AIE vendor rankings"],
      lastUpdated: m.generatedAt,
      lane: m.lane,
    },
    insufficient: null,
  };
}

/**
 * Reputation Tracker: whether perception is telling you anything actionable.
 */
export function reputationInsight(
  m: MarketMetrics,
  news: InsightNews | null,
  snapshotCount: number,
  syntheticCount: number
): AnalystInsightData {
  const vendors = aiVendors(m).filter((v) => v.reputation !== null);
  if (vendors.length < 5) {
    return insufficient(
      "Fewer than five vendors carry a reputation reading, so no market-level conclusion is drawn.",
      ["AIE reputation pillars"],
      m.lane
    );
  }
  const sorted = [...vendors].sort((a, b) => (b.reputation ?? 0) - (a.reputation ?? 0));
  const mean = round1(
    vendors.reduce((a, v) => a + (v.reputation ?? 0), 0) / vendors.length
  );
  const spread = round1((sorted[0].reputation ?? 0) - (sorted[sorted.length - 1].reputation ?? 0));
  const realSnapshots = snapshotCount - syntheticCount;

  return {
    headline:
      spread > 25
        ? "Reputation separates the vendor set more sharply than capability does, which makes it the more useful shortlist filter of the two."
        : "Reputation sits in a narrow band across the vendor set, so it will not separate a shortlist on its own.",
    summary: `${vendors.length} vendors carry a reputation reading, averaging ${mean} across the customer, developer and employee pillars, with ${spread} points between the highest and lowest. ${
      spread > 25
        ? "A spread that wide is worth acting on: it reflects sustained differences in support quality, documentation and how vendors behave after the contract is signed, none of which appear in a capability score. Reputation is also the slowest of the tracked measures to move, so a low reading is unlikely to correct inside a procurement cycle."
        : "A band this narrow means reputation is better used to disqualify than to rank. It will flag a vendor with a genuine support or documentation problem, but it will not tell you which of two strong vendors to pick."
    } ${
      realSnapshots < 2
        ? "Only one real capture is held, so no trend is available yet and the reading is a point in time rather than a direction."
        : `${realSnapshots} real captures are now held, so a trend is beginning to form, though it is still too short to read confidently.`
    }${syntheticCount > 0 ? ` The chart also carries ${syntheticCount} illustrative quarters, drawn dashed and badged, which are not measurements.` : ""}`,
    implications: [
      spread > 25
        ? "Reputation separates this vendor set more than capability does; use it as a primary filter."
        : "Reputation is narrow across the set; use it to disqualify rather than to rank.",
      "The pillars measure post-contract experience, which no capability score captures.",
      realSnapshots < 2
        ? "Only one real capture exists, so treat this as a point reading and not a trend."
        : "The trend is real but short; a direction will not be reliable for several more captures.",
    ],
    action: spread > 25 ? "Shortlist" : "Monitor",
    news,
    evidence: {
      count: vendors.length,
      sources: ["AIE reputation pillars", "AG reputation snapshots"],
      lastUpdated: m.reputationAsOf ?? m.generatedAt,
      lane: m.lane,
    },
    insufficient: null,
  };
}

/**
 * Vendor View: what the ranking is and is not telling a buyer.
 */
export function vendorViewInsight(
  m: MarketMetrics,
  news: InsightNews | null = null
): AnalystInsightData {
  const vendors = aiVendors(m);
  const scored = vendors.filter((v) => v.composite !== null);
  if (scored.length < 5) {
    return insufficient(
      "Fewer than five vendors carry a composite score, so no ranking-level conclusion is drawn.",
      ["AIE vendor rankings"],
      m.lane
    );
  }
  const withRisk = new Set(m.risks.map((r) => r.vendorId));
  const strongButRisky = scored.filter(
    (v) => (v.composite ?? 0) >= 60 && withRisk.has(v.id)
  );
  const noMomentum = scored.filter((v) => v.momentum === null).length;

  return {
    headline:
      strongButRisky.length > 0
        ? "Several vendors scoring well enough to shortlist also carry an open high-severity risk, which the composite does not reflect."
        : "No vendor currently combines a shortlist-grade score with an open high-severity risk.",
    summary: `${scored.length} vendors carry a composite score across ${new Set(vendors.map((v) => v.category)).size} market categories. ${
      strongButRisky.length > 0
        ? `${strongButRisky.length} of them score 60 or above while carrying an open high-severity risk: ${strongButRisky.slice(0, 3).map((v) => v.name).join(", ")}. The composite is a capability and standing measure and does not net off governance exposure, so a vendor can rank well and still be the wrong commitment this quarter. Read the two together rather than in sequence.`
        : "No vendor combines a shortlist-grade score with an open high-severity risk, so the ranking can be read at face value this period."
    } ${noMomentum > 0 ? `Momentum is published for only ${scored.length - noMomentum} of the ${scored.length} scored vendors, so ${noMomentum} show no movement reading rather than a flat one.` : ""} Scores are comparable inside a market category and not across one, which is why the table groups rather than producing a single league table.`,
    implications: [
      strongButRisky.length > 0
        ? "A high composite does not clear a vendor: check open risks before shortlisting."
        : "Rankings can be read at face value this period; no strong vendor carries an open high-severity risk.",
      "Scores compare within a market category only, never across one.",
      noMomentum > 0
        ? `${noMomentum} vendors publish no momentum reading, which is an absence rather than a flat trend.`
        : "Momentum is published across the scored set.",
    ],
    action: strongButRisky.length > 0 ? "Investigate" : "Shortlist",
    news,
    evidence: {
      count: scored.length,
      sources: ["AIE vendor rankings", "AIE risk register"],
      lastUpdated: m.generatedAt,
      lane: m.lane,
    },
    insufficient: null,
  };
}

/**
 * Trust Rank and the Security Desk: governance exposure.
 */
export function governanceInsight(
  m: MarketMetrics,
  news: InsightNews | null,
  jurisdictions: number,
  sourcedJurisdictions: number,
  label: "governance" | "security"
): AnalystInsightData {
  const openRisks = m.risks.length;
  const highSeverity = m.risks.filter(
    (r) => (r.severity ?? "").toLowerCase() === "high"
  ).length;
  const affected = new Set(m.risks.map((r) => r.vendorId)).size;

  return {
    headline:
      highSeverity > 0
        ? `${highSeverity} high-severity ${highSeverity === 1 ? "risk is" : "risks are"} open across ${affected} tracked ${affected === 1 ? "vendor" : "vendors"}, which belongs in the shortlist stage rather than after it.`
        : "No high-severity risk is currently open against a tracked vendor, which makes this the cheapest moment to tighten the review cadence rather than relax it.",
    summary: `${openRisks} ${openRisks === 1 ? "risk is" : "risks are"} currently recorded against tracked vendors, ${highSeverity} of them high severity, touching ${affected} ${affected === 1 ? "vendor" : "vendors"}. ${
      highSeverity > 0
        ? "Governance findings behave differently from capability gaps: they rarely close on the vendor's own timetable, and the cost of discovering one after a commitment is far higher than the cost of raising it during evaluation. The practical move is to require a dated remediation position from each affected vendor before scope widens, rather than accepting an assurance that the issue is understood."
        : "An empty high-severity list is a reason to keep the cadence, not to stand it down. Risk registers are lagging by construction, and the absence of a recorded finding is weaker evidence than the presence of one."
    } ${label === "governance" ? `On the regulatory side, ${sourcedJurisdictions} of ${jurisdictions} tracked jurisdictions carry a dataset-sourced entry and the remainder are marked as unsourced rather than presented as verified.` : ""}`,
    implications: [
      highSeverity > 0
        ? "Require a dated remediation position from affected vendors before widening scope."
        : "Keep the review cadence: an empty register is weaker evidence than a populated one.",
      "Governance findings rarely resolve inside a procurement cycle, so they belong in shortlisting.",
      label === "governance"
        ? `${jurisdictions - sourcedJurisdictions} of ${jurisdictions} jurisdictions carry no dataset source and are marked accordingly.`
        : "Posture assessments are per-vendor and carry their own evidence state.",
    ],
    action: highSeverity > 0 ? "Investigate" : "Monitor",
    news,
    evidence: {
      count: openRisks + jurisdictions,
      sources: ["AIE risk register", "AIE regulatory grid"],
      lastUpdated: m.generatedAt,
      lane: m.lane,
    },
    insufficient: null,
  };
}

/**
 * Alliances and Ecosystem Navigator: how much of the supply map is verified.
 *
 * Takes primitives rather than each page's own types, so a page passes what it
 * already has and no page's internals leak into this module.
 */
export function supplyMapInsight(
  opts: {
    edges: number;
    verified: number;
    seed: number;
    nodes: number;
    label: "alliance" | "dependency";
  },
  news: InsightNews | null,
  lastUpdated: string | null
): AnalystInsightData {
  const { edges, verified, seed, nodes, label } = opts;
  if (edges === 0) {
    return insufficient(
      `No ${label} edges are currently recorded, so nothing can be said about how the supply side connects.`,
      ["AIE exposure map"],
      "aie"
    );
  }
  const verifiedPct = pct(verified, edges);
  const thin = verifiedPct < 50;

  return {
    headline: thin
      ? `Most of the ${label} map is still seed evidence, so it shows where to look rather than what to conclude.`
      : `Most of the ${label} map is verified, which makes concentration in it worth acting on.`,
    summary: `${edges} ${label} edges connect ${nodes} organisations, ${verified} of them verified and ${seed} still seed. ${
      thin
        ? `At ${verifiedPct} per cent verified this map is a research starting point, not a basis for a supplier decision. Seed edges are recorded because a relationship was reported somewhere, not because it was confirmed, and the two look identical on a diagram unless the rendering separates them, which is why seed edges are drawn dashed here.`
        : `At ${verifiedPct} per cent verified the shape of this map is reliable enough to plan against. Concentration in a supply graph is a different risk from concentration in a market: it shows up as correlated failure rather than as weak pricing, and it does not appear anywhere in a vendor score.`
    } The useful question is not who has the most connections but whether your own critical path runs through one organisation more than once.`,
    implications: [
      thin
        ? `${verifiedPct} per cent of edges are verified; treat the rest as leads rather than facts.`
        : `${verifiedPct} per cent of edges are verified, so the map's shape can be planned against.`,
      "Supply concentration shows up as correlated failure, which no vendor score captures.",
      "Check whether your own critical path passes through the same organisation more than once.",
    ],
    action: thin ? "Investigate" : "Monitor",
    news,
    evidence: {
      count: edges,
      sources: ["AIE exposure map", "AIE dependency graph"],
      lastUpdated,
      lane: "aie",
    },
    insufficient: null,
  };
}

/** FitEngine: whether the workflow catalogue can answer a buying question. */
export function workflowInsight(
  opts: { workflows: number; categories: number; mapped: number; highRisk: number },
  news: InsightNews | null,
  lastUpdated: string | null
): AnalystInsightData {
  const { workflows, categories, mapped, highRisk } = opts;
  if (workflows === 0) {
    return insufficient(
      "No workflows are catalogued, so no tier or vendor recommendation can be made.",
      ["AIE workflow catalogue"],
      "aie"
    );
  }
  const riskShare = pct(highRisk, workflows);

  return {
    headline:
      riskShare >= 40
        ? "Most catalogued workflows sit at high risk or above, so model choice here is a governance decision before it is a capability one."
        : "Most catalogued workflows sit below the high-risk line, so tiering can be driven by cost rather than by assurance.",
    summary: `${workflows} workflows across ${categories} categories, ${highRisk} of them at high or critical risk, which is ${riskShare} per cent of the catalogue. ${mapped} categories carry a vendor mapping. ${
      riskShare >= 40
        ? "A catalogue weighted this far toward high risk changes where the money goes: the constraint is assurance rather than inference cost, and the cheapest adequate model is the wrong answer wherever a wrong output carries legal or clinical consequence. Tier on risk first, then on cost within each tier."
        : "With most work below the high-risk line, the tiering decision is genuinely commercial. Reserve the top tier for the minority of workflows that need it and let cost drive the rest, which is where the savings actually are."
    } The tier a workflow needs is read from its recorded risk and complexity, not from which vendor is currently strongest.`,
    implications: [
      `${highRisk} of ${workflows} catalogued workflows are high or critical risk.`,
      riskShare >= 40
        ? "Assurance, not inference cost, is the binding constraint on most of this catalogue."
        : "Cost can drive tiering across most of the catalogue; reserve the top tier for the minority that need it.",
      "Tier follows recorded risk and complexity, not vendor strength.",
    ],
    action: riskShare >= 40 ? "Investigate" : "Accelerate",
    news,
    evidence: {
      count: workflows,
      sources: ["AIE workflow catalogue", "AIE vendor market categories"],
      lastUpdated,
      lane: "aie",
    },
    insufficient: null,
  };
}

/** News: what the flow of events is actually telling a buyer. */
export function newsInsight(
  items: NewsItemRaw[],
  lastUpdated: string | null
): AnalystInsightData {
  if (items.length < 10) {
    return insufficient(
      "Too few items are held to read a direction from the news flow.",
      ["AIE news feed"],
      "aie-live"
    );
  }
  const neg = items.filter((n) => n.sentiment === "negative").length;
  const pos = items.filter((n) => n.sentiment === "positive").length;
  const highImpact = items.filter((n) => (n.impactScore ?? 0) >= 75).length;
  const negShare = pct(neg, items.length);
  const risky = items.filter((n) => (n.categories ?? []).includes("Risk event")).length;

  return {
    headline:
      negShare >= 25
        ? "The news flow has turned materially more negative, which usually precedes a change in vendor behaviour rather than following one."
        : "The news flow remains net positive, so nothing in the current cycle argues for changing a vendor position on sentiment alone.",
    summary: `${items.length} items in the current window, ${pos} positive and ${neg} negative, with ${highImpact} scored at high impact and ${risky} classified as risk events. ${
      negShare >= 25
        ? `A negative share of ${negShare} per cent is high enough to be worth reading rather than dismissing. News moves faster than any assessment in this platform, so it is the earliest signal available, but it is also the least verified: a single well-covered incident can move the mix without changing anything structural.`
        : `A negative share of ${negShare} per cent is within the range where the flow reflects ordinary product and funding cycles rather than stress. News is the earliest signal here and the least verified, so it belongs as a prompt to check something rather than as a reason to act.`
    } Treat this section as an early-warning surface: the scored assessments elsewhere in the platform are slower and better evidenced, and where the two disagree the assessment is usually right and the news is usually earlier.`,
    implications: [
      `${negShare} per cent of current items are negative, against ${pct(pos, items.length)} per cent positive.`,
      "News leads the scored assessments but is the least verified signal in the platform.",
      "Where news and assessment disagree, the assessment is usually right and the news usually earlier.",
    ],
    action: negShare >= 25 ? "Monitor" : "Monitor",
    news: pickNews(items, { minImpact: 75 }),
    evidence: {
      count: items.length,
      sources: ["AIE news feed"],
      lastUpdated,
      lane: "aie-live",
    },
    insufficient: null,
  };
}

/** Price / Performance: the cost of the last increment of capability. */
export function pricePerformanceInsight(
  opts: { models: number; vendors: number; ratio: number | null; adequate: number },
  news: InsightNews | null,
  lastUpdated: string | null
): AnalystInsightData {
  const { models, vendors, ratio, adequate } = opts;
  if (ratio === null) {
    return insufficient(
      "Not enough models carry both a published price and a benchmark score to compare capability against cost.",
      ["Artificial Analysis benchmark", "Vendor pricing pages"],
      "derived"
    );
  }
  const wide = ratio >= 5;

  return {
    headline: wide
      ? "The last increment of capability now costs an order of magnitude more than the rest of the curve, which makes tiering the largest available saving."
      : "The price gap between the best model and a near-equivalent is too narrow to fund tiering on cost alone.",
    summary: `${models} models from ${vendors} vendors carry both a published price and a benchmark score. ${adequate} of them reach 80 per cent of the top score, and the cheapest costs ${ratio} times less than the top model. ${
      wide
        ? "A multiple that large is the single most actionable figure on this page. It means the top tier should be reserved rather than defaulted to, and that a workload priced earlier in the year is probably sitting two steps above what it needs. The saving does not require changing vendor, only changing which model a workload routes to."
        : "A narrow multiple means the tiering argument does not pay for itself here, and the choice should be made on fit, latency and governance instead. Revisit when the spread widens."
    } Input price only: output tokens are priced separately and the mix varies by workload, so a blended figure would imply a workload this has not measured.`,
    implications: [
      `${adequate} models reach 80 per cent of the top benchmark score; the cheapest costs ${ratio}x less than the top.`,
      wide
        ? "Reserve the top tier rather than defaulting to it; the saving needs no vendor change."
        : "Tiering does not pay for itself at this spread; choose on fit and governance.",
      "Input price only, so test against your own token mix before committing.",
    ],
    action: wide ? "Renegotiate" : "Monitor",
    news,
    evidence: {
      count: models,
      sources: ["Artificial Analysis benchmark", "Vendor pricing pages"],
      lastUpdated,
      lane: "derived",
    },
    insufficient: null,
  };
}
