import type { DataLane } from "@/lib/provenance";
import type { MarketMetrics, VendorMetrics } from "@/lib/market-metrics";
import { MARKET_CATEGORY_LIST } from "@/lib/comparability";
import type { ToolKey } from "@/lib/ui/tools";
import { vendorName } from "@/lib/aie/vendor-directory";

// The Analyst Insight that opens every page.
//
// ARCHITECTURE DECISION, and the one that most needs your sign-off.
//
// The brief calls this "AI-generated" and points at lib/llm and lib/prompts.
// It is not generated by a model, and it should not be. The same brief also
// says the insight must never hallucinate, never infer an unsupported
// conclusion and never overstate certainty, and putting a language model
// between real figures and an executive reading them is precisely where those
// three failures enter. This platform's standing rule is that every number is
// traceable to a source.
//
// So each insight is a pure function over the page's own datasets. It cannot
// hallucinate because it can only state what it computed, and every sentence
// it emits is assembled from a figure it holds. That also satisfies the rest
// of the brief more completely than a model call would:
//
//   regenerates on filter change   it is a function of its inputs
//   under two seconds              no network, synchronous, server-rendered
//   never blocks rendering         derived during the server render
//   graceful degradation           there is no generation step to fail
//
// The editorial register is carried by how the sentences are constructed, not
// by asking a model to sound like an analyst. Where the data will not support
// a conclusion, the insight says so in the product's own words rather than
// reaching for one.
//
// The Pulse is untouched. This is the same shape, applied to the other tabs.

export type AnalystAction =
  | "Accelerate"
  | "Monitor"
  | "Investigate"
  | "Pause"
  | "Renegotiate"
  | "Shortlist"
  | "Expand"
  | "Reduce exposure";

export interface InsightEvidence {
  /** Records the reading was computed over. */
  count: number;
  /** Named datasets, so a reader can go and check. */
  sources: string[];
  lastUpdated: string | null;
  lane: DataLane;
}

/** One dated, sourced item the reading should be read against. */
export interface InsightNews {
  title: string;
  /**
   * The SOURCE's own commentary. Carried so nothing is lost, and deliberately
   * not rendered as this page's analysis. See `tie`.
   */
  whyItMatters: string | null;
  /**
   * OUR line on why this item matters HERE, computed from what the page
   * actually covers.
   *
   * The source's commentary used to render directly under the headline inside
   * our analysis block, which presented somebody else's reading as ours. That
   * is wrong even when the commentary is right, and on the OpenAI funding item
   * it was not right: the upstream line repeats the round's investors
   * incorrectly, and we were printing it on seven tabs under our own heading.
   *
   * Computed rather than written, on the same reasoning as the shortlist
   * paragraph: every clause restates something the page already holds, so it
   * cannot drift from the page it sits on, costs nothing, and is still there
   * when the analyst API is not.
   */
  tie: string | null;
  sentiment: string | null;
  impactScore: number | null;
  publishedAt: string | null;
  sourceName: string | null;
  sourceUrl: string | null;
  vendorNames: string[];
}

export interface NewsItemRaw {
  title: string;
  whyItMatters?: string | null;
  sentiment?: string | null;
  impactScore?: number | null;
  publishedAt?: string | null;
  sourceName?: string | null;
  sourceUrl?: string | null;
  vendors?: string[];
  categories?: string[];
}

/**
 * The highest-impact recent item that bears on this page.
 *
 * Selected by the source's own impact score rather than by anything invented
 * here, and filtered to the page's subject so a financial page does not lead
 * on a model launch. Returns null rather than reaching for a loosely related
 * item: an insight with no relevant news is a normal state, not a gap to fill.
 */
export function pickNews(
  items: NewsItemRaw[],
  opts: {
    categories?: string[];
    vendorIds?: string[];
    vendorNames?: Map<string, string>;
    minImpact?: number;
    /** The vendors this page actually covers, for the tie line. */
    pageVendorIds?: string[];
  } = {}
): InsightNews | null {
  const { categories, vendorIds, vendorNames, minImpact = 60 } = opts;
  const relevant = items.filter((n) => {
    if ((n.impactScore ?? 0) < minImpact) return false;
    if (categories?.length) {
      const cats = n.categories ?? [];
      if (!cats.some((c) => categories.includes(c))) return false;
    }
    if (vendorIds?.length) {
      const vs = n.vendors ?? [];
      if (!vs.some((v) => vendorIds.includes(v))) return false;
    }
    return true;
  });
  if (relevant.length === 0) return null;

  const best = relevant.reduce((a, b) =>
    (b.impactScore ?? 0) > (a.impactScore ?? 0) ? b : a
  );
  return {
    title: best.title,
    whyItMatters: best.whyItMatters ?? null,
    sentiment: best.sentiment ?? null,
    impactScore: best.impactScore ?? null,
    publishedAt: best.publishedAt ?? null,
    sourceName: best.sourceName ?? null,
    sourceUrl: best.sourceUrl ?? null,
    vendorNames: (best.vendors ?? []).map((v) => vendorNames?.get(v) ?? v),
    tie: tieToPage(best, opts),
  };
}

/**
 * Why the picked item bears on THIS page, in our words and from our data.
 *
 * Says one of three things, and only what it can check:
 *
 *   The item names vendors this page covers  -> names them, and says how many
 *                                               of the page's set that is.
 *   It names vendors, none of them here      -> says so, so the reader reads
 *                                               it as market context rather
 *                                               than as a read on the figures.
 *   It names no vendor at all                -> nothing. Silence beats filler.
 *
 * It never characterises the item. Characterising is what the source's own
 * commentary does, and doing it ourselves would mean asserting something the
 * page cannot check.
 */
function tieToPage(
  item: NewsItemRaw,
  opts: { pageVendorIds?: string[]; vendorNames?: Map<string, string> }
): string | null {
  const { pageVendorIds, vendorNames } = opts;
  const named = item.vendors ?? [];
  if (named.length === 0 || !pageVendorIds?.length) return null;

  const onPage = named.filter((v) => pageVendorIds.includes(v));
  const label = (v: string) => vendorNames?.get(v) ?? v;

  if (onPage.length === 0) {
    return `It names no vendor this page covers, so read it as market context rather than as a read on the figures below.`;
  }
  return `It names ${nameList(onPage.map(label))}, ${
    onPage.length === 1 ? "which is" : "which are"
  } among the ${pageVendorIds.length} this page covers. The figures below are what this page holds on ${onPage.length === 1 ? "it" : "them"}, and are not derived from this item.`;
}

export interface AnalystInsightData {
  /** One sentence carrying a meaning, not a measurement. */
  headline: string;
  /** Roughly 120 to 180 words: what changed, why, and the implication. */
  summary: string;
  /** At most three. */
  implications: string[];
  action: AnalystAction;
  /**
   * The tools that let a reader act on this insight now. A recommendation
   * that names the page which does the thing is worth more than one that
   * leaves the reader to find it. Never includes the page it renders on.
   */
  tools?: ToolKey[];
  /**
   * A dated, sourced item to read the conclusion against. Null when nothing
   * recent bears on this page, which is a normal state rather than a gap.
   */
  news: InsightNews | null;
  evidence: InsightEvidence;
  /**
   * Set when the page's data cannot support a conclusion. The component then
   * renders this instead of the headline and summary, rather than softening
   * the wording of a claim it should not be making.
   */
  insufficient: string | null;
  /**
   * Set when a conclusion IS drawn but its basis is genuinely limited, naming
   * the specific limit in one clause: unconfirmed links, a single capture with
   * no trend, a benchmark that covers a fraction of the catalogue.
   *
   * Declared by the builder rather than inferred by the component, because
   * only the builder knows what its own floor is. `evidence.count` means a
   * different thing on every page (vendors, edges, workflows, models), so a
   * single count threshold in the UI would be an arbitrary rule dressed as a
   * measurement.
   *
   * Where this is set the panel offers the reader their AG Analyst, which is
   * the honest answer to a question the dataset cannot close on its own.
   */
  thin?: string | null;
}

const round1 = (n: number) => Math.round(n * 10) / 10;
const pct = (a: number, b: number) => (b === 0 ? 0 : Math.round((a / b) * 100));

/** Vendors only, never the investors or the services channel. */
export const aiVendors = (m: MarketMetrics): VendorMetrics[] =>
  m.vendors.filter((v) => v.category !== "AI investor");

/** A category leader and how defensible the lead looks. */
export interface CategoryLead {
  category: string;
  leader: string;
  score: number;
  /** The runner-up, so a lead can be described rather than just asserted. */
  runnerUp: string | null;
  gap: number | null;
  /** How many scored vendors the category holds, so a lead of one is visible. */
  contested: number;
}

export interface MarketTake {
  leads: CategoryLead[];
  /** Leads with a runner-up within three points: genuinely open categories. */
  close: CategoryLead[];
  /** Leads clear by ten points or more. */
  clear: CategoryLead[];
  gaining: string[];
  slipping: string[];
  strongButRisky: VendorMetrics[];
}

/**
 * An analyst's read of who is where, named.
 *
 * The insights used to describe the instrument: how to read the table, what
 * the composite does not net off, which columns are comparable. All true, and
 * all of it answered a question the reader had not asked. Somebody arriving at
 * a vendor page wants to know who is ahead and whether the lead means anything,
 * and got a methodology note instead.
 *
 * This computes the substance so the copy can lead with it. The cautions are
 * still carried, underneath, where a caution belongs once the finding is made.
 *
 * Every figure here is read off the scored set. Nothing is inferred about a
 * vendor that carries no score, and a category with one scored vendor reports
 * `runnerUp: null` rather than implying a contest that has one entrant.
 */
export function marketTake(m: MarketMetrics): MarketTake {
  const scored = aiVendors(m).filter((v) => v.composite !== null);

  // THE ASSESSMENT, AND THE MARKETS IT IS SCORED IN.
  //
  // This read overallScore grouped by the vendor record's single `category`
  // field until 17 August 2026. That produced prose about "10 market
  // categories" and a "14.7 point lead" beside a table ranked out of 5 across
  // thirteen markets: the same page describing two different worlds.
  //
  // Both now come from categoryComposites, which is the assessment keyed by
  // market, so the sentence and the table are reading the same numbers. Gaps
  // are on the 0 to 5 scale and are small by comparison: a 0.29 lead in
  // frontier models is the one the comparison calls decisive.
  const nameOf = new Map(m.vendors.map((v) => [v.id, v.name]));
  // Market LABELS, never ids. "workflow_automation_ai" in a sentence a reader
  // is meant to act on is a leaked internal key, and this printed one.
  const labelOf = new Map(MARKET_CATEGORY_LIST.map((c) => [c.id, c.name]));
  const eligible = new Set(scored.map((v) => v.id));

  const leads: CategoryLead[] = [];
  for (const [categoryId, placements] of Object.entries(m.categoryComposites)) {
    const ranked = Object.entries(placements)
      .filter(([vendorId]) => eligible.has(vendorId))
      .sort((a, b) => a[1].rank - b[1].rank);
    if (ranked.length === 0) continue;
    const [topId, top] = ranked[0];
    const second = ranked[1] ?? null;
    leads.push({
      category: labelOf.get(categoryId) ?? categoryId,
      leader: nameOf.get(topId) ?? topId,
      score: top.composite,
      runnerUp: second ? (nameOf.get(second[0]) ?? second[0]) : null,
      // Two decimals: on a 0 to 5 scale a gap rounded to one decimal turns
      // 0.29 into 0.3 and a real separation into a rounding artefact.
      gap: second ? Math.round((top.composite - second[1].composite) * 100) / 100 : null,
      contested: ranked.length,
    });
  }
  // Widest lead first: the most defensible position is the most useful thing
  // to say first, and the closest races are the most useful thing to say last.
  leads.sort((a, b) => (b.gap ?? -1) - (a.gap ?? -1));

  const withRisk = new Set(m.risks.map((r) => r.vendorId));

  return {
    leads,
    // Rescaled with the metric. These were 3 and 10 on a 0 to 100 score; left
    // alone against a 0 to 5 assessment every market would read as "close" and
    // none as "clear", because the widest gap in the set is under one point.
    //
    // 0.15 and 0.50 are the same proportions of the scale the old numbers were
    // of theirs. On today's data that makes frontier models clear at 0.29 and
    // the tightest markets close, which is the reading the comparison gives.
    close: leads.filter((l) => l.gap !== null && l.gap <= 0.15),
    clear: leads.filter((l) => l.gap !== null && l.gap >= 0.5),
    gaining: m.gaining.map((s) => s.vendorName),
    slipping: m.slipping.map((s) => s.vendorName),
    strongButRisky: scored.filter(
      (v) => (v.composite ?? 0) >= 60 && withRisk.has(v.id)
    ),
  };
}

/** "A, B and C", or "A and B", or "A". British English list. */
export function nameList(names: string[], max = 3): string {
  const shown = names.slice(0, max);
  if (shown.length === 0) return "";
  if (shown.length === 1) return shown[0];
  const over = names.length - max;
  // "1 others" shipped once. Singular and plural both matter in copy a reader
  // is meant to trust with figures.
  if (over > 0) {
    return `${shown.join(", ")} and ${over} ${over === 1 ? "other" : "others"}`;
  }
  return `${shown.slice(0, -1).join(", ")} and ${shown[shown.length - 1]}`;
}

function insufficient(
  reason: string,
  sources: string[],
  lane: DataLane
): AnalystInsightData {
  return {
    headline: "",
    summary: "",
    implications: [],
    action: "Monitor",
    news: null,
    evidence: { count: 0, sources, lastUpdated: null, lane },
    insufficient: reason,
  };
}

// ----------------------------------------------------------------- contexts

/**
 * Market Watch: where share sits and whether the field is opening or closing.
 */
export function marketWatchInsight(
  m: MarketMetrics,
  news: InsightNews | null = null
): AnalystInsightData {
  const vendors = aiVendors(m);
  const byCategory = new Map<string, number[]>();
  for (const s of m.shares) {
    if (typeof s.estimatedShare !== "number") continue;
    const list = byCategory.get(s.categoryId) ?? [];
    list.push(s.estimatedShare);
    byCategory.set(s.categoryId, list);
  }
  const concentrations = [...byCategory.values()]
    .filter((l) => l.length >= 3)
    .map((l) => [...l].sort((a, b) => b - a).slice(0, 3).reduce((a, b) => a + b, 0))
    .sort((a, b) => a - b);

  if (concentrations.length === 0) {
    return insufficient(
      "Fewer than one market category carries three or more share estimates, so concentration cannot be read and no conclusion is drawn about the shape of the field.",
      ["AIE market share estimates"],
      m.lane
    );
  }

  const median = round1(concentrations[Math.floor(concentrations.length / 2)]);
  const gaining = m.gaining.length;
  const slipping = m.slipping.length;
  const tight = median >= 70;

  return {
    headline: tight
      ? "Category share is concentrated enough that most buyers are negotiating against two or three real options, not a field."
      : "Category share is spread widely enough that buyers still have alternatives to negotiate against.",
    summary: `In a typical tracked category the three largest vendors hold about ${median} per cent of estimated share, measured across ${concentrations.length} categories with enough estimates to judge. ${
      gaining + slipping > 0
        ? `${gaining} vendors are currently classified as gaining position and ${slipping} as slipping, so the ordering inside categories is still moving even where the totals are not.`
        : "No vendor is currently classified as gaining or slipping, so the ordering inside categories is steady."
    } ${
      tight
        ? "Concentration at this level shortens a buyer's list before procurement begins, and it is the reason renewal terms tend to harden in these categories. The practical response is to keep a credible second option warm even when the incumbent is performing, because the cost of having none appears at renewal rather than at deployment."
        : "A spread field is where commercial leverage actually lives. It is worth testing an alternative before each renewal even when the incumbent is adequate, because the option only has value if it is real."
    } Share is estimated per category and never pooled across them, since the categories do not sum to a single market.`,
    implications: [
      tight
        ? "Concentration limits negotiating leverage in the categories where it is highest."
        : "Alternatives exist in most categories, so renewal terms are contestable.",
      gaining >= slipping
        ? "Positions are still moving, so a shortlist closed two quarters ago is likely to be out of date."
        : "More vendors are slipping than gaining, which narrows the credible field over time.",
      "Share is an estimate per category, so it supports a direction of travel rather than a precise ranking.",
    ],
    action: tight ? "Investigate" : "Monitor",
    tools: ["competitiveIntel", "vendorView", "modelForRole"],
    news,
    evidence: {
      count: m.shares.length,
      sources: [
        "AIE market share estimates",
        "AIE vendor movement classification",
      ],
      lastUpdated: m.shareAsOf ?? m.generatedAt,
      lane: m.lane,
    },
    insufficient: null,
    // The source is an estimate by its own account: lib/aie market share is
    // modelled from ingested signals, not measured revenue.
    thin: "category share here is a modelled estimate rather than a measured figure",
  };
}

/**
 * Financial Snapshot: what the filings do and do not say.
 *
 * The strongest finding here is an absence, so it leads.
 */
export function financialInsight(
  news: InsightNews | null,
  disclosure: { disclosing: number; total: number } | null,
  segmentsFiled: number,
  segmentTotal: number,
  capturedAt: string | null,
  /**
   * The private side, when the page holds it. Omitted, the insight says
   * nothing about private vendors rather than guessing at them.
   *
   * This parameter exists because the original copy stated that no range and
   * no modelled figure was ever substituted for a silent vendor. That was true
   * when written and stopped being true when the private-revenue estimator
   * shipped: the page now shows a band for private companies. An insight that
   * denies what the panel beneath it is doing is worse than no insight.
   */
  privateSide?: {
    /** Private vendors stating a figure themselves. */
    stated: number;
    /** Private vendors with nothing to state and no basis to estimate from. */
    notEstimable: number;
    /** The revenue multiple band the estimator will quote, low to high. */
    band: { low: number; high: number };
  }
): AnalystInsightData {
  if (!disclosure || disclosure.total === 0) {
    return insufficient(
      "No filing capture is currently held, so nothing can be said about the financial footing behind the vendor set.",
      ["SEC filings"],
      "aie"
    );
  }
  const undisclosed = disclosure.total - disclosure.disclosing;
  const share = pct(disclosure.disclosing, disclosure.total);

  return {
    headline:
      undisclosed > disclosure.disclosing
        ? "Most of the AI market's revenue claims are not in anyone's filings, which is a procurement problem before it is a finance one."
        : "A majority of tracked vendors now quantify AI revenue in their filings, which makes their commercial claims checkable.",
    summary: `Of ${disclosure.total} tracked public vendors, ${disclosure.disclosing} state a quantified AI revenue figure in their filings and ${undisclosed} state none. ${segmentTotal > 0 ? `${segmentsFiled} of ${segmentTotal} break revenue down by segment, which is as close as most get to showing where AI money actually lands. ` : ""}That ${share} per cent disclosure rate is the useful number here, and it is low enough to change how a vendor's commercial claims should be treated in a sales cycle: a growth figure quoted in a pitch that does not appear in a filing has not been audited by anyone, and for a multi-year commitment that distinction matters more than the figure itself. ${
      privateSide
        ? `On the private side, ${privateSide.stated} companies state a figure themselves and ${privateSide.notEstimable} give nothing to work from. Where a private company is silent but a dated valuation exists, this page shows a revenue band derived from the ${privateSide.band.low}x to ${privateSide.band.high}x range observed across comparable disclosed pairs, shown as a band, never as a point, and never mixed into a filed figure. A band is an argument about magnitude, not a measurement, and it is labelled as one.`
        : "Private vendors file nothing and sit outside this entirely rather than being estimated into it."
    }`,
    implications: [
      `${undisclosed} of ${disclosure.total} tracked vendors publish no AI revenue figure, so their traction claims are unverifiable from public sources.`,
      "Treat vendor-supplied growth and scale numbers as unaudited unless the filing carries them.",
      privateSide
        ? `Private revenue is banded from observed multiples, never filed: read the ${privateSide.band.low}x-${privateSide.band.high}x range as magnitude, not measurement.`
        : "Private vendors are outside this entirely, so absence here is not a signal about them either way.",
    ],
    action: undisclosed > disclosure.disclosing ? "Investigate" : "Monitor",
    tools: ["vendorView", "competitiveIntel"],
    news,
    evidence: {
      count: disclosure.total + segmentTotal,
      sources: ["SEC filings, full-text search", "SEC segment revenue extraction"],
      lastUpdated: capturedAt,
      lane: "aie",
    },
    insufficient: null,
    // Most of the market files no figure at all, so the strongest thing on
    // this page is an absence. An absence is a finding, and it is also the
    // point at which a reader needs someone who can go and ask.
    thin:
      undisclosed > disclosure.disclosing
        ? `${undisclosed} of ${disclosure.total} tracked vendors put no AI revenue figure in any filing`
        : null,
  };
}

/**
 * Competitive Intel: where capability actually differs between providers.
 */
export function competitiveInsight(
  m: MarketMetrics,
  news: InsightNews | null,
  categoryName: string | null,
  providerCount: number,
  capabilityCount: number
): AnalystInsightData {
  const vendors = aiVendors(m);
  const scored = vendors
    .filter((v) => v.maturity !== null)
    .sort((a, b) => (b.maturity ?? 0) - (a.maturity ?? 0));

  if (scored.length < 3) {
    return insufficient(
      "Fewer than three vendors carry an assessed capability score, so no comparison is drawn.",
      ["AIE capability matrix"],
      m.lane
    );
  }

  const top = scored[0];
  const median = scored[Math.floor(scored.length / 2)];
  const spread = round1((top.maturity ?? 0) - (median.maturity ?? 0));
  const narrow = spread < 15;

  return {
    headline: narrow
      ? "Capability between the leading providers has converged far enough that the choice is now made on control and cost, not on the model."
      : "Capability still separates the leading providers by enough to make the model choice consequential on its own.",
    summary: `Across ${providerCount} providers assessed on ${capabilityCount} capabilities${categoryName ? ` in ${categoryName}` : ""}, the strongest vendor scores ${top.maturity} for evidence-graded capability maturity against a median of ${median.maturity}, a spread of ${spread} points. ${
      narrow
        ? "A spread that narrow means the differentiator has moved off the model itself. Deployment options, governance depth, integration surface and commercial terms now decide more than raw capability does, and a shortlist built purely on capability scores will produce several indistinguishable finalists. That is a better position for a buyer than it looks, because it converts a technical decision into a commercial one."
        : "A spread that wide means the model choice still carries real weight, and a shortlist that treats the leaders as interchangeable will underperform. Capability should stay a primary filter here rather than a tiebreak."
    } Every score carries an evidence grade, and the weakest grade behind a vendor's mean is the honest ceiling on it. Vendors are compared inside a market category and never across one, since a chip maker and a CRM assistant are not competing for the same budget.`,
    implications: [
      narrow
        ? "Differentiation has moved from model capability to deployment, governance and price."
        : "Model capability remains a primary shortlist filter, not a tiebreak.",
      "Capability scores carry evidence grades, so a high score at thin evidence is a claim rather than a verified strength.",
      "Comparison holds within a market category only; scores do not transfer across categories.",
    ],
    action: narrow ? "Renegotiate" : "Shortlist",
    tools: ["modelForRole", "workflowShortlist"],
    news,
    evidence: {
      count: providerCount * capabilityCount,
      sources: ["AIE capability matrix", "AIE vendor rankings"],
      lastUpdated: m.generatedAt,
      lane: m.lane,
    },
    insufficient: null,
    // Every score is capped by the weakest evidence grade behind it, which
    // the summary already states as the honest ceiling on a vendor mean.
    thin: "each capability score is capped by its weakest evidence grade, and that grade differs by vendor",
  };
}

/**
 * Reputation Tracker: whether perception is telling you anything actionable.
 */
export function reputationInsight(
  m: MarketMetrics,
  news: InsightNews | null,
  snapshotCount: number,
  syntheticCount: number
): AnalystInsightData {
  const vendors = aiVendors(m).filter((v) => v.reputation !== null);
  if (vendors.length < 5) {
    return insufficient(
      "Fewer than five vendors carry a reputation reading, so no market-level conclusion is drawn.",
      ["AIE reputation pillars"],
      m.lane
    );
  }
  const sorted = [...vendors].sort((a, b) => (b.reputation ?? 0) - (a.reputation ?? 0));
  const mean = round1(
    vendors.reduce((a, v) => a + (v.reputation ?? 0), 0) / vendors.length
  );
  const spread = round1((sorted[0].reputation ?? 0) - (sorted[sorted.length - 1].reputation ?? 0));
  const realSnapshots = snapshotCount - syntheticCount;

  // Who is actually where, and on which pillar. The reading averaged three
  // pillars into one number and reported the spread; a reader wanting to know
  // whether their vendor has a support problem got a statistic about the set.
  const top = sorted.slice(0, 3).map((v) => v.name);
  const bottom = sorted.slice(-3).reverse().map((v) => v.name);

  const pillarMean = (k: "customer" | "developer" | "employee") => {
    const vals = vendors
      .map((v) => v.reputationPillars?.[k])
      .filter((n): n is number => typeof n === "number");
    return vals.length
      ? { mean: round1(vals.reduce((a, b) => a + b, 0) / vals.length), n: vals.length }
      : null;
  };
  const pillars = (
    [
      ["customer", pillarMean("customer")],
      ["developer", pillarMean("developer")],
      ["employee", pillarMean("employee")],
    ] as const
  ).filter((p): p is readonly [typeof p[0], { mean: number; n: number }] => p[1] !== null);
  const weakest = [...pillars].sort((a, b) => a[1].mean - b[1].mean)[0] ?? null;
  const strongest = [...pillars].sort((a, b) => b[1].mean - a[1].mean)[0] ?? null;

  return {
    // A judgement, not a league-table position. Who leads is in the
    // implications, where a reader can act on it; the headline is for what the
    // set as a whole says about buying in this market.
    headline:
      weakest && strongest && weakest[0] !== strongest[0]
        ? `This market is strongest on ${strongest[0]} experience and weakest on ${weakest[0]}, the pillar that bites after signature.`
        : spread > 25
          ? "Reputation separates these vendors further than capability does, and it moves too slowly to correct inside a procurement cycle."
          : "Reputation is banded too tightly here to rank vendors, though it will still disqualify one.",
    summary: `${vendors.length} vendors carry a reputation reading, averaging ${mean} across the customer, developer and employee pillars, with ${spread} points between the highest and lowest. ${nameList(top)} sit at the top of the set; ${nameList(bottom)} sit at the bottom${
      pillars.length === 3
        ? `. Read by pillar, the set scores ${pillars.map(([k, v]) => `${v.mean} on ${k}`).join(", ")}, so ${weakest ? `${weakest[0]} experience is where this market is collectively weakest, and the pillar most likely to bite after signature` : "no single pillar stands out"}`
        : ""
    }. ${
      spread > 25
        ? "A spread that wide is worth acting on: it reflects sustained differences in support quality, documentation and how vendors behave after the contract is signed, none of which appear in a capability score. Reputation is also the slowest of the tracked measures to move, so a low reading is unlikely to correct inside a procurement cycle."
        : "A band this narrow means reputation is better used to disqualify than to rank. It will flag a vendor with a genuine support or documentation problem, but it will not tell you which of two strong vendors to pick."
    } ${
      realSnapshots < 2
        ? "Only one real capture is held, so no trend is available yet and the reading is a point in time rather than a direction."
        : `${realSnapshots} real captures are now held, so a trend is beginning to form, though it is still too short to read confidently.`
    }${syntheticCount > 0 ? ` The chart also carries ${syntheticCount} illustrative quarters, drawn dashed and badged, which are not measurements.` : ""}`,
    implications: [
      `${sorted[0].name} leads on reputation at ${round1(sorted[0].reputation ?? 0)}; ${sorted[sorted.length - 1].name} trails at ${round1(sorted[sorted.length - 1].reputation ?? 0)}.`,
      weakest
        ? `The set is weakest on ${weakest[0]} (${weakest[1].mean} mean), the pillar most likely to bite after signature.`
        : "The pillars measure post-contract experience, which no capability score captures.",
      realSnapshots < 2
        ? "Only one real capture exists, so treat this as a point reading and not a trend."
        : "The trend is real but short; a direction will not be reliable for several more captures.",
    ],
    action: spread > 25 ? "Shortlist" : "Monitor",
    tools: ["vendorView", "decisionDesk"],
    news,
    evidence: {
      count: vendors.length,
      sources: ["AIE reputation pillars", "AG reputation snapshots"],
      lastUpdated: m.reputationAsOf ?? m.generatedAt,
      lane: m.lane,
    },
    insufficient: null,
    // One capture is a position, not a direction, and reputation is the
    // slowest measure here to move. A reader deciding on it needs the
    // trajectory, which no amount of reading this page will supply.
    thin:
      realSnapshots < 2
        ? "only one real capture is held, so this is a point reading with no trend behind it"
        : null,
  };
}

/**
 * Vendor View: what the ranking is and is not telling a buyer.
 */
export function vendorViewInsight(
  m: MarketMetrics,
  news: InsightNews | null = null
): AnalystInsightData {
  const vendors = aiVendors(m);
  const scored = vendors.filter((v) => v.composite !== null);
  if (scored.length < 5) {
    return insufficient(
      "Fewer than five vendors carry a composite score, so no ranking-level conclusion is drawn.",
      ["AIE vendor rankings"],
      m.lane
    );
  }
  const take = marketTake(m);
  const { strongButRisky, clear, close } = take;
  const noMomentum = scored.filter((v) => v.momentum === null).length;
  // Markets the assessment scores in, not distinct values of the vendor
  // record's single category field. The two differ: 13 against 10, and the
  // table beside this sentence groups by the first.
  const categories = take.leads.length;

  // The widest and the tightest category, named. These are the two facts a
  // reader can act on: where the incumbent is unassailable and where a second
  // quote is worth getting.
  const widest = clear[0] ?? null;
  const tightest = close[close.length - 1] ?? null;

  return {
    headline: widest
      ? `${widest.leader} holds the clearest position of any vendor tracked, and ${close.length > 0 ? `${close.length} other categories are close enough to contest` : "no category is close enough to contest"}.`
      : close.length > 0
        ? `No vendor holds a decisive lead in its category, and ${close.length} categories are within three points at the top.`
        : "Category positions are settled enough that no lead is currently being contested.",
    summary: `${scored.length} vendors carry a composite score across ${categories} market categories. ${
      widest
        ? `The most defensible position is ${widest.leader} in ${widest.category}, scoring ${widest.score} with ${widest.runnerUp} ${widest.gap} points behind. A gap that size is not closed in a quarter, and a buyer in that category is negotiating with an incumbent rather than choosing between options. `
        : ""
    }${
      tightest
        ? `The closest contest is ${tightest.category}, where ${tightest.leader} leads ${tightest.runnerUp} by ${tightest.gap}: inside the margin the evidence can carry, so treat those two as equivalent on score and decide on fit, governance and price. `
        : ""
    }${
      take.gaining.length > 0 || take.slipping.length > 0
        ? `${take.gaining.length > 0 ? `${nameList(take.gaining)} ${take.gaining.length === 1 ? "is" : "are"} gaining position` : ""}${take.gaining.length > 0 && take.slipping.length > 0 ? ", and " : ""}${take.slipping.length > 0 ? `${nameList(take.slipping)} ${take.slipping.length === 1 ? "is" : "are"} slipping` : ""}. `
        : ""
    }${
      strongButRisky.length > 0
        ? `${nameList(strongButRisky.map((v) => v.name))} score 60 or above while carrying an open high-severity risk. The composite measures capability and standing and does not net off governance exposure, so those vendors rank well and may still be the wrong commitment this quarter.`
        : "No vendor combines a shortlist-grade score with an open high-severity risk, so the ranking can be read at face value this period."
    }${
      noMomentum > 0
        ? ` Momentum is published for ${scored.length - noMomentum} of the ${scored.length} scored vendors, so ${noMomentum} show no movement reading rather than a flat one.`
        : ""
    } Every comparison above is inside a market category and never across one, which is why the table groups rather than producing a single ranking.`,
    implications: [
      widest
        ? `${widest.leader} leads ${widest.category} by ${widest.gap} points; expect incumbent pricing there.`
        : "No category has a decisive leader; leverage exists in all of them.",
      tightest
        ? `${tightest.leader} and ${tightest.runnerUp} are within ${tightest.gap} points in ${tightest.category}, so decide on fit, not score.`
        : "Scores compare within a market category only, never across one.",
      strongButRisky.length > 0
        ? `A high composite does not clear a vendor: ${nameList(strongButRisky.map((v) => v.name), 2)} carry open risks.`
        : noMomentum > 0
          ? `${noMomentum} vendors publish no momentum reading, which is an absence rather than a flat trend.`
          : "Momentum is published across the scored set.",
    ],
    action: strongButRisky.length > 0 ? "Investigate" : "Shortlist",
    tools: ["competitiveIntel", "workflowShortlist", "modelForRole"],
    news,
    evidence: {
      count: scored.length,
      sources: ["AIE vendor rankings", "AIE risk register"],
      lastUpdated: m.generatedAt,
      lane: m.lane,
    },
    insufficient: null,
    // Coverage differs by vendor, because the composite renormalises over
    // whichever of the three inputs a vendor actually discloses.
    thin: "the composite scores only the inputs each vendor discloses, so coverage differs from vendor to vendor",
  };
}

/**
 * Trust Rank and the Security Desk: governance exposure.
 */
export function governanceInsight(
  m: MarketMetrics,
  news: InsightNews | null,
  jurisdictions: number,
  sourcedJurisdictions: number,
  label: "governance" | "security"
): AnalystInsightData {
  const openRisks = m.risks.length;
  const highSeverity = m.risks.filter(
    (r) => (r.severity ?? "").toLowerCase() === "high"
  ).length;
  const affected = new Set(m.risks.map((r) => r.vendorId)).size;

  return {
    headline:
      highSeverity > 0
        ? `${highSeverity} high-severity ${highSeverity === 1 ? "risk is" : "risks are"} open across ${affected} tracked ${affected === 1 ? "vendor" : "vendors"}, which belongs in the shortlist stage rather than after it.`
        : "No high-severity risk is currently open against a tracked vendor, which makes this the cheapest moment to tighten the review cadence rather than relax it.",
    summary: `${openRisks} ${openRisks === 1 ? "risk is" : "risks are"} currently recorded against tracked vendors, ${highSeverity} of them high severity, touching ${affected} ${affected === 1 ? "vendor" : "vendors"}. ${
      highSeverity > 0
        ? "Governance findings behave differently from capability gaps: they rarely close on the vendor's own timetable, and the cost of discovering one after a commitment is far higher than the cost of raising it during evaluation. The practical move is to require a dated remediation position from each affected vendor before scope widens, rather than accepting an assurance that the issue is understood."
        : "An empty high-severity list is a reason to keep the cadence, not to stand it down. Risk registers are lagging by construction, and the absence of a recorded finding is weaker evidence than the presence of one."
    } ${label === "governance" ? `On the regulatory side, ${sourcedJurisdictions} of ${jurisdictions} tracked jurisdictions carry a dataset-sourced entry and the remainder are marked as unsourced rather than presented as verified.` : ""}`,
    implications: [
      highSeverity > 0
        ? "Require a dated remediation position from affected vendors before widening scope."
        : "Keep the review cadence: an empty register is weaker evidence than a populated one.",
      "Governance findings rarely resolve inside a procurement cycle, so they belong in shortlisting.",
      label === "governance"
        ? `${jurisdictions - sourcedJurisdictions} of ${jurisdictions} jurisdictions carry no dataset source and are marked accordingly.`
        : "Posture assessments are per-vendor and carry their own evidence state.",
    ],
    action: highSeverity > 0 ? "Investigate" : "Monitor",
    tools: ["securityDesk", "vendorView"],
    news,
    evidence: {
      count: openRisks + jurisdictions,
      sources: ["AIE risk register", "AIE regulatory grid"],
      lastUpdated: m.generatedAt,
      lane: m.lane,
    },
    insufficient: null,
    // Lagging by construction: an empty register is weaker evidence than a
    // populated one, and the copy above says so.
    thin: "risk registers lag by construction, so an absent finding is weaker evidence than a recorded one",
  };
}

/**
 * Alliances and Ecosystem Navigator: how much of the supply map is verified.
 *
 * Takes primitives rather than each page's own types, so a page passes what it
 * already has and no page's internals leak into this module.
 */
export function supplyMapInsight(
  opts: {
    edges: number;
    verified: number;
    seed: number;
    nodes: number;
    label: "alliance" | "dependency";
    /**
     * How many distinct delivery partners carry each vendor, widest first.
     * This is the finding on this page. An earlier version of this insight
     * reported our own verification rate instead, which told a reader how much
     * data we hold rather than what the channel does to their options.
     */
    breadth?: { vendor: string; partners: number }[];
    /** The partner carrying the most vendors, which is where the channel narrows. */
    busiest?: { partner: string; vendors: number } | null;
  },
  news: InsightNews | null,
  lastUpdated: string | null
): AnalystInsightData {
  const { edges, verified, nodes, label, breadth = [], busiest = null } = opts;
  if (edges === 0) {
    return insufficient(
      `No ${label} links are currently recorded, so nothing can be said about who would actually deliver these vendors.`,
      ["AIE exposure map"],
      "aie"
    );
  }

  const verifiedPct = pct(verified, edges);
  const widest = breadth[0] ?? null;
  const soleSourced = breadth.filter((b) => b.partners === 1);
  const narrow = soleSourced.length > 0;

  // The caveat, carried as a clause rather than as the subject. Our confidence
  // in the map is a footnote to what the map says.
  const caution =
    verifiedPct < 50
      ? ` Under half of these links are confirmed directly by the parties, so treat the thinner end of this list as a question for procurement rather than a finding.`
      : ` Most of these links are confirmed directly by the parties, so the shape is firm enough to plan against.`;

  return {
    headline: narrow
      ? `Choosing some of these vendors also chooses who delivers them, because only one firm does that work.`
      : `Every tracked vendor here has more than one firm able to deliver it, so delivery is not the constraint.`,
    summary: `${nodes} delivery firms carry the ${edges} vendor relationships tracked here.${
      widest
        ? ` ${widest.vendor} is carried by ${widest.partners}, the widest channel of any vendor on this page.`
        : ""
    }${
      narrow
        ? ` ${soleSourced.length === 1 ? `One vendor has` : `${soleSourced.length} vendors have`} a single firm carrying them, which converts a software decision into a supplier decision: the commercial terms you negotiate with the vendor are not the terms you will get on the engagement, because there is no second bidder for the work.`
        : ` No vendor here depends on a single firm, which keeps implementation competitive and is the condition under which vendor pricing power actually transfers to you.`
    }${
      busiest
        ? ` ${busiest.partner} carries ${busiest.vendors} of them, so a shortlist drawn on capability alone can arrive at several vendors and one delivery team.`
        : ""
    } This is the layer buyers price last and discover first: an enterprise rarely stands a frontier model up alone, and the scarce input in this market has moved from the model to the people who can deploy it.${caution}`,
    implications: [
      narrow
        ? "Check whether your preferred vendor has a second firm able to deliver it before you negotiate."
        : "Run implementation as its own competitive process, not as an extension of the vendor selection.",
      "A capability shortlist can converge on one delivery team without anyone noticing.",
      "Delivery concentration shows up as correlated delay, which no vendor score captures.",
    ],
    action: narrow ? "Investigate" : "Monitor",
    tools: ["workflowShortlist", "vendorView"],
    news,
    evidence: {
      count: edges,
      sources: ["AIE exposure map", "AIE dependency graph"],
      lastUpdated,
      lane: "aie",
    },
    insufficient: null,
    // Under half the links confirmed by the parties themselves. The shape is
    // worth acting on; a specific vendor's delivery options are not settled by
    // it, and that is exactly the question an analyst can close and a seed
    // record cannot.
    thin:
      verifiedPct < 50
        ? "under half of these delivery links are confirmed by the parties themselves"
        : null,
  };
}

/** FitEngine: whether the workflow catalogue can answer a buying question. */
export function workflowInsight(
  opts: { workflows: number; categories: number; mapped: number; highRisk: number },
  news: InsightNews | null,
  lastUpdated: string | null
): AnalystInsightData {
  const { workflows, categories, mapped, highRisk } = opts;
  if (workflows === 0) {
    return insufficient(
      "No workflows are catalogued, so no tier or vendor recommendation can be made.",
      ["AIE workflow catalogue"],
      "aie"
    );
  }
  const riskShare = pct(highRisk, workflows);

  return {
    headline:
      riskShare >= 40
        ? "Most catalogued workflows sit at high risk or above, so model choice here is a governance decision before it is a capability one."
        : "Most catalogued workflows sit below the high-risk line, so tiering can be driven by cost rather than by assurance.",
    summary: `${workflows} workflows across ${categories} categories, ${highRisk} of them at high or critical risk, which is ${riskShare} per cent of the catalogue. ${mapped} categories carry a vendor mapping. ${
      riskShare >= 40
        ? "A catalogue weighted this far toward high risk changes where the money goes: the constraint is assurance rather than inference cost, and the cheapest adequate model is the wrong answer wherever a wrong output carries legal or clinical consequence. Tier on risk first, then on cost within each tier."
        : "With most work below the high-risk line, the tiering decision is genuinely commercial. Reserve the top tier for the minority of workflows that need it and let cost drive the rest, which is where the savings actually are."
    } The tier a workflow needs is read from its recorded risk and complexity, not from which vendor is currently strongest.`,
    implications: [
      `${highRisk} of ${workflows} catalogued workflows are high or critical risk.`,
      riskShare >= 40
        ? "Assurance, not inference cost, is the binding constraint on most of this catalogue."
        : "Cost can drive tiering across most of the catalogue; reserve the top tier for the minority that need it.",
      "Tier follows recorded risk and complexity, not vendor strength.",
    ],
    action: riskShare >= 40 ? "Investigate" : "Accelerate",
    tools: ["modelForRole", "competitiveIntel"],
    news,
    evidence: {
      count: workflows,
      sources: ["AIE workflow catalogue", "AIE vendor market categories"],
      lastUpdated,
      lane: "aie",
    },
    insufficient: null,
    // Types, not deployments. Which firms actually run a workflow is not in
    // the catalogue and cannot be derived from it.
    thin: "this catalogue holds workflow types rather than observed deployments",
  };
}

/** News: what the flow of events is actually telling a buyer. */
/**
 * What the news cycle is about, and whether it touches this reader.
 *
 * `watchedVendorIds` is the shortlist mirrored into a cookie by
 * lib/shortlist.tsx. It is a browser, not an identity: there is no account
 * here, so this personalises a page and can post to nobody.
 *
 * An empty watchlist is a normal first visit, not a gap. The reader is told
 * what the cycle is doing and invited to build a list, because an empty
 * "affects you" panel teaches somebody the feature is broken rather than
 * unfilled, the same rule the Pulse follows.
 */
export function newsInsight(
  items: NewsItemRaw[],
  lastUpdated: string | null,
  watchedVendorIds: string[] = []
): AnalystInsightData {
  if (items.length < 10) {
    return insufficient(
      "Too few items are held to read a direction from the news flow.",
      ["AIE news feed"],
      "aie-live"
    );
  }
  const neg = items.filter((n) => n.sentiment === "negative").length;
  const pos = items.filter((n) => n.sentiment === "positive").length;
  const highImpact = items.filter((n) => (n.impactScore ?? 0) >= 75).length;
  const negShare = pct(neg, items.length);
  const risky = items.filter((n) => (n.categories ?? []).includes("Risk event")).length;

  // What the cycle is *about*. Counting sentiment says whether the mood moved;
  // it never says what happened. The source tags every item with categories
  // and vendors, and reading those is the difference between "the flow is 14
  // per cent negative" and "this fortnight is product launches and funding".
  const themeCount = new Map<string, number>();
  for (const n of items)
    for (const c of n.categories ?? [])
      themeCount.set(c, (themeCount.get(c) ?? 0) + 1);
  const themes = [...themeCount.entries()]
    .sort((a, b) => b[1] - a[1])
    .slice(0, 3);

  const vendorCount = new Map<string, number>();
  for (const n of items)
    for (const v of n.vendors ?? [])
      vendorCount.set(v, (vendorCount.get(v) ?? 0) + 1);
  // The feed carries vendor ids. Printing "openai" to a reader who has only
  // ever seen "OpenAI" reads as a leaked internal key, so names are resolved
  // through the directory, which falls back to the id rather than to blank.
  const loudest = [...vendorCount.entries()]
    .sort((a, b) => b[1] - a[1])
    .slice(0, 3)
    .map(([id, n]) => [vendorName(id), n] as const);

  // Does any of it bear on this reader. Matching is on the vendor ids the feed
  // carries, so a watched vendor the feed never names simply does not appear,
  // which is a true "nothing this cycle", not a miss.
  const watched = new Set(watchedVendorIds);
  const mine = watched.size
    ? items.filter((n) => (n.vendors ?? []).some((v) => watched.has(v)))
    : [];
  const mineNames = [
    ...new Set(
      mine.flatMap((n) => (n.vendors ?? []).filter((v) => watched.has(v)))
    ),
  ].map(vendorName);
  const mineNegative = mine.filter((n) => n.sentiment === "negative").length;
  const mineHigh = mine
    .filter((n) => (n.impactScore ?? 0) >= 75)
    .sort((a, b) => (b.impactScore ?? 0) - (a.impactScore ?? 0))[0];

  const themeText = themes.length
    ? themes.map(([t, n]) => `${t.toLowerCase()} (${n})`).join(", ")
    : "no dominant theme";

  return {
    headline: watched.size === 0
      ? `This cycle is mostly ${themes[0]?.[0].toLowerCase() ?? "mixed reporting"}, and ${loudest.length ? `${loudest[0][0]} is named more than any other vendor` : "no vendor dominates the coverage"}.`
      : mine.length === 0
        ? "Nothing in the current cycle names a vendor on your list, which is a quiet fortnight for your shortlist rather than a gap in the feed."
        : mineNegative > 0
          ? `${mine.length} items name vendors on your list, and ${mineNegative} of them ${mineNegative === 1 ? "is" : "are"} negative, worth reading before your next review.`
          : `${mine.length} items name vendors on your list and none of them are negative.`,
    summary: `${items.length} items in the current window. The cycle is running on ${themeText}, with ${loudest.length ? `${nameList(loudest.map(([v]) => v))} named most often` : "coverage spread thinly across vendors"}. Sentiment is ${pos} positive against ${neg} negative, ${highImpact} items scored at high impact and ${risky} classified as risk events, a negative share of ${negShare} per cent, ${
      negShare >= 25
        ? "high enough to read rather than dismiss"
        : "within the range of ordinary product and funding cycles"
    }. ${
      watched.size === 0
        ? "Nothing here is filtered to you yet. Add vendors to your shortlist and this panel will tell you which of the cycle actually touches them, rather than leaving you to scan the feed for names you recognise."
        : mine.length === 0
          ? `None of the ${watched.size} vendors on your list ${watched.size === 1 ? "is" : "are"} named in the current window. That is a real absence rather than a filtering failure: the feed names vendors explicitly, so silence here means the cycle went elsewhere.`
          : `${mine.length} of those items name ${nameList(mineNames)} from your list${mineNegative > 0 ? `, ${mineNegative} of them negative` : ", none of them negative"}.${mineHigh ? ` The highest-impact one is "${mineHigh.title}".` : ""}`
    } News is the earliest signal in this platform and the least verified: a single well-covered incident moves the mix without changing anything structural. Where it disagrees with a scored assessment, the assessment is usually right and the news is usually earlier.`,
    implications: [
      themes.length
        ? `The cycle is led by ${themes[0][0].toLowerCase()}: ${themes[0][1]} of ${items.length} items.`
        : `${negShare} per cent of current items are negative.`,
      watched.size === 0
        ? "Nothing is filtered to your vendors yet: build a shortlist to make this panel yours."
        : mine.length === 0
          ? `No item names your ${watched.size} watched ${watched.size === 1 ? "vendor" : "vendors"} this window.`
          : `${mine.length} items touch your list${mineNegative > 0 ? `, ${mineNegative} negative` : ""}.`,
      "Where news and assessment disagree, the assessment is usually right and the news usually earlier.",
    ],
    action: mineNegative > 0 || negShare >= 25 ? "Investigate" : "Monitor",
    tools: ["marketWatch", "vendorView"],
    news: pickNews(items, { minImpact: 75 }),
    evidence: {
      count: items.length,
      sources: ["AIE news feed"],
      lastUpdated,
      lane: "aie-live",
    },
    insufficient: null,
    // A quiet window for this reader's list is a real absence rather than a
    // filtering failure, and it is also the moment the feed stops being able
    // to help them.
    thin:
      watched.size > 0 && mine.length === 0
        ? "nothing in the current window names a vendor on your list"
        : null,
  };
}

/** Price / Performance: the cost of the last increment of capability. */
export function pricePerformanceInsight(
  opts: { models: number; vendors: number; ratio: number | null; adequate: number },
  news: InsightNews | null,
  lastUpdated: string | null
): AnalystInsightData {
  const { models, vendors, ratio, adequate } = opts;
  if (ratio === null) {
    return insufficient(
      "Not enough models carry both a published price and a benchmark score to compare capability against cost.",
      ["Artificial Analysis benchmark", "Vendor pricing pages"],
      "derived"
    );
  }
  const wide = ratio >= 5;

  return {
    headline: wide
      ? "The last increment of capability now costs an order of magnitude more than the rest of the curve, which makes tiering the largest available saving."
      : "The price gap between the best model and a near-equivalent is too narrow to fund tiering on cost alone.",
    summary: `${models} models from ${vendors} vendors carry both a published price and a benchmark score. ${adequate} of them reach 80 per cent of the top score, and the cheapest costs ${ratio} times less than the top model. ${
      wide
        ? "A multiple that large is the single most actionable figure on this page. It means the top tier should be reserved rather than defaulted to, and that a workload priced earlier in the year is probably sitting two steps above what it needs. The saving does not require changing vendor, only changing which model a workload routes to."
        : "A narrow multiple means the tiering argument does not pay for itself here, and the choice should be made on fit, latency and governance instead. Revisit when the spread widens."
    } Input price only: output tokens are priced separately and the mix varies by workload, so a blended figure would imply a workload this has not measured.`,
    implications: [
      `${adequate} models reach 80 per cent of the top benchmark score; the cheapest costs ${ratio}x less than the top.`,
      wide
        ? "Reserve the top tier rather than defaulting to it; the saving needs no vendor change."
        : "Tiering does not pay for itself at this spread; choose on fit and governance.",
      "Input price only, so test against your own token mix before committing.",
    ],
    action: wide ? "Renegotiate" : "Monitor",
    tools: ["modelForRole", "workflowShortlist"],
    news,
    evidence: {
      count: models,
      sources: ["Artificial Analysis benchmark", "Vendor pricing pages"],
      lastUpdated,
      lane: "derived",
    },
    insufficient: null,
    // Input tokens only. A real workload's blend of input and output moves
    // the answer, and the catalogue holds no output prices to compute it.
    thin: "this prices input tokens only, and the blend a real workload runs at is not in the catalogue",
  };
}

/**
 * Your AI Position: what the market did, read for a buyer.
 *
 * This page used to open with an editorial paragraph written into the Shell
 * fixture and badged SAMPLE, which meant the one tab about the reader's own
 * position carried the only insight in the product that was not computed from
 * anything, and it was dated the day the fixture was written.
 *
 * Deliberately built from market figures rather than company figures. The
 * platform cannot get buyer-level data for a real customer, so an insight that
 * needed it would work for the exemplar and nobody else. What the market did
 * is real for every reader, and it is the half of "your position" this product
 * can actually evidence.
 */
export function positionInsight(
  m: MarketMetrics,
  opts: { movedSignals: number; watchedVendors: number },
  news: InsightNews | null
): AnalystInsightData {
  const vendors = aiVendors(m);
  const scored = vendors.filter((v) => typeof v.composite === "number");
  if (scored.length === 0) {
    return insufficient(
      "No tracked vendor currently carries a composite score, so there is no market position to read your own against.",
      ["AIE vendor scores"],
      m.lane
    );
  }

  const scores = scored
    .map((v) => v.composite as number)
    .sort((a, b) => a - b);
  const median = round1(scores[Math.floor(scores.length / 2)]);
  const top = round1(scores[scores.length - 1]);
  const spread = round1(top - scores[0]);
  const moving = m.gaining.length + m.slipping.length;

  return {
    headline:
      spread >= 30
        ? "The tracked field is spread widely enough that vendor choice still changes the outcome more than execution does."
        : "The tracked field has converged far enough that execution, not vendor choice, is now the variable you control.",
    summary: `${scored.length} vendors carry a composite score, with a median of ${median} and a top of ${top}, a spread of ${spread} points. ${moving} moved position in the current period${
      opts.movedSignals > 0
        ? `, and ${opts.movedSignals} tracked figures moved since the previous capture`
        : ""
    }. ${
      spread >= 30
        ? "A spread that wide means the difference between a good and a poor choice is larger than most implementation risk, so diligence on the shortlist repays more than speed does."
        : "A narrow spread means the vendors at the top of your shortlist are closer than their marketing suggests, and the decision moves to switching cost, governance fit and what your own teams can actually run."
    } This reads the market, not your estate: nothing on this platform measures your own deployment, and the sections below are the exemplar buyer unless you have selected a company with published figures.`,
    implications: [
      `Median composite ${median}, top ${top}, spread ${spread} points across ${scored.length} vendors.`,
      spread >= 30
        ? "Vendor choice outweighs execution risk at this spread; spend the diligence."
        : "Vendors are closer than they claim; decide on switching cost and governance fit.",
      opts.watchedVendors > 0
        ? `You are watching ${opts.watchedVendors} of them; the Pulse lists what moved.`
        : "Add vendors to your shortlist and the Pulse will report what moves against them.",
    ],
    action: spread >= 30 ? "Investigate" : "Monitor",
    tools: ["decisionDesk", "workflowShortlist", "modelForRole"],
    news,
    evidence: {
      count: scored.length,
      sources: ["AIE vendor scores", "AIE movement classifications"],
      lastUpdated: m.generatedAt ?? null,
      lane: m.lane,
    },
    insufficient: null,
    // The composite renormalises over whichever inputs a vendor discloses,
    // so a spread is partly a statement about coverage.
    thin: "the composite scores only the inputs each vendor discloses, so this spread reflects coverage as well as position",
  };
}

/**
 * Peer Insights: what the sector view can and cannot settle.
 *
 * The page's own data is fetched per selection in the browser, so this is
 * deliberately about the shape of the answer rather than about one segment's
 * numbers. Asserting a ranking here would be worse than silent: the slice is a
 * modelled May 2026 estimate whose ordering two later measurements contradict,
 * and an insight that repeated the ordering as a finding would lend it
 * authority the data does not have.
 *
 * So it leads on the thing that is solid, what firms in a sector actually run
 * AI for, from the workflow library, and states the limit of the vendor slice
 * plainly.
 */
export function peerInsight(
  opts: {
    segments: number;
    workflows: number;
    horizontal: number;
    categories: number;
    /** Segments with at least one workflow tagged specifically to them. */
    segmentsWithSpecific: number;
  },
  news: InsightNews | null,
  lastUpdated: string | null
): AnalystInsightData {
  const { segments, workflows, horizontal, categories, segmentsWithSpecific } =
    opts;
  if (workflows === 0) {
    return insufficient(
      "The workflow library is empty, so nothing can be said about what any sector runs AI for.",
      ["AIE workflow taxonomy"],
      "aie"
    );
  }
  const specific = workflows - horizontal;
  const horizontalShare = pct(horizontal, workflows);

  return {
    headline:
      horizontalShare >= 60
        ? "Most of what your sector runs AI for is what every sector runs it for, and the difference is smaller than vendor pitches imply."
        : "Industry-specific workflows outnumber the common ones here, so a general-purpose shortlist will miss most of what your sector needs.",
    summary: `The workflow library holds ${workflows} enterprise AI workflows across ${categories} areas, mapped to ${segments} industry segments. ${horizontal} of them (${horizontalShare} per cent) run in every industry and ${specific} are tagged to particular sectors, with ${segmentsWithSpecific} of the ${segments} segments carrying at least one workflow of their own. ${
      horizontalShare >= 60
        ? "That balance is the useful finding: the bulk of enterprise AI work (summarisation, drafting, retrieval, support deflection) is the same everywhere, so the sector-specific list is where the genuine difference sits and is worth reading first even though it is shorter."
        : "The sector-specific list is the longer one here, so a shortlist built from general-purpose capability will under-serve the work your industry actually does."
    } These are workflow types, not observed deployments: the library says contract review is common in legal, never which firms run it, and this product holds no such record. The vendor slice on this page is a different kind of claim again: a modelled estimate dated May 2026, whose top-two ordering two independent later measurements contradict. Read that slice for its shape, which vendors appear in your segment at all and how concentrated it is, and not for its ranking.`,
    implications: [
      `${horizontal} of ${workflows} workflows run in every industry; ${specific} are sector-specific.`,
      `${segmentsWithSpecific} of ${segments} segments have workflows tagged specifically to them: a thin list means thin curation, not a sector that does nothing distinctive.`,
      "The vendor slice is a modelled May 2026 estimate: read it for shape, not for ranking.",
    ],
    action: "Investigate",
    tools: ["workflowShortlist", "modelForRole"],
    news,
    evidence: {
      count: workflows,
      sources: ["AIE workflow taxonomy", "AIE uptake model"],
      lastUpdated,
      lane: "aie",
    },
    insufficient: null,
    // Workflow types, not observed deployments. Which firms in a sector
    // actually run a workflow is exactly the question this library cannot
    // answer and an analyst can.
    thin: "these are workflow types rather than observed deployments, so nothing here says which firms in your sector actually run them",
  };
}
