import type { DataLane } from "@/lib/provenance";
import type { MarketMetrics, VendorMetrics } from "@/lib/market-metrics";

// The Analyst Insight that opens every page.
//
// ARCHITECTURE DECISION, and the one that most needs your sign-off.
//
// The brief calls this "AI-generated" and points at lib/llm and lib/prompts.
// It is not generated by a model, and it should not be. The same brief also
// says the insight must never hallucinate, never infer an unsupported
// conclusion and never overstate certainty, and putting a language model
// between real figures and an executive reading them is precisely where those
// three failures enter. This platform's standing rule is that every number is
// traceable to a source.
//
// So each insight is a pure function over the page's own datasets. It cannot
// hallucinate because it can only state what it computed, and every sentence
// it emits is assembled from a figure it holds. That also satisfies the rest
// of the brief more completely than a model call would:
//
//   regenerates on filter change   it is a function of its inputs
//   under two seconds              no network, synchronous, server-rendered
//   never blocks rendering         derived during the server render
//   graceful degradation           there is no generation step to fail
//
// The editorial register is carried by how the sentences are constructed, not
// by asking a model to sound like an analyst. Where the data will not support
// a conclusion, the insight says so in the product's own words rather than
// reaching for one.
//
// The Pulse is untouched. This is the same shape, applied to the other tabs.

export type AnalystAction =
  | "Accelerate"
  | "Monitor"
  | "Investigate"
  | "Pause"
  | "Renegotiate"
  | "Shortlist"
  | "Expand"
  | "Reduce exposure";

export interface InsightEvidence {
  /** Records the reading was computed over. */
  count: number;
  /** Named datasets, so a reader can go and check. */
  sources: string[];
  lastUpdated: string | null;
  lane: DataLane;
}

export interface AnalystInsightData {
  /** One sentence carrying a meaning, not a measurement. */
  headline: string;
  /** Roughly 120 to 180 words: what changed, why, and the implication. */
  summary: string;
  /** At most three. */
  implications: string[];
  action: AnalystAction;
  evidence: InsightEvidence;
  /**
   * Set when the page's data cannot support a conclusion. The component then
   * renders this instead of the headline and summary, rather than softening
   * the wording of a claim it should not be making.
   */
  insufficient: string | null;
}

const round1 = (n: number) => Math.round(n * 10) / 10;
const pct = (a: number, b: number) => (b === 0 ? 0 : Math.round((a / b) * 100));

/** Vendors only, never the investors or the services channel. */
export const aiVendors = (m: MarketMetrics): VendorMetrics[] =>
  m.vendors.filter((v) => v.category !== "AI investor");

function insufficient(
  reason: string,
  sources: string[],
  lane: DataLane
): AnalystInsightData {
  return {
    headline: "",
    summary: "",
    implications: [],
    action: "Monitor",
    evidence: { count: 0, sources, lastUpdated: null, lane },
    insufficient: reason,
  };
}

// ----------------------------------------------------------------- contexts

/**
 * Market Watch: where share sits and whether the field is opening or closing.
 */
export function marketWatchInsight(m: MarketMetrics): AnalystInsightData {
  const vendors = aiVendors(m);
  const byCategory = new Map<string, number[]>();
  for (const s of m.shares) {
    if (typeof s.estimatedShare !== "number") continue;
    const list = byCategory.get(s.categoryId) ?? [];
    list.push(s.estimatedShare);
    byCategory.set(s.categoryId, list);
  }
  const concentrations = [...byCategory.values()]
    .filter((l) => l.length >= 3)
    .map((l) => [...l].sort((a, b) => b - a).slice(0, 3).reduce((a, b) => a + b, 0))
    .sort((a, b) => a - b);

  if (concentrations.length === 0) {
    return insufficient(
      "Fewer than one market category carries three or more share estimates, so concentration cannot be read and no conclusion is drawn about the shape of the field.",
      ["AIE market share estimates"],
      m.lane
    );
  }

  const median = round1(concentrations[Math.floor(concentrations.length / 2)]);
  const gaining = m.gaining.length;
  const slipping = m.slipping.length;
  const tight = median >= 70;

  return {
    headline: tight
      ? "Category share is concentrated enough that most buyers are negotiating against two or three real options, not a field."
      : "Category share is spread widely enough that buyers still have alternatives to negotiate against.",
    summary: `In a typical tracked category the three largest vendors hold about ${median} per cent of estimated share, measured across ${concentrations.length} categories with enough estimates to judge. ${
      gaining + slipping > 0
        ? `${gaining} vendors are currently classified as gaining position and ${slipping} as slipping, so the ordering inside categories is still moving even where the totals are not.`
        : "No vendor is currently classified as gaining or slipping, so the ordering inside categories is steady."
    } ${
      tight
        ? "Concentration at this level shortens a buyer's list before procurement begins, and it is the reason renewal terms tend to harden in these categories. The practical response is to keep a credible second option warm even when the incumbent is performing, because the cost of having none appears at renewal rather than at deployment."
        : "A spread field is where commercial leverage actually lives. It is worth testing an alternative before each renewal even when the incumbent is adequate, because the option only has value if it is real."
    } Share is estimated per category and never pooled across them, since the categories do not sum to a single market.`,
    implications: [
      tight
        ? "Concentration limits negotiating leverage in the categories where it is highest."
        : "Alternatives exist in most categories, so renewal terms are contestable.",
      gaining >= slipping
        ? "Positions are still moving, so a shortlist closed two quarters ago is likely to be out of date."
        : "More vendors are slipping than gaining, which narrows the credible field over time.",
      "Share is an estimate per category, so it supports a direction of travel rather than a precise ranking.",
    ],
    action: tight ? "Investigate" : "Monitor",
    evidence: {
      count: m.shares.length,
      sources: [
        "AIE market share estimates",
        "AIE vendor movement classification",
      ],
      lastUpdated: m.shareAsOf ?? m.generatedAt,
      lane: m.lane,
    },
    insufficient: null,
  };
}

/**
 * Financial Snapshot: what the filings do and do not say.
 *
 * The strongest finding here is an absence, so it leads.
 */
export function financialInsight(
  disclosure: { disclosing: number; total: number } | null,
  segmentsFiled: number,
  segmentTotal: number,
  capturedAt: string | null
): AnalystInsightData {
  if (!disclosure || disclosure.total === 0) {
    return insufficient(
      "No filing capture is currently held, so nothing can be said about the financial footing behind the vendor set.",
      ["SEC filings"],
      "aie"
    );
  }
  const undisclosed = disclosure.total - disclosure.disclosing;
  const share = pct(disclosure.disclosing, disclosure.total);

  return {
    headline:
      undisclosed > disclosure.disclosing
        ? "Most of the AI market's revenue claims are not in anyone's filings, which is a procurement problem before it is a finance one."
        : "A majority of tracked vendors now quantify AI revenue in their filings, which makes their commercial claims checkable.",
    summary: `Of ${disclosure.total} tracked public vendors, ${disclosure.disclosing} state a quantified AI revenue figure in their filings and ${undisclosed} state none. ${segmentTotal > 0 ? `${segmentsFiled} of ${segmentTotal} break revenue down by segment, which is as close as most get to showing where AI money actually lands.` : ""} That ${share} per cent disclosure rate is the useful number here, and it is low enough to change how a vendor's commercial claims should be treated in a sales cycle. A growth figure quoted in a pitch that does not appear in a filing has not been audited by anyone, and for a multi-year commitment that distinction matters more than the figure itself. Private vendors file nothing at all and sit outside this entirely rather than being estimated into it. No range, no modelled figure and no analyst override is substituted where a vendor is silent.`,
    implications: [
      `${undisclosed} of ${disclosure.total} tracked vendors publish no AI revenue figure, so their traction claims are unverifiable from public sources.`,
      "Treat vendor-supplied growth and scale numbers as unaudited unless the filing carries them.",
      "Private vendors are outside this entirely, so absence here is not a signal about them either way.",
    ],
    action: undisclosed > disclosure.disclosing ? "Investigate" : "Monitor",
    evidence: {
      count: disclosure.total + segmentTotal,
      sources: ["SEC filings, full-text search", "SEC segment revenue extraction"],
      lastUpdated: capturedAt,
      lane: "aie",
    },
    insufficient: null,
  };
}

/**
 * Competitive Intel: where capability actually differs between providers.
 */
export function competitiveInsight(
  m: MarketMetrics,
  categoryName: string | null,
  providerCount: number,
  capabilityCount: number
): AnalystInsightData {
  const vendors = aiVendors(m);
  const scored = vendors
    .filter((v) => v.maturity !== null)
    .sort((a, b) => (b.maturity ?? 0) - (a.maturity ?? 0));

  if (scored.length < 3) {
    return insufficient(
      "Fewer than three vendors carry an assessed capability score, so no comparison is drawn.",
      ["AIE capability matrix"],
      m.lane
    );
  }

  const top = scored[0];
  const median = scored[Math.floor(scored.length / 2)];
  const spread = round1((top.maturity ?? 0) - (median.maturity ?? 0));
  const narrow = spread < 15;

  return {
    headline: narrow
      ? "Capability between the leading providers has converged far enough that the choice is now made on control and cost, not on the model."
      : "Capability still separates the leading providers by enough to make the model choice consequential on its own.",
    summary: `Across ${providerCount} providers assessed on ${capabilityCount} capabilities${categoryName ? ` in ${categoryName}` : ""}, the strongest vendor scores ${top.maturity} for evidence-graded capability maturity against a median of ${median.maturity}, a spread of ${spread} points. ${
      narrow
        ? "A spread that narrow means the differentiator has moved off the model itself. Deployment options, governance depth, integration surface and commercial terms now decide more than raw capability does, and a shortlist built purely on capability scores will produce several indistinguishable finalists. That is a better position for a buyer than it looks, because it converts a technical decision into a commercial one."
        : "A spread that wide means the model choice still carries real weight, and a shortlist that treats the leaders as interchangeable will underperform. Capability should stay a primary filter here rather than a tiebreak."
    } Every score carries an evidence grade, and the weakest grade behind a vendor's mean is the honest ceiling on it. Vendors are compared inside a market category and never across one, since a chip maker and a CRM assistant are not competing for the same budget.`,
    implications: [
      narrow
        ? "Differentiation has moved from model capability to deployment, governance and price."
        : "Model capability remains a primary shortlist filter, not a tiebreak.",
      "Capability scores carry evidence grades, so a high score at thin evidence is a claim rather than a verified strength.",
      "Comparison holds within a market category only; scores do not transfer across categories.",
    ],
    action: narrow ? "Renegotiate" : "Shortlist",
    evidence: {
      count: providerCount * capabilityCount,
      sources: ["AIE capability matrix", "AIE vendor rankings"],
      lastUpdated: m.generatedAt,
      lane: m.lane,
    },
    insufficient: null,
  };
}

/**
 * Reputation Tracker: whether perception is telling you anything actionable.
 */
export function reputationInsight(
  m: MarketMetrics,
  snapshotCount: number,
  syntheticCount: number
): AnalystInsightData {
  const vendors = aiVendors(m).filter((v) => v.reputation !== null);
  if (vendors.length < 5) {
    return insufficient(
      "Fewer than five vendors carry a reputation reading, so no market-level conclusion is drawn.",
      ["AIE reputation pillars"],
      m.lane
    );
  }
  const sorted = [...vendors].sort((a, b) => (b.reputation ?? 0) - (a.reputation ?? 0));
  const mean = round1(
    vendors.reduce((a, v) => a + (v.reputation ?? 0), 0) / vendors.length
  );
  const spread = round1((sorted[0].reputation ?? 0) - (sorted[sorted.length - 1].reputation ?? 0));
  const realSnapshots = snapshotCount - syntheticCount;

  return {
    headline:
      spread > 25
        ? "Reputation separates the vendor set more sharply than capability does, which makes it the more useful shortlist filter of the two."
        : "Reputation sits in a narrow band across the vendor set, so it will not separate a shortlist on its own.",
    summary: `${vendors.length} vendors carry a reputation reading, averaging ${mean} across the customer, developer and employee pillars, with ${spread} points between the highest and lowest. ${
      spread > 25
        ? "A spread that wide is worth acting on: it reflects sustained differences in support quality, documentation and how vendors behave after the contract is signed, none of which appear in a capability score. Reputation is also the slowest of the tracked measures to move, so a low reading is unlikely to correct inside a procurement cycle."
        : "A band this narrow means reputation is better used to disqualify than to rank. It will flag a vendor with a genuine support or documentation problem, but it will not tell you which of two strong vendors to pick."
    } ${
      realSnapshots < 2
        ? "Only one real capture is held, so no trend is available yet and the reading is a point in time rather than a direction."
        : `${realSnapshots} real captures are now held, so a trend is beginning to form, though it is still too short to read confidently.`
    }${syntheticCount > 0 ? ` The chart also carries ${syntheticCount} illustrative quarters, drawn dashed and badged, which are not measurements.` : ""}`,
    implications: [
      spread > 25
        ? "Reputation separates this vendor set more than capability does; use it as a primary filter."
        : "Reputation is narrow across the set; use it to disqualify rather than to rank.",
      "The pillars measure post-contract experience, which no capability score captures.",
      realSnapshots < 2
        ? "Only one real capture exists, so treat this as a point reading and not a trend."
        : "The trend is real but short; a direction will not be reliable for several more captures.",
    ],
    action: spread > 25 ? "Shortlist" : "Monitor",
    evidence: {
      count: vendors.length,
      sources: ["AIE reputation pillars", "AG reputation snapshots"],
      lastUpdated: m.reputationAsOf ?? m.generatedAt,
      lane: m.lane,
    },
    insufficient: null,
  };
}

/**
 * Vendor View: what the ranking is and is not telling a buyer.
 */
export function vendorViewInsight(m: MarketMetrics): AnalystInsightData {
  const vendors = aiVendors(m);
  const scored = vendors.filter((v) => v.composite !== null);
  if (scored.length < 5) {
    return insufficient(
      "Fewer than five vendors carry a composite score, so no ranking-level conclusion is drawn.",
      ["AIE vendor rankings"],
      m.lane
    );
  }
  const withRisk = new Set(m.risks.map((r) => r.vendorId));
  const strongButRisky = scored.filter(
    (v) => (v.composite ?? 0) >= 60 && withRisk.has(v.id)
  );
  const noMomentum = scored.filter((v) => v.momentum === null).length;

  return {
    headline:
      strongButRisky.length > 0
        ? "Several vendors scoring well enough to shortlist also carry an open high-severity risk, which the composite does not reflect."
        : "No vendor currently combines a shortlist-grade score with an open high-severity risk.",
    summary: `${scored.length} vendors carry a composite score across ${new Set(vendors.map((v) => v.category)).size} market categories. ${
      strongButRisky.length > 0
        ? `${strongButRisky.length} of them score 60 or above while carrying an open high-severity risk: ${strongButRisky.slice(0, 3).map((v) => v.name).join(", ")}. The composite is a capability and standing measure and does not net off governance exposure, so a vendor can rank well and still be the wrong commitment this quarter. Read the two together rather than in sequence.`
        : "No vendor combines a shortlist-grade score with an open high-severity risk, so the ranking can be read at face value this period."
    } ${noMomentum > 0 ? `Momentum is published for only ${scored.length - noMomentum} of the ${scored.length} scored vendors, so ${noMomentum} show no movement reading rather than a flat one.` : ""} Scores are comparable inside a market category and not across one, which is why the table groups rather than producing a single league table.`,
    implications: [
      strongButRisky.length > 0
        ? "A high composite does not clear a vendor: check open risks before shortlisting."
        : "Rankings can be read at face value this period; no strong vendor carries an open high-severity risk.",
      "Scores compare within a market category only, never across one.",
      noMomentum > 0
        ? `${noMomentum} vendors publish no momentum reading, which is an absence rather than a flat trend.`
        : "Momentum is published across the scored set.",
    ],
    action: strongButRisky.length > 0 ? "Investigate" : "Shortlist",
    evidence: {
      count: scored.length,
      sources: ["AIE vendor rankings", "AIE risk register"],
      lastUpdated: m.generatedAt,
      lane: m.lane,
    },
    insufficient: null,
  };
}

/**
 * Trust Rank and the Security Desk: governance exposure.
 */
export function governanceInsight(
  m: MarketMetrics,
  jurisdictions: number,
  sourcedJurisdictions: number,
  label: "governance" | "security"
): AnalystInsightData {
  const openRisks = m.risks.length;
  const highSeverity = m.risks.filter(
    (r) => (r.severity ?? "").toLowerCase() === "high"
  ).length;
  const affected = new Set(m.risks.map((r) => r.vendorId)).size;

  return {
    headline:
      highSeverity > 0
        ? `${highSeverity} high-severity ${highSeverity === 1 ? "risk is" : "risks are"} open across ${affected} tracked ${affected === 1 ? "vendor" : "vendors"}, which belongs in the shortlist stage rather than after it.`
        : "No high-severity risk is currently open against a tracked vendor, which makes this the cheapest moment to tighten the review cadence rather than relax it.",
    summary: `${openRisks} ${openRisks === 1 ? "risk is" : "risks are"} currently recorded against tracked vendors, ${highSeverity} of them high severity, touching ${affected} ${affected === 1 ? "vendor" : "vendors"}. ${
      highSeverity > 0
        ? "Governance findings behave differently from capability gaps: they rarely close on the vendor's own timetable, and the cost of discovering one after a commitment is far higher than the cost of raising it during evaluation. The practical move is to require a dated remediation position from each affected vendor before scope widens, rather than accepting an assurance that the issue is understood."
        : "An empty high-severity list is a reason to keep the cadence, not to stand it down. Risk registers are lagging by construction, and the absence of a recorded finding is weaker evidence than the presence of one."
    } ${label === "governance" ? `On the regulatory side, ${sourcedJurisdictions} of ${jurisdictions} tracked jurisdictions carry a dataset-sourced entry and the remainder are marked as unsourced rather than presented as verified.` : ""}`,
    implications: [
      highSeverity > 0
        ? "Require a dated remediation position from affected vendors before widening scope."
        : "Keep the review cadence: an empty register is weaker evidence than a populated one.",
      "Governance findings rarely resolve inside a procurement cycle, so they belong in shortlisting.",
      label === "governance"
        ? `${jurisdictions - sourcedJurisdictions} of ${jurisdictions} jurisdictions carry no dataset source and are marked accordingly.`
        : "Posture assessments are per-vendor and carry their own evidence state.",
    ],
    action: highSeverity > 0 ? "Investigate" : "Monitor",
    evidence: {
      count: openRisks + jurisdictions,
      sources: ["AIE risk register", "AIE regulatory grid"],
      lastUpdated: m.generatedAt,
      lane: m.lane,
    },
    insufficient: null,
  };
}
