"use client";

import { useEffect, useState } from "react";
import { brFetch, type BrResult, type BrSource } from "@/lib/br-client";
import { LaneBadge } from "@/lib/ui/badges";
import { DerivationDrawer } from "@/lib/ui/score";
import { MicroLabel } from "@/lib/ui/micro";
import type {
  OverviewResponse,
  ProbedTicker,
  QuickMetricsResponse,
} from "../types";

interface FetchState<T> {
  loading: boolean;
  source: BrSource;
  data: T | null;
  errorCode: string | null;
}

const idle = <T,>(): FetchState<T> => ({
  loading: true,
  source: "live",
  data: null,
  errorCode: null,
});

function fromResult<T>(res: BrResult<T>): FetchState<T> {
  return {
    loading: false,
    source: res.source,
    data: res.ok ? res.data : null,
    errorCode: res.ok ? null : (res.errorCode ?? "UNKNOWN"),
  };
}

function SourceBadge({ state }: { state: FetchState<unknown> }) {
  if (state.loading) return <LaneBadge lane="live" />;
  return <LaneBadge lane={state.source === "mock" ? "mock" : "live"} />;
}

function LoadingNote() {
  return (
    <p className="py-6 text-center font-mono text-[11px] text-muted">
      Fetching live figures... the first call for a ticker can take several
      seconds while BoardRadar computes.
    </p>
  );
}

function ErrorNote({ code }: { code: string }) {
  return (
    <p className="py-6 text-center font-mono text-[11px] text-muted">
      Live data unavailable ({code}); no figure shown rather than a guess.
    </p>
  );
}

// Direction color for the change column, keyed off the API string as
// returned (leading "+" or "-"); the value itself is never reformatted.
function changeClass(change: string): string {
  if (change.startsWith("+")) return "text-good";
  if (change.startsWith("-")) return "text-error";
  return "text-muted";
}

// Live public-ticker section: selector over the probed BoardRadar set, then
// the overview summary and quick-metrics table exactly as the API returns
// them. LIVE badge, mock fallback badge, friendly error state.
export function LiveTickers({ tickers }: { tickers: ProbedTicker[] }) {
  const [selected, setSelected] = useState(tickers[0]?.ticker ?? "MSFT");
  const [overview, setOverview] = useState<FetchState<OverviewResponse>>(idle);
  const [metrics, setMetrics] = useState<FetchState<QuickMetricsResponse>>(idle);

  const selectedMeta = tickers.find((t) => t.ticker === selected);

  useEffect(() => {
    let cancelled = false;
    setOverview(idle());
    setMetrics(idle());
    brFetch<OverviewResponse>("financial-snapshot/overview", {
      ticker: selected,
    }).then((res) => {
      if (!cancelled) setOverview(fromResult(res));
    });
    brFetch<QuickMetricsResponse>("financial-snapshot/quick-metrics", {
      ticker: selected,
    }).then((res) => {
      if (!cancelled) setMetrics(fromResult(res));
    });
    return () => {
      cancelled = true;
    };
  }, [selected]);

  return (
    <section>
      <div className="flex flex-wrap items-center gap-2">
        <MicroLabel
          label="Public tickers, live"
          tooltip="Every figure in this section comes straight from the BoardRadar financial-snapshot endpoints for the selected ticker. Nothing is adjusted or recalculated."
        />
      </div>
      <div className="mt-2 flex flex-wrap gap-1.5">
        {tickers.map((t) => (
          <button
            key={t.ticker}
            type="button"
            onClick={() => setSelected(t.ticker)}
            className={`rounded-full border px-2.5 py-1 font-mono text-[11px] font-semibold transition ${
              selected === t.ticker
                ? "border-primary bg-primary text-white"
                : "border-base-300 bg-base-100 text-base-content/75 hover:border-primary hover:text-primary"
            }`}
            title={t.name}
          >
            {t.ticker}
          </button>
        ))}
      </div>
      {selectedMeta?.financialsOnly ? (
        <p className="measure mt-1.5 text-[11px] text-muted">
          {selectedMeta.name} is covered for financials only: it is not in the
          wider BoardRadar company universe, so other modules show honest empty
          states for it.
        </p>
      ) : null}

      <div className="mt-3 grid grid-cols-1 gap-4 @4xl:grid-cols-5">
        {/* Overview summary card */}
        <div className="@container rounded-lg border border-base-300 bg-base-100 p-4 @4xl:col-span-2">
          <div className="flex flex-wrap items-start justify-between gap-2">
            <MicroLabel
              label="Company overview"
              tooltip="Narrative summary generated by BoardRadar from the company's latest disclosed financials."
            />
            <SourceBadge state={overview} />
          </div>
          {overview.loading ? (
            <LoadingNote />
          ) : overview.errorCode ? (
            <ErrorNote code={overview.errorCode} />
          ) : overview.data ? (
            <div className="mt-2">
              <h3 className="text-[15px] font-bold">
                {overview.data.companyName}
              </h3>
              <p className="mt-0.5 font-mono text-[10px] text-muted">
                {overview.data.sector} / {overview.data.industry}
              </p>
              <p className="measure mt-2 text-[13px] leading-relaxed text-base-content/85">
                {overview.data.summary}
              </p>
              <p className="mt-3 font-mono text-[10px] text-muted">
                GENERATED{" "}
                {new Date(overview.data.timestamp).toLocaleDateString("en-GB", {
                  day: "numeric",
                  month: "short",
                  year: "numeric",
                })}
              </p>
            </div>
          ) : null}
        </div>

        {/* Quick metrics table */}
        <div className="@container rounded-lg border border-base-300 bg-base-100 p-4 @4xl:col-span-3">
          <div className="flex flex-wrap items-start justify-between gap-2">
            <MicroLabel
              label="Quick metrics"
              tooltip="The BoardRadar quick-metrics set for the selected ticker: figure names, values, prior period and change, rendered exactly as returned."
            />
            <SourceBadge state={metrics} />
          </div>
          {metrics.loading ? (
            <LoadingNote />
          ) : metrics.errorCode ? (
            <ErrorNote code={metrics.errorCode} />
          ) : metrics.data ? (
            <div className="mt-2 overflow-x-auto">
              <table className="w-full text-[12.5px]">
                <thead>
                  <tr className="border-b border-base-300 text-left">
                    <th className="micro-label py-1.5 pr-2 font-normal">Metric</th>
                    <th className="micro-label py-1.5 pr-2 font-normal">Current</th>
                    <th className="micro-label py-1.5 pr-2 font-normal">Previous</th>
                    <th className="micro-label py-1.5 pr-2 font-normal">Change</th>
                    <th className="micro-label py-1.5 font-normal">Period</th>
                  </tr>
                </thead>
                <tbody>
                  {metrics.data.metrics.map((m) => (
                    <tr key={m.name} className="border-b border-base-300/60">
                      <td className="py-2 pr-2 font-medium">{m.name}</td>
                      <td className="py-2 pr-2 font-mono">{m.current}</td>
                      <td className="py-2 pr-2 font-mono text-muted">
                        {m.previous}
                      </td>
                      <td
                        className={`py-2 pr-2 font-mono font-semibold ${changeClass(m.change)}`}
                      >
                        {m.change}
                      </td>
                      <td className="py-2 font-mono text-muted">{m.period}</td>
                    </tr>
                  ))}
                </tbody>
              </table>
              <div className="mt-2 flex items-center justify-between">
                <DerivationDrawer title="How these figures are derived">
                  <p>
                    Both cards call the BoardRadar financial-snapshot endpoints
                    (overview and quick-metrics) for the selected ticker through
                    the server-side proxy. Values, prior periods, change figures
                    and period labels are rendered exactly as the API returns
                    them; nothing is recalculated or estimated on this page.
                  </p>
                  <p className="measure text-muted">
                    A LIVE badge means the figures came from the upstream API on
                    this visit. A Cached sample badge means the live call was
                    unavailable and a recorded response is shown instead. When
                    neither is possible the card says so and shows no figure.
                  </p>
                </DerivationDrawer>
                <span className="font-mono text-[10px] text-muted">
                  GENERATED{" "}
                  {new Date(metrics.data.timestamp).toLocaleDateString("en-GB", {
                    day: "numeric",
                    month: "short",
                    year: "numeric",
                  })}
                </span>
              </div>
            </div>
          ) : null}
        </div>
      </div>
    </section>
  );
}
